### ISSUE TITLE
Inconsistent encoding?

### ISSUE THREAD

**Issue by pmichna** [js-cookie/js-cookie#109]
I want to save current date in a cookie with:

    Cookies.set('discount_timer', new Date())

`new Date()` returns `Fri Oct 30 2015 09:45:30 GMT+0100 (CET)`

What is really saved in the cookie is:

    Fri%20Oct%2030%202015%2009:45:30%20GMT+0100%20(CET)

Why isn't the plus sign after "GMT" encoded while the spaces are encoded?

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for creating the issue.

The [docs says](https://github.com/js-cookie/js-cookie/tree/d832048dcf6526081c773f2014815292b7135827#json) that:

> When creating a cookie you can pass an Array or Object Literal instead of a string in the value.

Therefore, the only supported types in the cookie value are a [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String), an [Object Literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals) and an [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array), the behavior is undefined for any other type that is passed instead of the ones that are documented.

> Why isn't the plus sign after "GMT" encoded while the spaces are encoded?

The [docs says](https://github.com/js-cookie/js-cookie/tree/d832048dcf6526081c773f2014815292b7135827#encoding) that:

> This project is RFC 6265 compliant. All special characters that are not allowed in the cookie-name or cookie-value are encoded with each one's UTF-8 Hex equivalent using percent-encoding.
The only character in cookie-name or cookie-value that is allowed and still encoded is the percent % character, it is escaped in order to interpret percent input as literal.

According to [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1), the "plus sign" is allowed in the cookie value (see the `%x23-2B` part in section 4.1.1), therefore it doesn't need to be encoded.

This is not inconsistent encoding, it is actually pretty consistent.

**Comment by pmichna** [comment]
Maybe it would be a good idea to make it possible to save values in cookies with encoded '+' sign (or any others)? There is a converter that can read values from cookies. What about something similar for writing values to cookies?

Current situation hurts me, because I'm trying to use cookie values in my Rails application which tries to decode every character, so it treats '+' as space.

**Comment by FagnerMartinsBrack** [comment]
> Current situation hurts me

I am aware of that.

> What about something similar for writing values to cookies?

Definitely, see #71. I plan releasing it for 2.1.0, with no ETA. In the meantime you can build the `write-converters` branch.

You can find additional docs [here](https://github.com/js-cookie/js-cookie/blob/951353e99115746fe8afb186c084894f96d0161e/SERVER_SIDE.md) (in development).

**Comment by FagnerMartinsBrack** [comment]
I [just merged](https://github.com/js-cookie/js-cookie/commit/0fe470c76d254fa413c56bd83e77fcb0a6d5f29b) the write converter in the master branch.
