### ISSUE TITLE
update cookie

### ISSUE THREAD

**Issue by hon** [js-cookie/js-cookie#112]
I've set the cookie with expire time. 
```javascript
Cookie.set('key', 'value', {expires: 1});
```
How to update it without new expire time?
```javascript
//will this work?
Cookie.set('key', 'value');
```

**Comment by cassiocardoso** [comment]
It works.

**Comment by FagnerMartinsBrack** [comment]
As a safe measure I recommend to remove the previous cookie in order to prevent creating duplicates. We have plans to document the behavior for duplicated cookies, see https://github.com/js-cookie/js-cookie/issues/37#issue-73288279. When that is documented, this kind of question will probably be answered.

In the meantime I recommend asking in stackoverflow under the tag `js-cookie`.
