### ISSUE TITLE
Add "enabled" property or function

### ISSUE THREAD

**Issue by rgm3** [js-cookie/js-cookie#115]
It would be nice to have an enabled function that sets a test cookie and deletes it and updates a property when successful, and memoizes the result, allowing handy semantics like `if (!Cookies.enabled) { ...` by instantiating the library.

**Comment by FagnerMartinsBrack** [comment]
What is the use case?

**Comment by rgm3** [comment]
As a web developer, I want to detect that cookies are disabled so that I can warn the user of a degraded experience or of a system requirement. I expect that my cookie library would support this use case "by default."

**Comment by FagnerMartinsBrack** [comment]
I understand the requirements and the benefit of such feature. The reason why I asked for the use case is that as far as I remember nobody else have requested this in the past, you are the first one who request this. Is there a real application in which you feel the need for this feature instead of doing something like below?

```javascript
var isCookieEnabled = function() {
  var name = "dummy-" + Math.random();
  Cookies.set( name, "1" );
  return !!Cookies.get( name);
};
isCookieEnabled(); // true
```

Some code snippets showing the usage would also be very useful.

I personally don't feel like this would be useful for the majority of users of the lib and would be better being handled in the developer environment. The developer can have a much better control over the name of the dummy cookie than a general purpose library.

I will wait to see what @carhartl thinks about it.

**Comment by FagnerMartinsBrack** [comment]
> ... as far as I remember nobody else have requested this in the past

Some people did twice. See https://github.com/carhartl/jquery-cookie/pull/348 and https://github.com/carhartl/jquery-cookie/pull/58.

**Comment by rgm3** [comment]
Your example doesn't clean up after testing.  The library could perform this test at instantiation time and store the result for the developer's convenience. I understand that it's simple, but I also feel that it would be common and therefore useful as a library feature to avoid the need for repeated writing by each developer.  In my case I want to explain to the user of my web application that some things work better if they turn on cookies, and that they are being asked about a preference again because it is relevant to their client (most preferences in my app are stored in the database server-side, but cookies are appropriate for some things).

**Comment by FagnerMartinsBrack** [comment]
> The library could perform this test at instantiation time and store the result for the developer's convenience

If this go forward, we need to consider if cookies are disabled without a page load and if the request is made through iframes. The expectation is that the API returns `true` or `false` at any moment of execution in the browser main Thread, not just when the script is loaded. I am not sure how browsers handle external events like changing the cookie preferences when a page is already loaded.

**Comment by carhartl** [comment]
Here are my objections. First of all, it sounds like the proposed feature seems to be a nice to have ("It would be nice to have..."). In my experience, nice to haves in libraries quickly turn into bloat (the moment you add them actually). 

Secondly, and maybe more importantly, I refrain from adding the feature because, as mentioned by @FagnerMartinsBrack , it can't be implemented in a relyable fashion. I would consider a generalized api that detects when an expected cookie is available or not, i.e. when it disappears, already a bit more useful. A user may delete cookies at any point in time and that would have the same effect as if it wasn't written in the first place. If you have to build critical application features on top of client-side cookie handling, that would allow you to react accordingly in both cases. But do we really want to handle these scenarios? The effort of implementation (service workers?) doesn't justify the benefit imo. 

For a poor-man's detection, is asking the developer to write the following one-liner asking too much?

```js
Cookies.enabled = !!Cookies.set("__CookiesEnabled?__", 1);

if (Cookies.enabled)
  // yum
```

**Comment by carhartl** [comment]
PS: What's the status of `navigator.cookieEnabled`? Haft that ever been implemented in browsers other than Firefox?

PPS: Someone using modernizr could use that libraries cookie detection: https://github.com/Modernizr/Modernizr/blob/master/feature-detects/cookies.js

**Comment by FagnerMartinsBrack** [comment]
>  In my experience, nice to haves in libraries quickly turn into bloat

jQuery is a good example of that: https://github.com/jquery/jquery/issues/1866#issuecomment-62957452

> For a poor-man's detection, is asking the developer to write the following one-liner asking too much?

> ```javascript
> Cookies.enabled = !!Cookies.set("__CookiesEnabled?__", 1);
>
> if (Cookies.enabled)
>   // yum
> ```

The return of the `Cookies.set()` API is assumed to be "not defined" because the returned String is not publicly documented and just used internally and for test purposes. We need to document something in order to suggest the use of `!!Cookies.set("__CookiesEnabled?__", 1)` in production, even if we do not document the format, but just something like (returns a truthy value if the cookie could be created).

I say this to prevent encouraging the use of undocumented stuff and locking the code, which makes the lib impossible to extend in the future if necessary (without a major bump), see #117 for an example.

> A user may also delete cookies at any point in time and that would have the same effect as if it wasn't written in the first place

If it creates and removes the cookie in the browser main thread, then there is no time for the user to remove it, because the execution blocks. All cookie detection methods that I have seen relied on setting and removing a cookie in the main thread, none of them seem to have drawbacks due to the user deleting some cookie.

> Someone using modernizr could use that libraries cookie feature detection:

I agree that to check if the cookie is enabled one should use a specific library for that like Modernizr. I see they have done a very good research on that and have much more experience in detecting features, as demonstrated in their comments:

```javascript
// navigator.cookieEnabled cannot detect custom or nuanced cookie blocking
// configurations. For example, when blocking cookies via the Advanced
// Privacy Settings in IE9, it always returns true. And there have been
// issues in the past with site-specific exceptions.
// Don't rely on it.

// try..catch because some in situations `document.cookie` is exposed but throws a
// SecurityError if you try to access it; e.g. documents created from data URIs
// or in sandboxed iframes (depending on flags/context)
```

I believe we should leave browser feature detection for the ones that are specialized at it.

**Comment by FagnerMartinsBrack** [comment]
It seems we are not going for an `enabled` functionality this time to prevent bloating issues. Better delegate such support for a great tool like Modernizr.

Thanks for opening this issue though, it was a great discussion.

**Comment by rgm3** [comment]
I understand, and although I disagree and am disappointed I respect your decision.  Thanks for giving it due consideration.

**Comment by westy92** [comment]
I'm using the following code which also cleans up the temporary cookie:

```javascript
var cookiesEnabled = !!Cookies.set('__CookiesEnabled?__', 1) 
  && !!Cookies.get('__CookiesEnabled?__') 
  && (Cookies.remove('__CookiesEnabled?__') || true);
```

**Comment by FagnerMartinsBrack** [comment]
@westy92 I really recommend using [Modernizr code](https://github.com/Modernizr/Modernizr/blob/5e3f359bfc9aa511543ece60bd8a6ea8aa7defd3/feature-detects/cookies.js#L16-L35) to do this, unless you have specific requirements. Modernizr is very well tested and created by great developers.
