### ISSUE TITLE
Impact of `window.json` to results of `Cookies('somekey')`

### ISSUE THREAD

**Issue by DiamondeX** [js-cookie/js-cookie#117]
When someone set `window.json` to any value that evaluates to `true` (not to work with cookies) and then calls `Cookies('somekey')`, he will get json-parsed value instead of expected value itself.

**Comment by DiamondeX** [comment]
for example, we set:
```js
Cookies("ticket", "[45e2]");
```
then
```js
window.json = '{"someKey": "someValue"}';
```
Now we expect :
```js
console.log(Cookies("ticket"));  // "[45e2]" (string)
```
but we've got
```js
console.log(Cookies("ticket"));  // [4500] (array)
```

**Comment by DiamondeX** [comment]
One of workarounds is always call `api` itself with brand new object as context like this:
```js
    //...
    api.defaults = {};

    var api2 = api.bind({});
    api2.set = api2.get = api2;
    api2.getJSON = function () {
      return api.apply({
        json: true
      }, [].slice.call(arguments));
    };

    api2.remove = function (key, attributes) {
      api2(key, '', extend(attributes, {
        expires: -1
      }));
    };

    api2.withConverter = init;

    return api2;
    //...
```
Notice call to original `api` inside `api2.getJSON` body

**Comment by DiamondeX** [comment]
I'd provided pull request with suitable changes

**Comment by FagnerMartinsBrack** [comment]
There is no such public API as `Cookies("name", "value")` or `Cookies("ticket")`.

In the ["Basic Usage"](https://github.com/js-cookie/js-cookie/tree/0fe470c76d254fa413c56bd83e77fcb0a6d5f29b#basic-usage) section is documented:

* `Cookies.set('name', 'value');` to set the cookie
* `Cookies.get('name');` to get the cookie

**Comment by FagnerMartinsBrack** [comment]
I will assume this as wrong usage of the API. Just because the code can do something it doesn't mean that it is publicly available (documented). It is not recommended to use interfaces that are not publicly available because they can break at any time without further notice, even in patch versions.

* If you believe that the docs doesn't make the public api clear, feel free to suggest improvements.
* If you want to suggest a new API, feel free to create an issue so we can discuss about it.
