### ISSUE TITLE
Support TypeScript's DefinitelyTyped

### ISSUE THREAD

**Issue by redstrike** [js-cookie/js-cookie#124]
TSD (TypeScript Definition manager) is lacking js-cookie's d.ts.
I think a popular project like js-cookie should support TypeScript.

**Comment by FagnerMartinsBrack** [comment]
Some folks handled that right in the begining of the new namespace: https://github.com/js-cookie/js-cookie/issues/50

What do you suggest?

**Comment by redstrike** [comment]
Oh, **js-cookie.d.ts** is available on DefinitelyTyped's repo. I did not found js-cookie via the search box on TSD's homepage, so I thought that.

Besides, why js-cookie doesn't contain a minified version in the repo? The source file in /src also has inconsistent name, "js.cookie.js" vs "js-cookie.js"). I am using Bower to manage the dependencies, so these issues cause me some small problems.

**Comment by FagnerMartinsBrack** [comment]
> I did not found js-cookie via the search box on TSD's homepage

It would be interesting to report an issue for them to make it easy the discovery of js-cookie through their search tool.

> Besides, why js-cookie doesn't contain a minified version in the repo?

See https://github.com/js-cookie/js-cookie/issues/73

> The source file in /src also has inconsistent name, "js.cookie.js" vs "js-cookie.js")
> I am using Bower to manage the dependencies, so these issues cause me some small problems.

Could you please create a new issue explaining in details which bower issues you have? Be aware that programatically using the unminified version from this repository `src` is **not supported**. What we support is the use of a build routine to run the project locally and generate the minified file. We have plans to add a minified version to the releases (see above), but the related PR #82 doesn't seems to be moving much faster. We welcome contributions to that PR branch, since the requirements are pretty clear in the description.

**Comment by redstrike** [comment]
> It would be interesting to report an issue for them to make it easy the discovery of js-cookie through their search tool.

I did it here https://github.com/DefinitelyTyped/tsd-site/issues/4

> Could you please create a new issue explaining in details which bower issues you have?

I think it's not worth to create a new issue for this. It's just my workflow's problem. Because I prefer to download js-cookie and manage it via Bower, so lacking the minified version causes my project's build process some tiny overhead for re-parsing and Uglify that portion of code again & again.

**Comment by ericnewton76** [comment]
Realistically your build process shouldnt be that bad.  Build Automation tools like Gulp are gaining support for dealing with changed files only, so unless you're taking all your files and bundling them, your incremental "active development" builds should get tight, and a final "deploy" build would be where you'd take the hit.

A lot of JS developers try to get away with not having a deploy build, but it solves many problems.
