### ISSUE TITLE
Add support for key=value& within the cookie aka "MultiValued Cookies"

### ISSUE THREAD

**Issue by ericnewton76** [js-cookie/js-cookie#127]
would be nice to have built-in support for multivalued cookies that utilize the key=value format

    function getCookieFilters() {
        try { 
            var filtersCookie = Cookies("filters");
            if(filtersCookie) {
                var filters = [];
                if(filtersCookie["r"]) filters.push("custom_s_regionkey:" + filtersCookie["r"]);
                if(filtersCookie["ct"]) filters.push("custom_s_customertype:" + filtersCookie["ct"])
                return filters;
            }
        }
        catch(e) { console.error(e); }
        return [];
    }

**Comment by FagnerMartinsBrack** [comment]
There is a mistake in your code:

```javascript
 var filtersCookie = Cookies("filters");
```

There is no such API as `Cookies(String)`, see https://github.com/js-cookie/js-cookie/issues/117#issuecomment-163961408 for context.

There is support for key/value storage using JSON. Just use the `Cookies.getJSON` API as [documented in the README.md](https://github.com/js-cookie/js-cookie/tree/v2.1.0#json):

```javascript
var filtersCookie = Cookies.getJSON("filters");
filtersCookie["r"];
filtersCookie["ct"];
```

**Comment by ericnewton76** [comment]
Sorry. I missed pasting in the require statement, utilizing it as module named Cookies

You mention GetJson but does that work for the format ```key=value&key2=value2```?  These cookies aren't in Json

**Comment by FagnerMartinsBrack** [comment]
> I missed pasting in the require statement, utilizing it as module named Cookies

Even with the require statement it is still wrong, there is no documented `Cookies(String)` API. This can break in a minor version without notice.

```javascript
var Cookies = require( "js-cookie" );
Cookies( "key" ) <-- There is no such API
Cookies.get( "key" ) <-- This is documented and supported though
```

> You mention GetJson but does that work for the format key=value&key2=value2? These cookies aren't in Json

You can always use something like `jQuery.param` to convert a querystring to JSON and then store a JSON in the cookie. What is you use case for storing a cookie in the format `key=value&key2=value2` instead of `{ "key": value, "key2": "value2" }` in the `document.cookie`?

**Comment by ericnewton76** [comment]
The use case for that is the cookie is written out by another project in ASP.Net which introduced the multivalue concept a while ago.  Basically, within asp.net, you create the cookie like so

```c#
public void WriteCookie()
{
    HttpCookie cookie = new HttpCookie("thecookie");
    cookie["r"] = "region";
    cookie["ct"] = "customertype";
    Response.Cookies.Set(cookie);
}
```

this renders out a cookie like what you've seen:
```
Set-Cookie: thecookie=r=region&ct=customertype
```

I'm thinking that this could definitely be a MultiValueConverter of sorts, that could detect '&' within the raw cookie value and return back an associative array/object with each key value pair.

If I send a PR would you consider it integrating it as another "built-in" converter?

**Comment by FagnerMartinsBrack** [comment]
Looks like I understand now:

This request asks for the integration with a third party server-side framework that encodes the cookies in a different format other than JSON in which the client does not have control.

As far as I am concerned, this is a "nice to have":

> would be nice to have built-in support for multivalued cookies

Therefore I have to quote @carhartl here [from a similar issue](https://github.com/js-cookie/js-cookie/issues/115#issuecomment-164373569):

> In my experience, nice to haves in libraries quickly turn into bloat (the moment you add them actually).

And I tend to agree with him. It doesn't seems to be enough evidence to justify the inclusion of a different parsing mechanism in a lib like js-cookie for everyone that uses it. The purpose of this library is only to make it easy how to set and retrieve a cookie. JSON was [only added](https://github.com/js-cookie/js-cookie/pull/10) due to the huge amount of requests in `jquery.cookie` age.

I would like to point out into an alternative though, see https://github.com/js-cookie/js-cookie/pull/123. There, we reached a conclusion that creating a separate module that integrates with js-cookie was much better instead of adding a needless feature to everyone (in this specific case, for those that might not be using Asp.net). The action we can take though, is document a pattern to extend js-cookie to accept custom plugins or something like that. Right now it is not trivial to add a new property to the `Cookies` namespace, see https://github.com/luanpotter/js-cookie-remove-all/pull/1#discussion_r49685742.

@ericnewton76 Looking forward on your feedback.

**Comment by FagnerMartinsBrack** [comment]
@ericnewton76 
What if this is exposed as a custom converter in a different module? Recently we had a similar issue in which someone was requesting a `removeAll` feature for js-cookie, we reached into an agreement that the best approach would be to create a separate module so we wouldn't clutter js-cookie. See https://github.com/js-cookie/js-cookie/pull/123.

Does that make ense for this use case? Looking for feedback.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.

If anyone reading this have the same need then I suggest creating a custom [read/write converter](https://github.com/js-cookie/js-cookie/tree/v2.1.0#converters) that it will do the job successfully.
