### ISSUE TITLE
Broadcast/listen to addition/removal of cookie

### ISSUE THREAD

**Issue by idokleinman** [js-cookie/js-cookie#132]
very useful for cases where a single sign on cookie is created across several services in same domain so the other services can login or out automatically (without refreshing the page) when one of the services got logged in or out

**Comment by FagnerMartinsBrack** [comment]
This seems out of scope of this project, see https://github.com/js-cookie/js-cookie/issues/115#issuecomment-164373569

The intent of js-cookie is to act as a low level API to make it easy to handle cookies in the browser. Adding an observer pattern on top of it seems to be unnecessary bloat. Maybe it makes more sense to be implemented on a full featured framework like Angular?

We need to be cautious for not adding lots of stuff to keep the lib smaller as possible under 1k gzipped size.

@carhartl

**Comment by carhartl** [comment]
Such functionality seems more like application instead of library level code. 

It could be implemented as an extension though. Furthermore one can already implement an event publishing read/write function using (abusing) converters I believe.

**Comment by carhartl** [comment]
(Maybe we should not have called them converters but callbacks.)

**Comment by carhartl** [comment]
It will surely require another component to handle registering subscribers etc. - which is then said application level code - but the foundation may exist for the rest.

**Comment by FagnerMartinsBrack** [comment]
> ... one can already implement an event publishing read/write function using (abusing) converters I believe ...

I hope one doesn't do that xD

The converters were created exclusively for the purpose of working around server-side encoding issues, although it seems that [we will still see people some using it for other purposes](https://github.com/js-cookie/js-cookie/issues/127#issuecomment-173335744).

**Comment by carhartl** [comment]
And why shouldn't they? Techically, they resemble callbacks.

Imo, in hindsight, we were wrong calling them converters. And by doing so restricting usage (or apparently hoping to do so). 

http://hintjens.com/blog:94 (Rule 6)

**Comment by carhartl** [comment]
Furthermore I disagree that converters were created solely in order work around encoding issues. At least not when I introduced them in the old jquery-cookie.

The example from the docs was this:

```js
$.cookie('foo', Number)
```

That's where the name converter actually came from. As such they were meant to provide a concise, intentful way to convert the value to another representation. They weren't called encoders or something.

**Comment by FagnerMartinsBrack** [comment]
I understand, but the problem with trying to use converters for general purposes, even for converting representations, is that you can't do everything from all use cases with it. It returns the value that is going to be used for the cookie value and executes it instead of the actual default encoding/decoding mechanism. For example, you can't change how the cookie **names** (not the values) are encoded/decoded (although you can extend it by allowing to return an object). It is expected from the dev to provide the whole encoding/decoding of the cookie value, which is too much overhead if you just want to create types with it.

In other hand, it is not possible to create a general purpose callback that fixes this server-side encoding issue and also allows the dev to do everything for all use cases. The reason for that is that we can't actually predict if, for all use cases, the callback should execute before the encoding (to fix encoding issues) or after the encoding (to implement or execute something else after encoding is done).

I don't understand how this violates the 6th rule of good API design. The converter API is extensible (and a lot):

* We can implement something that returns an object to change the decoding/encoding of the cookie name (it currently only changes the value)
* We can call with additional arguments to expose the default encoding strategy (instead of the dev having to implement everything from scratch, he can leverage the default strategy)
* We can pass the already encoded key/names as additional arguments (although it would need some effort)

The point is that, as it is documented, the purpose of the converter API is to deal with server-side incompatibilities because that is the most reported type of issue. We can extend it and allow it to be used for several purposes, but only related to converting the cookie data.

If we still want to use the same API for everything, then the only restriction is that it should allow the developer to return something before the actual encoding/decoding is applied. If we want to allow the function to be executed after the encoding is applied into it's final state, then it is something that can't be handled for only one general purpose callback.

A good analogy is the DOM events. We can't create a general purpose callback to execute before and after the modal is open, we need to choose either before, after or both. If we choose both, then we need two callbacks (`show` and `shown`). In js-cookie case, to potentially cover this specific use case without forcing the dev to write the encoding/decoding mechanism, we need to leave converters to execute before encoding and create something else for after the encoding.

For the `Number` case, you can easily use `Cookies.getJSON` that converts it out of the box without the need of converters. I just don't think it's worth adding more responsibilities to an API that currently is solving a very specific kind of problem that was requested several times.

**Comment by carhartl** [comment]
I think the main issue here is that I obviously didn't keep up with the development. I think it's time to officially retire me from the project.

**Comment by FagnerMartinsBrack** [comment]
I don't think that is a problem at all. Additional feedback always yelds the best result, if necessary I can provide the context and details that will make it possible to keep up.

**Comment by FagnerMartinsBrack** [comment]
@idokleinman Do you have a code sample where this feature might be useful in a way that it can't be done otherwise by an external framework consuming js-cookie as is now?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP, unfortunately without further information for this use-case we can't take any action.

If anyone has the same use-case, please create a new issue with an example or perhaps an idea of how to implement this, for now one can just implement a custom observer pattern with a decorator without js-cookie having to implement one. Below is quick and dirty/pseudo/untested solution from the top of my mind:

```javascript
var observer = {
  clients: []
  onRemoveCookie: function( observed ) {
    this.clients.push( observed );
  },
  onCreateCookie: function( observed ) {
    this.clients.push( observed );
  },
  trigger: function( event ) {
    this[event]();
  }
};

function setCookieDecorated() {
  observer.trigger( "onCreateCookie" );
  Cookies.set.apply( this, arguments );
}
function removeCookieDecorated() {
  observer.trigger( "onRemoveCookie" );
  Cookies.remove.apply( this, arguments );
}

// Usage

observer.onRemoveCookie(function() {
  alert( "It was removed!" );
});
observer.onCreateCookie(function() {
  alert( "It was created!" );
});

setCookieDecorated( "name", "value" ); // Executed alert!
removeCookieDecorated( "name" ); // Executed alert!
```
