### ISSUE TITLE
Remove all cookies on One operation

### ISSUE THREAD

**Issue by DeadcatDev** [js-cookie/js-cookie#134]
Something  about Cookies.removeAll(); to clear cookies.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/pull/123

**Comment by FagnerMartinsBrack** [comment]
Also, if you don't want to import a new module, you could simply use something like this in your own side:

```javascript
Object.keys(Cookies.get()).forEach(function(cookie) {
  Cookies.remove(cookie, attributes);
});
```

I don't see the need of having this built-in in the lib, since not everyone has the use case of removing all cookies visible to the current page, that is requirement specific and should be explicit in the application code.

**Comment by FagnerMartinsBrack** [comment]
I will close for now and consider it as a duplicate, but we can reopen this if you have any new information that might change what we know.
