### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Hollyw00d** [js-cookie/js-cookie#137]
I didn't see place to give you a thank you so I'm leaving it here. I'm using this for a WordPress site right now and it's working well. You can close this comment as soon as you see it.

Good job!

**Comment by FagnerMartinsBrack** [comment]
Glad to see this was useful!

If there is any server side incompatibilities you encounter, let us know because there are a lot of servers missing in the [SERVER_SIDE.md](https://github.com/js-cookie/js-cookie/blob/3f2b5e6884407c54b391483f39ddcd4c70f9243c/SERVER_SIDE.md) file! The best thing you can do to thanks us is helping in making the life of other devs easier ;)
