### ISSUE TITLE
Value of 'expires' interpreted as seconds

### ISSUE THREAD

**Issue by esBeee** [js-cookie/js-cookie#140]
> Create a cookie that expires 7 days from now, valid across the entire site:

> > Cookies.set('name', 'value', { expires: 7 });

My observations suggest, that passing a value of _7_ to the key _expires_ means that the cookie is invalid after 7 seconds. Is that possible or am I doing something wrong?

**Comment by FagnerMartinsBrack** [comment]
We have tests that ensure the number passed to the `expires` attribute will be treated as days from the moment of the cookie creation. Can you please provide an example where that doesn't happen? You can check the return of the `get*` API to see how the cookie is being created in the browser.

**Comment by Cam** [comment]
I'm seeing the same thing. I can't find any clues as to why it happening as yet.

**Comment by Cam** [comment]
After further testing I can confirm that this is happening in Safari, Firefox and Chrome.

**Comment by FagnerMartinsBrack** [comment]
As mentioned before, It is necessary a simplified working snippet that shows the problem, I can't debug the whole website. Please post something in http://jsfiddle.net or http://jsbin.com so that I can take a look?

**Comment by Cam** [comment]
Sorry. Can't isolate the issue. But I can confirm it is real and happening on more than one site. I am getting around it by adding *88400 for now.

**Comment by FagnerMartinsBrack** [comment]
I have just run `document.cookie = 'name=value; Expires: Sat, 05 Mar 2016 09:20:50 GMT; Path: /'` in Safari developer console (Version 9.0.1 (11601.2.7.2) on a Mac). This is the same data that is written by js-cookie. After waiting for a few seconds and running `document.cookie` I got the cookie, it did not disappear.

Unfortunately we can't do anything, neither create a bug report in the browser because we don't have a simplified example that shows the problem.

**Comment by Cam** [comment]
I tried to create an example, but I couldn't reproduce it in a clean simplified environment. For the record, the issue seems to affect all browsers. If you want to see it in action, take a look at this site https://www.winstontime.com 

You can see in the JS that I fixed it for them by making the following adjustment:

` Cookies.set('_subscribe_popup_shown', true, { expires: 14*88400}); `

**Comment by FagnerMartinsBrack** [comment]
Thanks @Cam, but again, it is pretty hard for us lib maintainers to debug every site that has a problem that can or cannot be related to the library. We depend on the devs to provide a clear example that show a problem in order to fix this =(.

One interesting technique to track down a bug like this is to provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/). This technique can be used even in the worst codebases (with some effort, of course).

By the way, probably unrelated, but I just want to point out that you are using an undocumented API:

```javascript
Cookies.set( String, Boolean );
```

We have no docs for passing a boolean in the value, just Object Literal.

**Comment by Cam** [comment]
@FagnerMartinsBrack Oh, I know. I wish I could give you more info. If and when I can, I will.]

As I said, I wasn't able to reproduce it in an SSCCE. I gave the example above in case you were feeling tenacious and wanted to trouble shoot.

Thanks re boolean point! I hadn't realised.

**Comment by FagnerMartinsBrack** [comment]
Ok @Cam thank you! If by any chance you happen to have a better example (or anybody else for that matter) then please ping me out and I will be glad to document it if it is a browser issue! :)

**Comment by Cam** [comment]
Will do :)

**Comment by Anima-t3d** [comment]
I had the same issue, but using the latest version solved it for me.

This was the minified code I was using (and it took expiry as seconds):
```javascript
(function(d,f){"use strict";var h=function(d){if("object"!==typeof d.document)throw Error("Cookies.js requires a `window` with a `document` object");var b=function(a,e,c){return 1===arguments.length?b.get(a):b.set(a,e,c)};b._document=d.document;b._cacheKeyPrefix="cookey.";b._maxExpireDate=new Date("Fri, 31 Dec 9999 23:59:59 UTC");b.defaults={path:"/",secure:!1};b.get=function(a){b._cachedDocumentCookie!==b._document.cookie&&b._renewCache();a=b._cache[b._cacheKeyPrefix+a];return a===f?f:decodeURIComponent(a)};
  b.set=function(a,e,c){c=b._getExtendedOptions(c);c.expires=b._getExpiresDate(e===f?-1:c.expires);b._document.cookie=b._generateCookieString(a,e,c);return b};b.expire=function(a,e){return b.set(a,f,e)};b._getExtendedOptions=function(a){return{path:a&&a.path||b.defaults.path,domain:a&&a.domain||b.defaults.domain,expires:a&&a.expires||b.defaults.expires,secure:a&&a.secure!==f?a.secure:b.defaults.secure}};b._isValidDate=function(a){return"[object Date]"===Object.prototype.toString.call(a)&&!isNaN(a.getTime())};
  b._getExpiresDate=function(a,e){e=e||new Date;"number"===typeof a?a=Infinity===a?b._maxExpireDate:new Date(e.getTime()+1E3*a):"string"===typeof a&&(a=new Date(a));if(a&&!b._isValidDate(a))throw Error("`expires` parameter cannot be converted to a valid Date instance");return a};b._generateCookieString=function(a,b,c){a=a.replace(/[^#$&+\^`|]/g,encodeURIComponent);a=a.replace(/\(/g,"%28").replace(/\)/g,"%29");b=(b+"").replace(/[^!#$&-+\--:<-\[\]-~]/g,encodeURIComponent);c=c||{};a=a+"="+b+(c.path?";path="+
    c.path:"");a+=c.domain?";domain="+c.domain:"";a+=c.expires?";expires="+c.expires.toUTCString():"";return a+=c.secure?";secure":""};b._getCacheFromString=function(a){var e={};a=a?a.split("; "):[];for(var c=0;c<a.length;c++){var d=b._getKeyValuePairFromCookieString(a[c]);e[b._cacheKeyPrefix+d.key]===f&&(e[b._cacheKeyPrefix+d.key]=d.value)}return e};b._getKeyValuePairFromCookieString=function(a){var b=a.indexOf("="),b=0>b?a.length:b,c=a.substr(0,b),d;try{d=decodeURIComponent(c)}catch(k){console&&"function"===
  typeof console.error&&console.error('Could not decode cookie with key "'+c+'"',k)}return{key:d,value:a.substr(b+1)}};b._renewCache=function(){b._cache=b._getCacheFromString(b._document.cookie);b._cachedDocumentCookie=b._document.cookie};b._areEnabled=function(){var a="1"===b.set("cookies.js",1).get("cookies.js");b.expire("cookies.js");return a};b.enabled=b._areEnabled();return b},g=d&&"object"===typeof d.document?h(d):h;"function"===typeof define&&define.amd?define(function(){return g}):"object"===
typeof exports?("object"===typeof module&&"object"===typeof module.exports&&(exports=module.exports=g),exports.Cookies=g):d.Cookies=g})("undefined"===typeof window?this:window);
```
So quite likely it's either old code or someone else modified it and that's why @FagnerMartinsBrack couldn't reproduce it with code from this repo?

**Comment by FagnerMartinsBrack** [comment]
@Anima-t3d This is probably using the code from [this library](https://github.com/ScottHamper/Cookies/tree/3599072d16983d5d324d2539b23138eb279c30e0) instead. We coincidently use the same namespace `Cookies`
