### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by mirko-pagliai** [js-cookie/js-cookie#172]
Hi guys,

can you add your code to [packagist](http://packagist.org)? Many people use it and I think it would be really convenient and useful.

Thanks.

**Comment by FagnerMartinsBrack** [comment]
Hi, take a look on https://github.com/js-cookie/js-cookie/pull/41#issuecomment-120662189 and the thread itself. [This comment](https://github.com/carhartl/jquery-cookie/issues/220#issuecomment-25412945) shows a potential solution to fix this, if you need additional information feel free to ask the author of the comment.

js-cookie does not support package managers for other languages other than JavaScript, and even in JavaScript we support only bower and npm.

If you are totally blocked and need some change in js-cookie to make it work for some package manager, then let us know. But before that, create an issue in the package manager itself to see if they can find a solution in their side that doesn't make it necessary any changes in js-cookie repository. There are too many package managers, it is easier for them to adapt to the ecosystem than the ecosystem adapting to them.

**Comment by mirko-pagliai** [comment]
I apologize, I did not see that discussion.
Ok, you were clear, although Packagist is one of the pm most used in the world and I hope that in the future you change your mind.

**Comment by FagnerMartinsBrack** [comment]
@mirko-pagliai 

> I hope that in the future you change your mind

Just to be clear, I have no idea how packagist works. I can just guess it is similar as npm. This is not about popularity, we are not ignoring other package managers. js-cookie cares deeply for all types of usage in the wild.

However, if there is a way to make it work without changes in js-cookie repository (and evidence suggest there is for packagist) then that is encouraged. Otherwise, if the only way to make this work is by changing something in js-cookie repository, then tell us what that is and why that can't be done in the package manager itself.

If it is reasonable, and for any reason the package manager cannot handle it, then we might consider. Otherwise it is not worth it.

Can you please clarify what is being requested here exactly and why? Maybe there is new information that justify it?

Looking forward on your response.

**Comment by mirko-pagliai** [comment]
I perfectly understand your position.
Packagist is the site, Composer is the package manager.

I understand that you prefer npm or similars, it is normal. But yours is essentially a library and not a stand-alone software. A JS library most likely will be used also for PHP projects. Composer is widely used for developing in PHP. That's all.

But it is obvious that you could do this talk to many other languages and for many other package managers: JS goes well with everything.

You have to assess which package manager is more important than others. I think that users of PHP is among the largest and in many use jQuery and JS. But this is just my idea, I have no pretensions.

To allow you to work with Composer, you must add a file (`composer.json`), which is the PR that you linked.

Bye!

**Comment by FagnerMartinsBrack** [comment]
@mirko-pagliai Just for confirmation purposes, can you use js-cookie in composer without having to add a `composer.json` to the root of this project? Is it possible?

**Comment by mirko-pagliai** [comment]
I think I can, see [here](http://burgiblog.com/2012/03/08/depending-on-packages-without-composer-json-in-composer-php-dependency-manager/).
I've never tried this, but I think that clones your github repository within my software.

But in this way, your software will not actually packaged. This probably prevents the package from being updated when you release a new release.

However, if you want, I can try and say the outcome.

**Comment by FagnerMartinsBrack** [comment]
> However, if you want, I can try and say the outcome.

Could you? That would be amazing! :) Also, it would help a lot anyone that in the future might make the same request (I could just link to this thread to see if this fixes the issue).

**Comment by mirko-pagliai** [comment]
This **does not work** (marking the master repo):
```
"repositories": [
        {
			"type": "package",
			"package": {
				"name": "js-cookie/js-cookie",
				"version": "master",
				"source": {
					"url": "https://github.com/js-cookie/js-cookie.git",
					"type": "git",
					"reference": "master"
				}
			}
        }
    ],
```
Instead, this works (marking a specific tag):
```
"repositories": [
        {
			"type": "package",
			"package": {
				"name": "js-cookie/js-cookie",
				"version": "v2.1.0",
				"source": {
					"url": "https://github.com/js-cookie/js-cookie.git",
					"type": "git",
					"reference": "v2.1.0"
				}
			}
        }
    ],
```

problems:

1. the entire repository is cloned, while I do not need it (minor);
2. because I have to mark a specific tag, it will not be updated automatically;
3. because the entire repository was cloned t, I have only the source and not the minimized version (so it seems).

**Comment by FagnerMartinsBrack** [comment]
Thanks for checking that!

> because I have to mark a specific tag, it will not be updated automatically;

I wouldn't encourage someone to do that anyway, dependencies shouldn't be automatically updated to prevent undesired side effects (let's say you rely in an undocumented feature and a patch upgrade breaks your system but you don't know why).

> because the entire repository was cloned t, I have only the source and not the minimized version (so it seems).

Even on npm you wouldn't have the minimized version. As it is right now, the repository requires you to have node installed and run the build in the developer environment to be able to get the minified version or minify it yourself in your build routine (or use a CDN). I am changing that slowly though, see https://github.com/js-cookie/js-cookie/issues/57.

**Comment by FagnerMartinsBrack** [comment]
I guess for now one should rely on tags to be able to use js-cookie in composer. We create the tags consistently, which is a good thing for this kind of use case. Good to know compose supports git repositories out of the box!

I have one more question, why composer does not use `package.json` to get metadata from the repository? It could fallback to it if it don't find the `composer.json` file, would that be worth an issue in composer repository?

**Comment by mirko-pagliai** [comment]
@FagnerMartinsBrack 

> I wouldn't encourage someone to do that anyway, dependencies shouldn't be automatically updated to prevent undesired side effects

Ehi man, I'm not a stupid! :-) Ok, I am a small developer, but I'm not a total noob

See https://getcomposer.org/doc/articles/versions.md
I mean that.

> I have one more question, why composer does not use package.json to get metadata from the repository? It could fallback to it if it don't find the composer.json file, would that be worth an issue in composer repository?
I have no idea. I'm just a Composer's end user.

**Comment by FagnerMartinsBrack** [comment]
> Ehi man, I'm not a stupid! :-) Ok, I am a small developer, but I'm not a total noob

I never said that! A post in a project's issues have 2 targets: The OP and the later dev that will find the issue through search. This library is also used by beginners, any information is valuable. Also, since I will be also linking this thread to future reports about composer, it is on more reason to have as much information as possible.

Sticking to versions without automatic update is usually a best practice. Only need to know if that is not the case with composer. Here is the best place to document that.

**Comment by FagnerMartinsBrack** [comment]
>>  I have one more question, why composer does not use package.json to get metadata from the repository? It could fallback to it if it don't find the composer.json file, would that be worth an issue in composer repository?

> I have no idea. I'm just a Composer's end user.

But even as an end-user, would it make sense creating an issue asking if they could retrieve all necessary meta-data from `package.json` if it exists instead of requiring a `composer.json` in every repository?

NPM is the [most used package manager in the world](https://nodejs.org/static/documents/2016-survey-report.pdf), it makes sense not fighting against reality and use what is already available.

**Comment by mirko-pagliai** [comment]
> Sticking to versions without automatic update is usually a best practice. Only need to know if that is not the case with composer. Here is the best place to document that.

With Composer, you can do something like:

    "js-cookie/js-cookie": "2.1.*"

it translates this as:

    >=2.1.0.0-dev <2.2.0.0-dev

Or:

    "js-cookie/js-cookie": "~2.1"

it translates this as:

    >=2.1.0.0-dev <3.0.0.0-dev

> But even as an end-user, would it make sense creating an issue asking if they could retrieve all necessary meta-data from package.json if it exists instead of requiring a composer.json in every repository?

Ok, maybe it's useless. 
But we should say it to Composer's developers.

For now I will use the tag or I will assess whether even use npm, no problem ;-)

**Comment by FagnerMartinsBrack** [comment]
Ok @mirko-pagliai, thanks for the help! I will be linking this in the future!

**Comment by FagnerMartinsBrack** [comment]
For anyone interested in the future, I noticed @mirko-pagliai recently added js-cookie to packagist: https://packagist.org/packages/js-cookie/

**Comment by mirko-pagliai** [comment]
I had to do this because:
1) I can not use npm;
2) the "repository" way did not work, because in my case the package was marked as a dependency of a dependency, that Composer can not handle.

I'll try to keep updated repository, perhaps creating tags.

**Comment by FagnerMartinsBrack** [comment]
> I'll try to keep updated repository

That would be very helpful, it is one less thing for us to worry about and it leverages community effort to make it work for everyone. Thanks man!

**Comment by drAlberT** [comment]
Having to maintain a fork only to add a composer.json file ...   @FagnerMartinsBrack I think it is a waste of time and human resources ... 

You really **should** merge it .. IMHO of course

**Comment by mirko-pagliai** [comment]
I have the same opinion. In the end... it's just a file.
But we have already talked about this.

**Comment by mirko-pagliai** [comment]
See PR https://github.com/js-cookie/js-cookie/pull/41

**Comment by FagnerMartinsBrack** [comment]
Yes, we have discussed about this and I will reiterate. What if someone wants to use [jspm](https://github.com/carhartl/jquery-cookie/pull/244), [nuget](https://www.nuget.org/packages/js-cookie), [component](https://github.com/componentjs/component) or another package manager? Or some special code for [volo](volo)? The project will be cluttered with json files or code that have to be maintained and things are gonna break and nobody will care, just like what happened before: https://github.com/carhartl/jquery-cookie/pull/262#issuecomment-86754471

@drAlberT 
> @FagnerMartinsBrack I think it is a waste of time and human resources ...

It is a waste of human resources from the maintainers of this project to support a custom package manager that will only be used by some people. The most popular [jquery.cookie package on packagist](https://packagist.org/packages/components/jquery-cookie) is there since 2014 and have done 23.610 installs, that is ~490 install per week for a project that exist for more than 7 years. The js-cookie repository was created ~1 year ago and doesn't have the same level of popularity yet.

If the package `js-cookie` receives a considerable amount of downloads in a given package manager, we might consider adding here. Until then, I count on the community to support a custom package manager for js-cookie to spare myself from having to support a specific use case.

I hope everyone understand and I am thankful for the help, thanks.

**Comment by drAlberT** [comment]
Maybe [RobLoach/component-installer](https://github.com/RobLoach/component-installer) could be the Columbus egg?

**Comment by xaos01** [comment]
Since your js-cookie has no dependencies you have likely spent more time talking about, thinking about, and responding in this thread than it would to add the composer.json file for the entire lifespan of the project.

**Comment by FagnerMartinsBrack** [comment]
@xaos01 The answer to a thread is done once, support for a package manager is forever. They are on huge different scales. [Code that does exist is the code you don't need to worry about](https://out.reddit.com/t3_5p3twj?url=https%3A%2F%2Fmedium.com%2F%40fagnerbrack%2Fcode-that-dont-exist-is-the-code-you-don-t-need-to-debug-88985ed9604&token=AQAA9WuvWDnAIcrmhrUld0OQ_KQbDmhv9lKUNMjbRndvdL3eM3D1&app_name=mweb2x).

Bring a solution to add Packagist support without having to worry about updating the file. I believe that is the better action to force this thread to be reopened.
