### ISSUE TITLE
Cookies don't work since upgrading to v2.1.1

### ISSUE THREAD

**Issue by Kirkis** [js-cookie/js-cookie#188]
Hi,

I am sorry to say I didn't take the time to investigate, but I wanted to see if you were aware of this or if I was perhaps mis-using the library.
After upgrading from v2.1.0 to v2.1.1, I noticed cookies weren't read by our usual JS code.
After switching back to v2.1.0, everything went back to normal.
I am unsure whether this is relevant, but we use yuicompressor v2.4.8 on the unminified release.

Here is how we write cookies (where the "cookie" variable is a JSON object):
```
Cookies.set(this.name, window.btoa(JSON.stringify(cookie)), params)
```
And they are read this way:
```
JSON.parse(window.atob(Cookies.get(this.name)))
```

I am guessing something changed in the way cookies are read from storage in this release?

**Comment by FagnerMartinsBrack** [comment]
@Kirkis 

Your code seems fine, it could be breaking somewhere else. Here are some resources to look at:

* Changelog: https://github.com/js-cookie/js-cookie/releases/tag/v2.1.1 (no breaking changes for documented API)
* Here are the relevant commits between the versions: https://github.com/js-cookie/js-cookie/compare/v2.1.0...v2.1.1. Try to rollback each piece of the code from `js.cookie.js` file until you find the code that is breaking your app.
* If that doesn't work, try to use the [SSCCE](http://sscce.org/) pattern to reduce the problem, maybe you will find the root cause and if you do please post it here so that we can assess if it is a common mistake we can document in the changelog.

This is a non breaking release, the only way for it to fail is if your application is somehow relying in some bug or internal (undocumented) behavior of js-cookie.

**Comment by FagnerMartinsBrack** [comment]
Here is a fiddle that proves the version 2.1.1 is working: https://jsfiddle.net/md2w2n3k/1/

**Comment by FagnerMartinsBrack** [comment]
It is more likely that somewhere the api is being used as `Cookies.get(String, Object Literal)`, instead of just `Cookies.get(String)`. If it does, then it is wrong usage because there is no such API like that. See https://github.com/js-cookie/js-cookie/pull/168.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by Kirkis** [comment]
Hi,
Sorry for the delay.
When using v2.1.1 but I revert only the following code (v2.1.1):
```
		api.set = api;
		api.get = function (key) {
			return api(key);
		};
```
to the following (v2.1.0):
```
		api.get = api.set = api;
```
Then my app works as expected (Firefox Developer Edition).

**Comment by FagnerMartinsBrack** [comment]
@Kirkis 

That means the API is being used incorrectly. Some part of your code is written as `Cookies.get(String, Object)` which created a cookie incorrectly and some code is depending on that behavior, that is probably why it breaks.

Find the code that is calling `Cookies.get(String, Object)` with 2 arguments and you will find the bug. Just replace the code with `Cookies.set(String, Object)`.

**Comment by Kirkis** [comment]
Thanks, that works
