### ISSUE TITLE
False advertising?

### ISSUE THREAD

**Issue by harrync** [js-cookie/js-cookie#189]
'Very good wiki' - there are 3 pages, i.e. not very good. Might want to remove this sentence?

**Comment by FagnerMartinsBrack** [comment]
> ... there are 3 pages

That is the reason why the wiki is very good, because there is only information that was proven to be essential. Different from other wikis, where people are bombarded with useless information, js-cookie wiki is based on [empirical evidence of useful content or frequently asked questions](https://github.com/js-cookie/js-cookie/issues/37) that will serve the majority of the library users.

Saying that a wiki is not good because it has a few pages is a falacy, because the argument is against the amount of information, not against the quality or usefulness of the content. A wiki can also have a lot of content and be useless or have a low amount of content and be useful.

That is what "very good" is all about in this context. Quality, not quantity. Therefore there is no "false advertising" here.

> Might want to remove this sentence?

I will be glad to do it if you provide some concrete evidence of why the wiki is not very good with arguments against the content, not against the amount of information there is.

Thanks for the feedback.

**Comment by FagnerMartinsBrack** [comment]
@harrync, what about: "Useful Wiki"?

**Comment by shackra** [comment]
I was expecting something alone the lines @harrync so I agree to change the wording to "Useful Wiki" or "Wiki with just the useful information".
