### ISSUE TITLE
Automatic JSON decoding

### ISSUE THREAD

**Issue by CupOfTea696** [js-cookie/js-cookie#190]
Could support for automatic JSON decoding be added? It could be done by adding a JSON map cookie that contains all cookies that were encoded to JSON. It should make sure to remove items from the JSON map if the value has changed (e.g. if you set it again but to a string)

**Comment by FagnerMartinsBrack** [comment]
Hi, we have support for JSON, just use `Cookies.getJSON(String)`. See [here](https://github.com/js-cookie/js-cookie/tree/v2.1.1#json).

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af).

**Comment by CupOfTea696** [comment]
@FagnerMartinsBrack Yes, but I mean that the normal .get would automatically decode JSON if the original cookie was set as JSON. 

Simple example to illustrate:
```js
Cookies.set('name', {prop: 'value'});

var name = Cookies.get('name');
name.prop === 'value'; // true
```

Behind the scenes, two cookies would be set: the cookie `name` and the cookie `__json_map`. The value of the JSON map cookie would be `"['name']"`. When `Cookies.get` is called, the library would get the JSON map (and store it internally so we don't need to get it again as long as the page doesn't reload) and JSON parse it. Then it would check if the value `name` is in the JSON map array. If it is, it will retrieve the requested cookie and JSON parse it. If not, it will simply retrieve the cookie. 

There's a few other ways this could be approached (e.g. prefixing the cookie value with an identifier string that indicates the cookie is JSON stringified) but this seems to me the best solution since a back-end could still retrieve the cookie without having to know how the front-end cookie library works.

**Comment by FagnerMartinsBrack** [comment]
> var name = Cookies.get('name');
> name.prop === 'value'; // true

The return type of a function should be consistent, otherwise it will violate the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) because the developer will have to treat types differently given specific conditions, that it why `getJSON()` was created in the first place, so that it doesn't mix JSON and String types in the same function.

There is no benefit in doing that.

>  ... two cookies would be set: the cookie name and the cookie __json_map.

This can cause problems. We already have issues with cookie [reaching the limit size](https://github.com/js-cookie/js-cookie/issues/37#issuecomment-217620753), creating a new cookie would be increase unnecessarily the size that is transferred through the network on each request. Remember, cookies are not gzipped, so all the bytes are transferred on each request, which is very bad.

Also, this library was since the beginning just a wrapper for `document.cookie`, that is why it is a "A **simple**, **lightweight** JavaScript API". If we start adding more stuff into it, it will turn into bloat. This is probably out of scope of the project.

We encourage creating APIs on top of js-cookie for different use cases, because it is not everyone that will want such feature, but everyone will download the bloat.

**Comment by CupOfTea696** [comment]
Good points 😄
