### ISSUE TITLE
Malformed URI

### ISSUE THREAD

**Issue by hinst** [js-cookie/js-cookie#196]
If there are other cookies that cause malformed-URI error then my cookies dont work because it crashes inside of get()

	Cookies.set('meow', 'value');
	console.log(Cookies.get('meow')); // exception

Here is what happens: I run a crappy web app on my PC. It stores perhaps-malformed cookies on localhost domain. Later I run my app. My code crashes when I call Cookies.get(). If I clear all cookies then the example code I posted above runs OK

**Comment by FagnerMartinsBrack** [comment]
@hinst Can you please post a [code sample](http://sscce.org/) that reproduces the error?

We had this problem before but it was fixed, see https://github.com/js-cookie/js-cookie/pull/62 and https://github.com/js-cookie/js-cookie/issues/55#issuecomment-116850929.

**Comment by hinst** [comment]
https://jsfiddle.net/hinst/rcgrLq98/3/

**Comment by FagnerMartinsBrack** [comment]
X-Ref: http://stackoverflow.com/questions/37124706/js-cookie-library-does-not-work

This probably happens due to the fact the [decoding of the keys](https://github.com/js-cookie/js-cookie/blob/f2b25713e8fae658d418b60710adc0e0d14998d9/src/js.cookie.js#L68-L70) of the cookie does not run inside the `try/catch` above.

I will take a look this week at some point. In the meantime feel free to create a [Pull Request](https://github.com/js-cookie/js-cookie/blob/f2b25713e8fae658d418b60710adc0e0d14998d9/CONTRIBUTING.md#pull-requests).

**Comment by FagnerMartinsBrack** [comment]
X-Ref: #62.

**Comment by FagnerMartinsBrack** [comment]
@hinst Pull Request opened, see #198.

Just to give a little bit of context on this for whoever reads it in the future:

[As documented](https://github.com/js-cookie/js-cookie/tree/v2.1.1#encoding):

> ... The only character in cookie-name or cookie-value that is allowed and still encoded is the percent % character, it is escaped in order to interpret percent input as literal ...

Because the % character is escaped to treat the input as literal, it fails if the sequence following the "percent" is not a valid percent-encoding sequence encoded as UTF-8, which is the case for `%BS` (`decodeURIComponent('%BS')`).

The bug in this case is that when it fails, it breaks the whole app, and that should not happen. That is why I cross-referenced to #62 above, in that case we had the same problem, but related to the cookie **value** (which is more likely to cause trouble than the **name**). In this case, it is not common to use complex characters outside the `[a-zA-Z]` range in the cookie name, that is why this problem was not spotted until now.

The solution to fix this bug is not making the app break due to existing complex characters in the cookie name, but rather ignore retrieving it.

There is no API to disable the character encoding from the cookie **name** and treat it as raw. There is only for the cookie **value**. If one feel the need to handle cookie names using the converter API, create a separate issue to discuss a feature request with real use cases that justify the inclusion of such API.

**Comment by hinst** [comment]
is it fixed now?

**Comment by FagnerMartinsBrack** [comment]
@hinst Test [this file](https://github.com/js-cookie/js-cookie/blob/754a942bb9761b6ec8e28723db979ec040e2cfca/src/js.cookie.js). Does it work?

I will release a version 2.1.2 this weekend.
