### ISSUE TITLE
WebPack / Require usage

### ISSUE THREAD

**Issue by flowdee** [js-cookie/js-cookie#201]
Installed js-cookie via npm, required it inside my asset with `require('js-cookie');` but always getting a `ReferenceError: Cookies is not defined` error when using Cookies.

Am I missing something? I'm using a webpack workflow for my project.

**Comment by FagnerMartinsBrack** [comment]
I never used webpack, so I need a simple failing example that is reproducible and shows a problem with js-cookie that doesn't happen with other similar library.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by isharov** [comment]
var Cookies = require('js-cookie');

**Comment by FagnerMartinsBrack** [comment]
@isharov it might have been fixed after https://github.com/js-cookie/js-cookie/issues/244, but the only person that can confirm is [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) =/

@flowdee, can you confirm if it's working now after https://github.com/js-cookie/js-cookie/issues/244?

**Comment by flowdee** [comment]
to be honest I looked for another solution (my post is almost 6 months ago) but with the next project going to give it a second chance 😄

**Comment by FagnerMartinsBrack** [comment]
Ok, if reporting some problem in the future, please provide a [small reproducible example](http://sscce.org) that shows a problem in the library, that will help us to guide efforts 👍

**Comment by Gotterbild** [comment]
Having the same issue.

I'm working on Vue project, started from [this template](https://github.com/vuejs-templates/webpack).
My build options are:
<pre>
? Project name myProject
? Project description My new project
? Author Me <me@mail.ru>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No
</pre>

1. Added `js-cookie` to `package.json` https://s.mail.ru/7Pa8/VEUArMezp
2. `npm install`
3. Added `require` to `main.js` https://s.mail.ru/MVrc/9KUPBiBiq
4. Try to use in `Home.vue`: https://s.mail.ru/KDjH/R1CGb33MX
5. But get `not defined`: https://s.mail.ru/N5JA/vhrRNTB5N

**Comment by FagnerMartinsBrack** [comment]
@Gotterbild see https://github.com/js-cookie/js-cookie/issues/201#issuecomment-256810332

**Comment by Gotterbild** [comment]
@FagnerMartinsBrack As I understand, the problem is somehow related with Webpack and its building mechanisms and other libraries (or frameworks) it is used with. So, I provided best example I could where error is reproducable. It is literaly 5 minutes to git clone, build and start debugging.

**Comment by FagnerMartinsBrack** [comment]
@Gotterbild Feel free to make your case and create a PR. We're very keen to land fixes to the library.

However, we don't have time to debug lots of dependencies, feel free to ask the question on StackOverflow.

The only thing this library does is to create an adapter for the browser cookie mechanism. If there's a problem that needs to be reproduced with a lot of dependencies, then it's probably a problem with the integration between those dependencies than a problem with js-cookie itself.

Once you find a problem with the library, feel free to create an issue or PR so that we can talk about it.

**Comment by Soullivaneuh** [comment]
I'm having the same issue with WebPack. @Gotterbild did you found anything?

**Comment by Gotterbild** [comment]
@Soullivaneuh We switched from cookies to Storage for our project. [MemoryStorage ](https://www.npmjs.com/package/memory-storage) if browser supports that and localStorage if doesn't.

**Comment by ddlaat** [comment]
Add this to your webpack.config:

```
plugins: [
        new webpack.ProvidePlugin({ Cookies: 'js-cookie/src/js.cookie.js' }),
    ]
```
It makes js-cookie.js globally available as 'Cookies' for other libraries.

**Comment by oshihirii** [comment]
I'm just trying to use `js-cookie` in chrome dev tools, but get: 

    Uncaught ReferenceError: Cookies is not defined

All of these suggestions don't work for me with `"webpack": "^5.63.0"`:
```js
{
    test: require.resolve('js-cookie'),
    loader: 'expose-loader',
    options: {
        exposes: ['Cookies'],
    },
}
```
```js
plugins: [
        new webpack.ProvidePlugin({ Cookies: 'js-cookie/dist/js.cookie.js' }),
    ]
```
and this just throws an error when building:
```js
{
    test: require.resolve('js-cookie/dist/js.cookie.js'),
    loader: 'expose-loader?Cookies'
}
```
this is how i import js-cookie into my main file:
```js
import Cookies from 'js-cookie';
```

**Comment by FagnerMartinsBrack** [comment]
Hi @oshihirii

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie. It looks like this is a problem with Webpack or another configuration layer in your environment, please see [this comment](https://github.com/js-cookie/js-cookie/issues/201#issuecomment-219291345).

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
