### ISSUE TITLE
Broken behavior after uglifying code with unsafe=true

### ISSUE THREAD

**Issue by everdimension** [js-cookie/js-cookie#206]
This might be an edge case, but I want to let this issue be known.

This library's behavior breaks after passing its code through and [uglifier](https://github.com/mishoo/UglifyJS2) plugin with an [`unsafe`](https://github.com/mishoo/UglifyJS2#compressor-options) option set to `true`.

This is what the uglifier does to the lines [72-78](https://github.com/js-cookie/js-cookie/blob/v2.1.2/src/js.cookie.js#L72-L78):
![screen shot 2016-06-03 at 16 10 16](https://cloud.githubusercontent.com/assets/5347023/15779769/fffc0f8c-29a6-11e6-8c2c-9c7b37792c8c.png)

This results in this broken behavior: 

```javascript
jsCookie.set('rnd', '43', { path: '/' });
// returns "rnd=43; path=/undefined"
```

You may argue that that's exactly what should be expected from an "unsafe" option and that this plugin is not responsible for the actions of other libs.

But still, the usage of `uglify` is very common even with the `unsafe` option on.

I'd like to offer a PR in a couple of hours which would fix the issue. You may reject it if you believe that it is not needed, but I think that making this library more robust will only be a good thing and will not harm its behavior in any way.

**Comment by everdimension** [comment]
Open PR https://github.com/js-cookie/js-cookie/pull/207 for this issue.

**Comment by FagnerMartinsBrack** [comment]
@everdimension Thanks for opening the issue.

The code was done like that originally to spare bytes when using uglify in our minification system, so that we still advertise correctly (~800 bytes gzipped). See PR https://github.com/js-cookie/js-cookie/pull/14 and related links for context.

To make sure that this is really necessary, can you please post the following information in the Pull Request?

1. The GZipped size of the file using uglify without the `unsafe` option.
2. The GZipped size of the file using uglify with the `unsafe` option and the code on your Pull Request.

If (1) have more **GZipped** bytes than (2), then we will recommend not using the `unsafe` because it will make no difference. If (1) have less **GZipped** bytes than (2), then we will consider doing something about it, maybe even run the tests on that minified version to make sure it doesn't break in the  future.

If you don't know how to see the GZipped size using our build tool and [grunt-compare-size](https://github.com/rwaldron/grunt-compare-size), please et me know that I will setup a small guide of how to run it in this project to make contributions easier.

**Comment by everdimension** [comment]
@FagnerMartinsBrack 
I've added size information to the [PR](https://github.com/js-cookie/js-cookie/pull/207).

> then we will recommend not using the unsafe because it will make no difference

I think such recommendation isn't the best idea because even if this `unsafe` option would not add significant gains to this particular library, it might be more than noticeable for other projects. And options for compressing code are usually set for the whole project bundle, not per file.

**Comment by megamk** [comment]
I have the same issue using webpack and UglifyJsPlugin. Took me 2 hours to figure out why Cookies are not set/removed in production (where code is being minified) and everything is fine in local env (where code is not minified).
