### ISSUE TITLE
Front end in a JSON, the back-end using JAVA is unavailable

### ISSUE THREAD

**Issue by luwei369** [js-cookie/js-cookie#217]
Cookies.set('name', { foo: 'bar' });
It is used in JAVA HttpServletRequest.getCookies();Unable to get to the value;If it is a simple string can, such as:
Cookies.set('name', 'aa');

**Comment by luwei369** [comment]
The same code using  jquery.cookie.js  is normal

**Comment by alongchengtian0** [comment]
1.request.getCookies() can't get the json style value.
2.All cookies has been sended to the brwoser.Then you can use request.getHeader("Cookie"),you can get all of it.Just need to resovle it.

**Comment by FagnerMartinsBrack** [comment]
Be aware that js-cookie works out of the box with cookies created by js-cookie and read by js-cookie, we implement by default the encoding of all characters that are not allowed according to [RFC 6265](https://tools.ietf.org/html/rfc6265). In order to make it  work in server-side application that do not follow the spec, you need to use [custom converters](https://github.com/js-cookie/js-cookie/tree/v2.1.2#converters) and come up with a custom encoding/decoding mechanism.

Which server are you guys using? Have you taken a look here: https://github.com/js-cookie/js-cookie/blob/3d47ad878256bf6457a88ebc72738558e8eaa07f/SERVER_SIDE.md

You can also try the [Java Cookie](github.com/js-cookie/java-cookie) project if you are using Java servlets.

**Comment by luwei369** [comment]
@alongchengtian0    
Thank you very much for your answer, use request.getHeader("Cookie") can indeed normal to the data.But I wonder why a simple can, can't JSON, found out the problem.Using the JSON data, sending data did more to escape {}.

**Comment by luwei369** [comment]
@FagnerMartinsBrack   Thank you very much for your answer。
I found that after using the JSON data, the browser sends the data is not to escape {}.Look at the code, found that:
`value = encodeURIComponent(String(value))  //Here will be to escape character
	.replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g, decodeURIComponent);   //But there is {} to escape again, why?`
I put it into a value = encodeURIComponent(String(value)) don't know what happens?

**Comment by luwei369** [comment]
%7B  Should not be restored    ???

**Comment by FagnerMartinsBrack** [comment]
According to [RFC 6265](https://tools.ietf.org/html/rfc6265) the `{` and `}` characters are allowed in the cookie value, therefore they are not [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) by js-cookie so they are not encoded by the browser.

In order to make it work you need to use [converters](https://github.com/js-cookie/js-cookie/tree/3d47ad878256bf6457a88ebc72738558e8eaa07f#converters), as stated above:

```javascript
var MyCookieForJava = Cookies.withConverter({
  read: function(value, name) {
    // Decode the cookie value into "decodedValue"
    decodedValue = decodedValue.replace(/%7B/g, '{')
    return decodedValue;
  }
});

// Then you use like this:
MyCookieForJava.set('name',  { foo: 'bar' });
MyCookieForJava.get('name');
```

**Comment by FagnerMartinsBrack** [comment]
@luwei369 did converters solved your issue?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by luwei369** [comment]
Thank you very much for answer my question.I finally did not use a converter, but blocked the code part of logic (62), as follows:
.replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g, decodeURIComponent);
The current work.
