### ISSUE TITLE
cookies.remove is not a function

### ISSUE THREAD

**Issue by beckend** [js-cookie/js-cookie#220]
I'm using webpack, .get, .set works just fine, remove function does not exist.

**Comment by FagnerMartinsBrack** [comment]
That's not enough information, please provide a reproducible example that I can run.

**Comment by beckend** [comment]
You can clone
```
https://bitbucket.org/linken/cookies-remove-fail
```
I'm sorry about the install time but i just cleaned out a working project.

**Comment by FagnerMartinsBrack** [comment]
@beckend Sorry, but that might take some time to debug and I am pretty busy =(. I was looking for a small reproducible example that we can see the problem straight away, see this link for how to do it: http://sscce.org.

If you want support to reduce the problem to the root cause, the best alternative would be posting it as a question in StackOverflow, under the tag js-cookie, see here: http://stackoverflow.com/questions/tagged/js-cookie

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.
