### ISSUE TITLE
How to use js-cookie with requirejs?

### ISSUE THREAD

**Issue by FlyingOE** [js-cookie/js-cookie#234]
With jquery-cookie previously, it was trivial to load the library via requirejs AMD-style declaration.

With js-cookie now, however, the same declaration doesn't seem to work -- neither window.Cookies or $.cookie is available.

Has requirejs support been dropped from js-cookie?

**Comment by FagnerMartinsBrack** [comment]
No, AMD and UMD support is there. Can you please create a [simplified example](http://sscce.org) that shows the problem? Thanks.

**Comment by Kirinya** [comment]
@FlyingOE 
An example of what works (provided you have set up your initrequire.js to work with js-cookie):

define(['js-cookie'],
function (cookie) {
	cookie.set('someCookieName');
}

So, because the jquery dependency was dropped and js-cookie no longer is a jquery-Plugin, it is no longer available under the jquery namespace ($), but you have to define your own namespace and can call it with this one.

**Comment by FagnerMartinsBrack** [comment]
Thanks @Kirinya.

Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the members.

**Comment by juliovedovatto** [comment]
I need to load the js-cookie code inside of a snippet (I dont have access on production enviroment to host the file, neither the requirejs configuration), requirejs is already loaded. 

So, the "simplified CommonJS Wrapper" (is that it, right?) does not work for me, because I'm not using requirejs to load the plugin.

What I did:

```javascript
;(function(){
    var original_define;
    // verificar se requirejs foi carregado e atribuir "esconder" ele do plugin abaixo
    if (define && typeof define==="function") {
        original_define = define;
        define = false;
    }

    // minified js-cookie code  goes here

   if (original_define) {
        define = original_define;
        original_define = undefined;
    }
    // [...] 
   Cookies.set('something', 'value', { expires: 1, path: '/' }); // I can acccess the Cookies global object now
    // [...] 
})();
```
Is it the only way to avoid this problem? I found this solution a little "ugly", with you know what I mean 😏

**Comment by FagnerMartinsBrack** [comment]
> I need to load the js-cookie code inside of a snippet

What if you don't just use the global `Cookies` namespace? Do you have a [SSCCE](http://sscce.org) that shows the problem?

**Comment by juliovedovatto** [comment]
@FagnerMartinsBrack unfortunately, I had to do in this way in order to use ```Cookies``` namespace. The first thing that js-cookie code looks is ```requirejs``` is loaded with ```amd```, if is true, then he loads via simplified CommonJS Wrapper. The code thinks I loaded it via require js configuration (at last I think).

```javascript
// js-cookie source code

/*!
 * JavaScript Cookie v2.1.2
 * https://github.com/js-cookie/js-cookie
 *
 * Copyright 2006, 2015 Klaus Hartl & Fagner Brack
 * Released under the MIT license
 */
;(function (factory) {
	if (typeof define === 'function' && define.amd) { // checks if requirejs is defined and have amd support
		define(factory);
	} else if (typeof exports === 'object') {
		module.exports = factory();
	} else {
		var OldCookies = window.Cookies;
		var api = window.Cookies = factory();
		api.noConflict = function () {
			window.Cookies = OldCookies;
			return api;
		};
	}
// [...]
```

Here is a snippet:

```javascript
// assuming requirejs is already loaded and the snippet bellow is injected througth third party script)
;(function(){
 
     /*!
      * JavaScript Cookie v2.1.2
      * https://github.com/js-cookie/js-cookie
      *
      * Copyright 2006, 2015 Klaus Hartl & Fagner Brack
      * Released under the MIT license
      */
    (function(b){if(typeof define==="function"&&define.amd){define(b)}else{if(typeof exports==="object"){module.exports=b()}else{var a=window.Cookies;var c=window.Cookies=b();c.noConflict=function(){window.Cookies=a;return c}}}}(function(){function b(){var f=0;var c={};for(;f<arguments.length;f++){var d=arguments[f];for(var e in d){c[e]=d[e]}}return c}function a(d){function c(o,n,k){var r;if(typeof document==="undefined"){return}if(arguments.length>1){k=b({path:"/"},c.defaults,k);if(typeof k.expires==="number"){var h=new Date();h.setMilliseconds(h.getMilliseconds()+k.expires*86400000);k.expires=h}try{r=JSON.stringify(n);if(/^[\{\[]/.test(r)){n=r}}catch(m){}if(!d.write){n=encodeURIComponent(String(n)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent)}else{n=d.write(n,o)}o=encodeURIComponent(String(o));o=o.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);o=o.replace(/[\(\)]/g,escape);return(document.cookie=[o,"=",n,k.expires&&"; expires="+k.expires.toUTCString(),k.path&&"; path="+k.path,k.domain&&"; domain="+k.domain,k.secure?"; secure":""].join(""))}if(!o){r={}}var q=document.cookie?document.cookie.split("; "):[];var p=/(%[0-9A-Z]{2})+/g;var l=0;for(;l<q.length;l++){var j=q[l].split("=");var g=j.slice(1).join("=");if(g.charAt(0)==='"'){g=g.slice(1,-1)}try{var f=j[0].replace(p,decodeURIComponent);g=d.read?d.read(g,f):d(g,f)||g.replace(p,decodeURIComponent);if(this.json){try{g=JSON.parse(g)}catch(m){}}if(o===f){r=g;break}if(!o){r[f]=g}}catch(m){}}return r}c.set=c;c.get=function(e){return c(e)};c.getJSON=function(){return c.apply({json:true},[].slice.call(arguments))};c.defaults={};c.remove=function(f,e){c(f,"",b(e,{expires:-1}))};c.withConverter=a;return c}return a(function(){})}));

var test = Cookies.get('foo'); 
console.debug(test);
})();
```

The snippet above throws exception: ```Uncaught ReferenceError: Cookies is not defined```

Workaround:

```javascript
;(function(){
    var original_define;
    
    if (('define' in window) && define && typeof define==="function") {
        original_define = define;
        define = false;
    }

     /*!
      * JavaScript Cookie v2.1.2
      * https://github.com/js-cookie/js-cookie
      *
      * Copyright 2006, 2015 Klaus Hartl & Fagner Brack
      * Released under the MIT license
      */
    (function(b){if(typeof define==="function"&&define.amd){define(b)}else{if(typeof exports==="object"){module.exports=b()}else{var a=window.Cookies;var c=window.Cookies=b();c.noConflict=function(){window.Cookies=a;return c}}}}(function(){function b(){var f=0;var c={};for(;f<arguments.length;f++){var d=arguments[f];for(var e in d){c[e]=d[e]}}return c}function a(d){function c(o,n,k){var r;if(typeof document==="undefined"){return}if(arguments.length>1){k=b({path:"/"},c.defaults,k);if(typeof k.expires==="number"){var h=new Date();h.setMilliseconds(h.getMilliseconds()+k.expires*86400000);k.expires=h}try{r=JSON.stringify(n);if(/^[\{\[]/.test(r)){n=r}}catch(m){}if(!d.write){n=encodeURIComponent(String(n)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent)}else{n=d.write(n,o)}o=encodeURIComponent(String(o));o=o.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);o=o.replace(/[\(\)]/g,escape);return(document.cookie=[o,"=",n,k.expires&&"; expires="+k.expires.toUTCString(),k.path&&"; path="+k.path,k.domain&&"; domain="+k.domain,k.secure?"; secure":""].join(""))}if(!o){r={}}var q=document.cookie?document.cookie.split("; "):[];var p=/(%[0-9A-Z]{2})+/g;var l=0;for(;l<q.length;l++){var j=q[l].split("=");var g=j.slice(1).join("=");if(g.charAt(0)==='"'){g=g.slice(1,-1)}try{var f=j[0].replace(p,decodeURIComponent);g=d.read?d.read(g,f):d(g,f)||g.replace(p,decodeURIComponent);if(this.json){try{g=JSON.parse(g)}catch(m){}}if(o===f){r=g;break}if(!o){r[f]=g}}catch(m){}}return r}c.set=c;c.get=function(e){return c(e)};c.getJSON=function(){return c.apply({json:true},[].slice.call(arguments))};c.defaults={};c.remove=function(f,e){c(f,"",b(e,{expires:-1}))};c.withConverter=a;return c}return a(function(){})}));

    if (original_define) {
        define = original_define;
        original_define = undefined;
    }

var test = Cookies.get('foo');

console.log(test); // undefined

})()
```

Does it make sense? I tried my best to explain and provide valid example.

**Comment by FagnerMartinsBrack** [comment]
I still don't get the problem. If the environment is using requireJS, then it should be loaded using `require('js-cookie')`, not using the `Cookies` namespace. What do you propose to do?

Can you please create a new issue and build a failing example in an online tool that we can execute it? See https://jsfiddle.net/

I also suggest creating a question in StackOverflow under the tag `js-cookie` and `amd` because it seems to be something specific to your environment. I really need a simple executable example that shows the problem, it is very hard to guess what is the intended behavior here.

**Comment by juliovedovatto** [comment]
@FagnerMartinsBrack I cannot access the ```requirejs``` configuration to load js-cookie. I can only load ```js-cookie``` under third party script (thats why the snippet).

If I try:

```javascript
require('js-cookie');
```

throws me this exception:

```mod-core-min.js:11 Uncaught Error: Module name "js-cookie" has not been loaded yet for context: _. Use require([])(…)```

If i try to call passing array:

```javascript
require(['js-cookie'])
```
```
mod-core-min.js:11 Uncaught Error: Mismatched anonymous define() module
```

Just imagine a enviroment: ```requirejs``` loaded on the page (without passing js-cookie in the configuration object) and you try to load the ```js-cookie``` thorught console (for example). It's not that hard to imagine. I tougth to create a JSFiddle Snippet, but I figured it would be something simple to understand. 

Again: I'm not able to load ```js-cookie``` using ```requirejs```, because the snippet with ```js-cookie``` code will load after the page loads (third party script). The problem is the first think that ```js-cookie``` will check if there is a requirejs instance, then check if is in Node JS enviroment and finnally create a ```Cookies``` global object. In my case, because requirejs is already loaded, the ```js-cookie``` loads throught CommonJS Syntax, inaccessible for me. I had to to a monkey patch in order to make the code runs smootly.

You can close this ticket if you think this is not a bug. Maybe my comments will serve to someone else with this problem (I found this issue on Google).

**Comment by FagnerMartinsBrack** [comment]
> You can close this ticket if you think this is not a bug.

The issue is already closed.

> Just imagine a enviroment: requirejs loaded on the page (without passing js-cookie in the configuration object) and you try to load the js-cookie thorught console (for example). It's not that hard to imagine. I tougth to create a JSFiddle Snippet, but I figured it would be something simple to understand.

The `Cookies` namespace is not available globally if requirejs is loaded on the page. That's by design.

> Maybe my comments will serve to someone else with this problem (I found this issue on Google).

As I said, try to post a question on StackOverflow, it is more likely to receive a better support answer there. There is a better SEO there too, so it is a better place to help someone else with a similar problem. This is just for issues related to the library, not with custom environments.

If you still believe we need some action to tackle this, feel free to create a Pull Request with a test that fails and reproduces the problem.

**Comment by FagnerMartinsBrack** [comment]
@juliovedovatto Can you please confirm if your use case is a duplicate of this one: https://github.com/js-cookie/js-cookie/issues/244#issuecomment-236415666

**Comment by juliovedovatto** [comment]
@FagnerMartinsBrack something like that. In my case, I try to load ```js-cookie``` in order to access ```Cookies``` global object. But because ```requirejs``` is already loaded, the script thinks I loaded ```js-cookie``` using ```requirejs```. 

Maybe you can modify the code to check if ```js-cookie``` is loaded using ```requirejs``` or  loaded from other source (like injection of code or explicit ```<script>``` tag. Does it make sense?

**Comment by FagnerMartinsBrack** [comment]
If js-cookie is loaded in an environment that uses AMD or UMD, it will register there and you should load using `require()` only. It makes no sense polluting the globals with the `Cookies` object if we don't need to.

That's by design, and changing it would break for all other cases where people use AMD or UMD in the browser in hope that the globals are not exposed.

I just don't understand why do you need to access the `Cookies` global if you're using an environment that supports AMD or UMD. One of the reasons module loaders were created is to avoid this!

**Comment by juliovedovatto** [comment]
@FagnerMartinsBrack as I say before: I **cannot** access the ` `requirejs``` configuration. I need to load a snippet using ```js-cookie``` through a third party script.

I understand the reason of your code design. Of course I'll prefer to use the correct method to load it. But in this case, I had to modify the code (dirty workaround) to solve my problem. I just posted here to inform you my case (maybe for other people will be not possible to load ```js-cookie``` via ```require```).

I rest my case.

Cheers
