### ISSUE TITLE
AMD over UMD

### ISSUE THREAD

**Issue by cllns** [js-cookie/js-cookie#244]
Thanks for `js-cookie`!

I'm using `js-cookie` with Browserify to build a widget. It works on most sites, but it failed on `nytimes.com`. I figured out was because `nytimes.com` uses AMD (that is, it has the `define` function defined in the global namespace) where as Browserify uses UMD.

My code was breaking because `js-cookie` defined itself via `define`, which I don't use at all.

Here's the current code:
```

if (typeof define === 'function' && define.amd) {
    define(factory);
} else if (typeof exports === 'object') {
    module.exports = factory();
} else {
    var OldCookies = window.Cookies;
    var api = window.Cookies = factory();
    api.noConflict = function () {
        window.Cookies = OldCookies;
        return api;
    };
}

```

I was able to fix it by swapping the order of the checks, so that it checks for UMD (`(typeof exports === 'object'`) before AMD (`(typeof define === 'function' && define.amd)`).

This just creates the opposite problem though, of preferring UMD over AMD.

In order to accommodate both, what about something like:
```
var usesAmdOrUMD = false;
if (typeof define === 'function' && define.amd) {
    usesAmdOrUMD = true;
    define(factory);
}

if (typeof exports === 'object') {
    usesAmdOrUMD = true;
    module.exports = factory();
}

if (!usesAmdOrUMD) {
    var OldCookies = window.Cookies;
    var api = window.Cookies = factory();
    api.noConflict = function () {
        window.Cookies = OldCookies;
        return api;
    };
}

```
This would have the effect of defining it *both* via AMD and UMD, if they're both available. I'm not sure if that's OK or not.

Maybe there's some other way of allowing either without preferring one over the other? Not sure how that'd be possible though.

I think this is the same issue as #173 and #201
And this is possibly related: #234

**Comment by FagnerMartinsBrack** [comment]
Hey, thanks for the explanation and links! Is there any way we can create a test for this first so that we can think of the best way to fix it?

We have a few [AMD tests](https://github.com/js-cookie/js-cookie/blob/960a75ed4f5876327c2a7628cc6e41be282effcc/test/amd.js) already, maybe we could use a similar structure to test this use case adding the minimum amount of dependencies to reproduce the issue?

**Comment by FagnerMartinsBrack** [comment]
@cllns I got some time to read it better and try to understand the problem in details, so let me see if I got the problem right:

The environment uses AMD and has a global `define` function. The environment also uses `UMD` and has a global `exports` object.

In this case, if AMD and UMD are available, we want to register it using `define()` and `module.exports = factory()`, but the current way js-cookie is setup it just registers for the AMD one and forgets` about the UMD `module.exports = factory()`.

Is that correct?

**Comment by cllns** [comment]
Yup, that's correct! 

For my use-case, I don't need it registered via AMD, just UMD. I don't see how to have it be one-or-the-other without preferring one of the two, which is why I think it makes sense to load it both ways.

**Comment by FagnerMartinsBrack** [comment]
@cllns This is just a convenience and not a blocker, right? Because if you have AMD, then it is reasonable to load using AMD. Is there a big problem?

I can imagine, though, a use-case where someone would want in some parts of the system to use one and in other parts of the system to use the other. In this use case, one wouldn't want to mix both module loaders and choose to load only one or the other as necessary.

Is that the same use case you have?

I can't see any big problem in registering it in both specs, other than the potential amount of bytes this might add to the lib.

I don't think this is a breaking change also, we can safely assume nobody is using 2 modules loaders in a way that it would break something. Correct me if I am wrong.

I will tackle this once I get back to the project and consider as a backwards compatible "bug" because it represents a behavior that is implicitly expected from the AMD/UMD support docs.

**Comment by cllns** [comment]
It is a blocker for me, I have to use an edited version of `js-cookie`. The trouble is that, in my code, I'm only using UMD. The code I'm working on is a widget which gets loaded onto other sites. To test this, we tried `nytimes.com` which uses AMD. So the current release of `js-cookie` loads only via AMD, which means my UMD code cannot access it.  

Seems like it would be OK to load via both. I can't think of a case where this change would break someone's code, but JS loading isn't my strong suit. 

Maybe take a look at how other projects have handled this?
