### ISSUE TITLE
If used in strict mode Cookie.get() always returns undefined 

### ISSUE THREAD

**Issue by ellenaua** [js-cookie/js-cookie#251]
I found that in strict mode this line throws an error 
https://github.com/js-cookie/js-cookie/blob/5c830fb71a2bd3acce9cb733d692e13316991891/src/js.cookie.js#L108
Cannot read property 'json' of undefined

Reason of the problem: strict mode. 
In non-strict mode "this" contains "window", but in strict mode it contains "undefined".

I see that you fixed it by changing api(key) to api.call(api, key)
https://github.com/js-cookie/js-cookie/commit/bccdaf79f7bef1d6d2cd56cbff00f8ed2a2c04a4
but it's not in release yet

I spent time debugging so decided to report so that others don't spend time debugging.

**Comment by ellenaua** [comment]
By the way, I'm not sure that this fixed it https://github.com/js-cookie/js-cookie/commit/bccdaf79f7bef1d6d2cd56cbff00f8ed2a2c04a4 - you pass "api" as this, but there should be "window"?

**Comment by FagnerMartinsBrack** [comment]
> I see that you fixed it by changing api(key) to api.call(api, key)

But still that addresses another problem, which is when there's a `window.json = true` property or an html element with the id `json` that will create a `window.json` property.

It might be worth keeping this issue open to create a test for the strict mode.

> By the way, I'm not sure that api.call(api, key) fixes it bccdaf7 - in this there should be "window" not api?

If we pass `window`, then the api won't get the new instance created by the `withConverter()` API. If `window` is present and you are not using any package managers, then the api will be attached to the `window.Cookies` namespace.

Also, by using the `window` directly in that part of the code we break the library in environments that contain no global `window` object, like nodejs for example.

Can you get [the code from the `window.json` fix](https://github.com/js-cookie/js-cookie/blob/bccdaf79f7bef1d6d2cd56cbff00f8ed2a2c04a4/src/js.cookie.js) and test it? Does it works as intended even with "use strict" enabled?
By the way, I would not encourage using strict mode in vendor files you don't control. The idea is to make it restrict to certain scopes where you're sure that there will be no breakage:

**Safe**
```javascript
var scoped = function() {
  "use strict";
  // This code is safe
}
```

**Not safe**

```javascript
"use strict";
var scoped = function() {
  // This code is in strict mode, as everything else we don't control
}
```

**Comment by ellenaua** [comment]
Thanks for quick and detailed reply.
I tested - it works in strict mode now (I used git+https://github.com/js-cookie/js-cookie.git#72d05c27ebfb99aa8b6ae8f1b46210e223e815b9 in package.json)

Small note: maybe you'll add some console.log to catch() blocks so that errors are not silent?
It would be great if you make new release

**Comment by FagnerMartinsBrack** [comment]
> maybe you'll add some console.error to catch() blocks so that errors are not silent?

Feel free to create a PR suggesting something. Failing silently is by design, it might not be worth throwing a global error because of some malformed cookie and the `console` is not available in older versions of internet explorer.

Also, adding more code just for debug will break our feature of having ~800 bytes gzipped size.

We have plans to provide a debugging file for development that will make it possible to run js-cookie with a lot of warnings in the console, see https://github.com/js-cookie/js-cookie/issues/57#issue-92249881.

I [have started a project](https://github.com/js-cookie/js-cookie-release) to handle the release process, but haven't had a lot of time to work on it.

> It would be great if you make new release

I want to wait until other issues are addressed so that I can release everything at once, see https://github.com/js-cookie/js-cookie/milestone/8.

This problem is not critical, but just an edge case. I suggest going with the commit until we release a new version, but be advised that master is  always unstable (although reverting things in this repository is not something that happens frequently).

**Comment by FagnerMartinsBrack** [comment]
> It might be worth keeping this issue open to create a test for the strict mode.

I don't think it makes sense creating a test for strict mode. It is a bad practice forcing strict mode in vendor files. It doesn't make sense encouraging bad practices.

Because of the `window.json` fix this issue doesn't exist anymore, but **that is just a side effect and nobody should rely on it being "fixed"**. We can't guarantee that the error in strict context won't come back in a minor version without notice.

The recommended approach is to apply the fix in the developer environment, not enforcing "use strict" in vendor files (or globally, for that matter), and instead leverage the [strictness principle](https://medium.com/@fagnerbrack/the-strictness-principle-9997e483cafb) by scoping the strict mode in a strict context.
