### ISSUE TITLE
Cookies.remove should return 'true' on successful cookie deletion

### ISSUE THREAD

**Issue by stalingraddd** [js-cookie/js-cookie#252]
if i want to use this expression, i can't, because Cookies.remove always returns _undefined_ even on successful deletion:
````
Cookies.get('test') == 'value' && Cookies.remove('test', {path: ''});

**Comment by FagnerMartinsBrack** [comment]
This feature was removed because it is impossible to check that the cookie was removed to return `true` or `false` deterministically. There's no such API in js-cookie that returns `true` or `false` on `Cookies.remove()`, it is just void, and there's no browser API that provides us that API either.

The problem is that if a cookie is created on a different path, it is impossible to know of the cookie exists or not when calling `Cookies.get()` on another path. Not just because of a browser limitation, but how would we know if the user expects it should return `true` for a cookie that exists in any path of the domain or for a cookie that exists in just that specific path that the cookie is being removed?

Any choice we make might violate the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for the developers that assume differently.

**Comment by FagnerMartinsBrack** [comment]
Correction: this feature **did exist officially** in the docs at the time of jquery-cookie. See the ["Usage" part of the README on the version 1.5.1](https://github.com/js-cookie/js-cookie/blob/v1.5.1/README.md#usage):

```
// Returns true when cookie was successfully deleted, otherwise false
Cookies.remove('name'); // => true
Cookies.remove('nothing'); // => false
```

So, yes. It existed and it was publicly documented, but I didn't see the information that it was removed in the changelog of [version 2](https://github.com/js-cookie/js-cookie/tree/v2.0.0) or [version 2 beta](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0-beta.1). For that reason, I have just added it.

```
## Cookies.remove() return value is not defined
```

For context on where it was removed, see https://github.com/js-cookie/js-cookie/pull/21.

@stalingraddd Thank you very much for reporting this!

**Comment by tiger-percentage77** [comment]
Check this note https://javascripter.space/questions/identifying-the-presence-of-a-particular-cookie
