### ISSUE TITLE
Polyfill for migrating from jQuery Cookie

### ISSUE THREAD

**Issue by danieliser** [js-cookie/js-cookie#271]
Not sure if this is helpful, but since many users will be porting from jQuery Cookie, here is a polyfill function I came up with that handles easy swapping from one to the other.

            /**
             * Polyfill for jQuery Cookie argument arrangement.
             *
             * @param key
             * @param value
             * @param attributes || expires (deprecated)
             * @param path (deprecated)
             * @returns {*}
             */
            api.process = function (key, value, attributes, path) {
                if (arguments.length > 3 && typeof arguments[2] !== 'object' && value !== undefined) {
                    return api.apply(api, [key, value, {
                        expires: expires,
                        path: path
                    }]);
                } else {
                    return api.apply(api, [].slice.call(arguments, [0, 2]));
                }
            };

**Comment by FagnerMartinsBrack** [comment]
AFAIK jQuery cookie never had the last argument as `path`, where does that come from?

**Comment by danieliser** [comment]
Hmm, maybe that was just something I did along the way and didn't realize it. Sorry about that.

**Comment by FagnerMartinsBrack** [comment]
@danieliser It's fine.

We're definitely up for ideas on how to make migration easier, although I haven't noticed a lot of requests that justifies for something more automatic since v2 came out last year. Version [1.5.1](https://github.com/js-cookie/js-cookie/tree/v1.5.1#migrating-from-jquery-cookie) documents how to migrate it and seems to be working so far.

If there's anything else we could take action on, just ping and I reopen it.

**Comment by danieliser** [comment]
@FagnerMartinsBrack Well in my case its used in a WP plugin with 60k installs, so maintaining the hundreds of custom calls to our mapped pm_cookie function were important. IE my concern was backward / forward compatibility on their part.

**Comment by FagnerMartinsBrack** [comment]
@danieliser Do you think that something like this could be useful for the general audience of the library?

I would argue that using the version 1.5.1 allows for backwards compatibility until each consumer is ready to migrate to v2. Also, if necessary, we could create a "migrate" plugin, just like how jquery did, to highlight in the console the APIs that were removed in v2 but I honestly don't see the value it brings that justifies the amount of work.

Make sense?

**Comment by danieliser** [comment]
@FagnerMartinsBrack From my perspective (biased due to being a WP dev, you know how they are about backward compatibility), it couldn't hurt. If they had a way to migrate without having to change their code then why wouldn't they.

Along that line if your goal is to migrate people from jQuery Cookie to JS Cookie, then it serves that purpose as well. In fact once you got it 100% tested, you could push JS Cookie as the new master branch of jQuery cookie.

**Comment by FagnerMartinsBrack** [comment]
@danieliser 

> In fact once you got it 100% tested, you could push JS Cookie as the new master branch of jQuery cookie.

That's not going to happen, we have decided to freeze that project and focus on the new one. The reason why we didn't just renamed it was to make a soft migration instead of a forced one, after all jquery cookie had years of life at the time, since when jquery was created (it was one of the first plugins).

Regarding the value of it I definitely agree with it. I can see value on having an adapter that allows running the latest version of js-cookie along with js-cookie. My point is mostly regarding maintainance and support, I haven't had a lot of time to contribute to open source lately, so I can't just promise that I can do this since I am also involved in impress.js, for example.

What I suggest is starting this in a separate repo. If a considerable amount of devs become interested on this it would definitely make sense porting it to the main js-cookie repo and support it. I can help reviewing it if necessary.

What do you think @danieliser? Willing to go for it?
