### ISSUE TITLE
Installing this plugin

### ISSUE THREAD

**Issue by NanditaReshamwala** [js-cookie/js-cookie#277]
hi there,

How would it be easier to install this plug in in .NET solution opened in Visual studio?  Can it be done using Nuget Package Manager? 

kind regards,
Nandita

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevant in Google results and therefore a solution posted there is more likely to reach someone with a similar problem.

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

Thanks.
