### ISSUE TITLE
Cookies is not defined

### ISSUE THREAD

**Issue by mcianciulli** [js-cookie/js-cookie#278]
Getting error in my production environment, that Cookies is not defined. It is v2.0.4.

**Comment by ginestra** [comment]
Hi, I'm having a similar issue.
Using v2.1.3 with requirejs.
js.cookie.js gets included in the built correctly, but I get `Cookie is not defined`.
Any pointers are greatly appreciated!

**Comment by ginestra** [comment]
@mcianciulli 
Not sure if you're using requirejs, but this might help.

I fixed it by renaming js-cookie to jscookie first (as a precaution, requirejs doesn't seem to like dashes) and applying some other changes, see below.

In `config.require.js` I have: `'jscookie': '../vendor/js-cookie/src/js.cookie',` in paths and `'jscookie': { exports: 'JScookie'},` in the shim.

Then a created a `cookie.js` file where I define the module:

```define([
    'module',
    'jquery',
    'jscookie'
], function(module, $, cookie) {
    'use strict';

    $(document).ready(function() {
        // Set cookie on click
        $('#myDiv').on("click", function() {
            cookie.set('name-cookie', 'cookie-value', { expires: 30 });
        });
    });

    return module;
});```

Finally I load `cookie.js` in my main js file where I pass require():

```require([
    'requirejs',
    'jquery',
    'cookie'
])```

Hope this helps.

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevant in Google results and therefore a solution posted there is more likely to reach someone with a similar problem.

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

Thanks.
