### ISSUE TITLE
Will Js-cookie work if the cookies are disabled in the internet explorer.

### ISSUE THREAD

**Issue by Balakumar90** [js-cookie/js-cookie#279]
Hello , 

If I block cookies in IE . Will the JS_cookie still be working ?

Thanks,
bk

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
