### ISSUE TITLE
Cookies doesn't work

### ISSUE THREAD

**Issue by jorootsqc** [js-cookie/js-cookie#281]
I try with simple code buit that doesn't work to save value in Cookies. Here my code:

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>test</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.js"></script>
	<script type="text/javascript">

$( document ).ready(function() {
 Cookies.set('name', 'value');		
		var _name = Cookies.get('name');		
		alert('my name is: '+_name);
}); 
			
	</script>	
</head>
<body>
	<div><p id="name"></p></div>
</body>
</html>

*** _name is already undefined
Can you tell me where is my bug ?

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie. The code you provided doesn't seem to have any issue, make sure [you are not using `file://` protocol](https://github.com/js-cookie/js-cookie/issues/97).

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
