### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by psabharwal123** [js-cookie/js-cookie#297]
npm WARN saveError EPERM: operation not permitted, rename 'C:\...................\client\package.json.108113333' -> 'C:\............................\client\package.json'
m.pogo.com@1.0.0 C:\p4\html5\m.pogo\main\client
`-- js-cookie@2.1.3

happens only with js-cookie and not with any other module

**Comment by FagnerMartinsBrack** [comment]
Try to create a question in StackOverflow first. There's not enough information for us to take any action. There might be some problem with your local environment.

**Comment by FagnerMartinsBrack** [comment]
As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
