### ISSUE TITLE
Not setting cookie in Chrome

### ISSUE THREAD

**Issue by michaelcouck** [js-cookie/js-cookie#299]
This code:

`$("a").each(function () {
        var a = this;
        $(this).click(function () {
            var linkId = $(a).attr('id');
            if (linkId != undefined) {
                alert('New active link : 4 : ' + linkId);
                Cookies.set(cookieName, linkId);
                var newLinkId = Cookies.get(cookieName);
                alert('New active link : 5 : ' + newLinkId);
            }
        });
    });`

Works perfectly well in FireFox but not in chrome strangely enough. The cookie is not reset, it is always the original cookie.

I am using chrome Version 56.0.2924.87 (64-bit) on linux. I see that the compatibility matrix for browsers does not include my version, does this mean that it will never work on this browser and version?

**Comment by FagnerMartinsBrack** [comment]
[Check this](https://github.com/js-cookie/js-cookie/issues/129#issuecomment-178854498).

**Comment by michaelcouck** [comment]
Thanks Fagner, 

Makes sense, however I am still sitting with the issue of course. I can't very well say that the site does not work in Chrome of course, imagine that?...

What is the solution pretty please?

Cheers,
Michael

**Comment by FagnerMartinsBrack** [comment]
@michaelcouck If the issue is the cookies not working because chrome is being run in the `file://` protocol, try to setup a server and run in the `http://` protocol.

**Comment by michaelcouck** [comment]
Thanks Fagner,

I'll investigate that.

Cheers,
Michael

**Comment by rek** [comment]
I wish these issues got taken more seriously, chrome is totally not setting cookies anymore...

The issue seems to be when setting a domain that has more than one subdomain in depth. Eg:

When you are on: `sub.test.domain.com`

And you set cookies with the config:

`domain: .domain.com`

This used to work ^^

But now it does not, you have to set:

`domain: .test.domain.com`

**Comment by FagnerMartinsBrack** [comment]
@rek Not sure if that has something to do with it, but there's a problem in your examples. The documentation doesn't say the "domain" should contain a dot in the prefix, neither the cookie spec (RFC 6265). Therefore, instead of `domain: .domain.com`, it should be `domain.com`.

Despite that, if cookies stopped working in Chrome that's a Chrome problem. The only thing js-cookie does is to serve as a dumb interface to `document.cookie` and there's no big change since version from 4 months ago. I just pointed out the `file://` situation because in my experience it is the most common problem of cookies not working in Chrome. If that's not the case, can you please provide an example that fails using `Cookies.set` but succeedes using `document.cookie`? That will prove there's a problem with the library.

Besides, this is an open-source project. You're free to create a Pull Request to improve the docs or change something.

**Comment by rek** [comment]
Thanks for the reply. Sorry for the heat above, was having a tough day at work. I will look into this further :)

**Comment by rek** [comment]
Dot's in the the domain are ignored thesedays. [Ref](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

But the issue seems to be with document.cookie not this lib, so sorry for coming here first, I tested with it directly as you mentioned and could reproduce the issue above  (where the cookie is not set if you only use the top level of your sub domain as the domain field in the cookie)

I guess we have to wait for chrome now. But at least we have the work around of setting more of the path in the domain field.

**Comment by michaelcouck** [comment]
Well, just to throw a spanner in the works, I find that everything is working fine on Chrome, now. I really couldn't tell you what changed that is just started working perfectly, don't know.

I hope I was not hallucinating...

I guess that doesn't help? ;) But on the bright side, there is hope for Chrome, the chrome lining?

**Comment by FagnerMartinsBrack** [comment]
Well, if anyone knows which version there was an issue in `document.cookie` on chrome, feel free to shout out. In the mean time, would it make sense documenting that js-cookie does not accept leading dots in the domain?

@michaelcouck @rek

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by DRASH7775** [comment]
> @michaelcouck If the issue is the cookies not working because chrome is being run in the `file://` protocol, try to setup a server and run in the `http://` protocol.

We are working on Water Management and Monitoring System and we were stuck at testing html pages locally on google chrome, and this solution leads us to good lead.

**Comment by FagnerMartinsBrack** [comment]
@DRASH7775 You can also create a fake server like [node-static](https://www.npmjs.com/package/node-static) to run your code locally.
