### ISSUE TITLE
Cookie undefined

### ISSUE THREAD

**Issue by faridsa** [js-cookie/js-cookie#308]
Hello, I'm trying to use your nice plugin to manage cookies with no success.

My layout is made as this:

- jQuery 2.2.4
- jQuery Migrate 1.4.1
- JS Cookie 2.1.3

I've set up a navbar with two buttons for language selection, each fires a jquery event to set a cookie with the name of language selected, and then reload page to change contents according to language selection.
But when click on a language button, cookie remains undefined.
I tried to change path with no success.
Removing jQuery Migrate makes no changes.

Here is a jsfiddle with my issue if anybody could give some help.
[https://jsfiddle.net/faridsilva/vrqvLfk2/16/](url)

Thanks everybody.

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by faridsa** [comment]
Thank you for your reply and gently corrections.
According to your guidelines I have made a post in stackoverflow with this situation and additional information.
I let it [here](http://stackoverflow.com/questions/42507852/js-cookie-always-returns-undefined) to connect the situation.
Regards.
