### ISSUE TITLE
Can not get cookie in php

### ISSUE THREAD

**Issue by AGhasemzadeh** [js-cookie/js-cookie#324]
Hello,
When I use this plugin I can't get values in php environment but I have cookie in browser.

**Comment by B1scuit** [comment]
This would be because PHP is a server-side language whereas this is a client side plugin, the two cannot communicate with each other, I would advise setting the cookie with PHP (so a record of it is kept on the server) and obtaining it with js-cookie, if you set the cookie with js-cookie, there is no easy way for the server to know the cookie exists

**Comment by AGhasemzadeh** [comment]
Hello,
Thanks but when I check storage in firefox I see cookies.
I think it should work.

**Comment by sonnysavage** [comment]
If you're setting the cookie in the first request via JavaScript (js-cookie), PHP won't be able to see it until the second request.

**Comment by AGhasemzadeh** [comment]
But cookie should be accessible in all environment.
Any solution?

**Comment by sonnysavage** [comment]
It *is* available. I was just explaining order of operations.

**Comment by AGhasemzadeh** [comment]
Hello
Can you give me an example?

**Comment by jivido** [comment]
I'm also encountering this problem, on Chrome it works though, but Safari doesn't get it... 
Maybe Safari and Firefox have the same problem? 
I set cookies with this plug-in, and read them from PHP. That works on Chrome.

**Comment by AGhasemzadeh** [comment]
I want to do this job with laravel can you help me?

**Comment by yellow1912** [comment]
@jivido I doubt that's the real issue. Do you happen to use a different subdomain for example when you redirect? Sometimes people think www.abc.com is the same as abc.com which is a huge mistake

@AGhasemzadeh I don't see how Laravel makes any difference? The JS set the cookie, this cookie can be read on the server side (assuming both running under the exact same domain). Note that if you set the cookie via js then the value is available in PHP in the next request.

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie) and `php`. The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Also, regarding php issues have you seen [this](https://github.com/js-cookie/js-cookie/blob/8b70250875f7e07445b6a457f9c2474ead4cba44/SERVER_SIDE.md#php)?

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by Lampe2020** [comment]
I have noticed that cookies set in PHP can be read in JS, trying to overwrite them just created a second cookie with the same name (at least when directly interacting with `document.cookie`) and cookies set in JS aren't readable in PHP because Firefox seems to keep some secret record over wether a cookie was set by a cookie header or a JS, separating those and sending only those set by a header back as a header.
