### ISSUE TITLE
Cookies aren't visible at subdomain

### ISSUE THREAD

**Issue by JamesJGoodwin** [js-cookie/js-cookie#342]
Hello, i'm trying to write cookies for a subdomain and a main domain, so they should be available both on the main domain and on the subdomain:

```javascript
Cookies.set('last_search', JSON.stringify(data), { expires: 7});
Cookies.set('last_search', JSON.stringify(data), { expires: 7}, { domain: 'search.example.com'});
```
But after writing the cookies i go to the subdomain and cookies are not written at all. Am i doing right?

Regards,
Andrew.

**Comment by salzersoftware** [comment]
@JamesJGoodwin you need to put a period in front of the domain. Check out more info [here](https://stackoverflow.com/questions/9618217/what-does-the-dot-prefix-in-the-cookie-domain-mean).

**Comment by FagnerMartinsBrack** [comment]
To follow up on @salzersoftware, IE behavior is different in this regard, see https://github.com/js-cookie/js-cookie/tree/8b70250875f7e07445b6a457f9c2474ead4cba44#domain.

That's why we don't document the `.` syntax. We only document and support cross browser compatible behavior. Use it at your own risk.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
