### ISSUE TITLE
Setting above max length fails silently

### ISSUE THREAD

**Issue by callumacrae** [js-cookie/js-cookie#348]
```
let str = '';
for (let i = 0; i < 10000; i++) {
  str += Math.random();
}
```

This acts like it works:

```
cookies.set('test-cookie', str);
```

But then this returns undefined:

```
cookies.get('test-cookie');
```

Obviously, this is an extreme example (nobody would actually try to store a string that long in a cookie), but I'd still expect at least an error.

**Comment by FagnerMartinsBrack** [comment]
See https://github.com/js-cookie/js-cookie/issues/86 and https://github.com/js-cookie/js-cookie/issues/227 and https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions/d279bdbee6148b19c0f714d407a4c3e68a226f59#why-are-my-cookies-being-deleted.

We can handle it in a `js.cookie.debug.js`, see https://github.com/js-cookie/js-cookie/issues/57 (Any help on how to do this without adding a lot of dependencies is much appreciated).

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

We'll track the issue on https://github.com/js-cookie/js-cookie/issues/57.
