### ISSUE TITLE
Why decodeURIComponent when writing

### ISSUE THREAD

**Issue by andraaspar** [js-cookie/js-cookie#35]
What is the purpose of [this line](https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js#L59):

```
value = value.replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g, decodeURIComponent);
```

When writing a cookie? This line reverts some of the characters converted by encodeURIComponent, right? Is that only to make the value more readable, or does it serve any other purpose?

**Comment by FagnerMartinsBrack** [comment]
Those characters are allowed in a cookie value, so there's no need to encode it. js-cookie encodes only the characters that are not allowed in the cookie value:

https://github.com/js-cookie/js-cookie/tree/1a0d1ed13c106382d2cfe1186a73e8091e4ac349#encoding

> This project is RFC 6265 compliant. All special characters that are not allowed in the cookie-name or cookie-value are encoded with each one's UTF-8 Hex equivalent using percent-encoding.
The only character in cookie-name or cookie-value that is allowed and still encoded is the percent % character, it is escaped in order to interpret percent input as literal.

Check here for context: https://github.com/js-cookie/js-cookie/pull/20#issuecomment-94453407

and here for the spec: http://tools.ietf.org/html/rfc6265#section-4.1.1

> Is that only to make the value more readable, or does it serve any other purpose?

It just to minimize the amount of encoded characters to leverage what browsers support and to save bytes. There is a limit of 4096 bytes per cookie, if we encode valid characters like `+`, then we are transmitting 3 unnecessary bytes to the server (`%2B`) for a character that is globally supported.

**Comment by andraaspar** [comment]
I see, a very nice feature. Thanks for the explanation!
