### ISSUE TITLE
Passing UTM Parameters to Intercom

### ISSUE THREAD

**Issue by dtalexone** [js-cookie/js-cookie#356]
I am trying to pass UTM parameters to Intercom to track users who chat with us and where they are coming from.

Intercom recommends capturing that information and setting it with the jQuery cookies plugin. Here is the documentation.

I am using the latest release of Cookies and updated the code Intercom provides just a bit.

`<script type="text/javascript" src=".../js/js.cookie.js"></script>`

`<script type="text/javascript">
function getURLParam(name) {
  return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(window.location.search) || [null, ''])[1].replace(/\+/g, '%20')) || null;
}

jQuery(document).ready(function($) {
  if(getURLParam('utm_source') !== null) {
    Cookies.set('utm_source', getURLParam('utm_source'), {
      expires: 365,
      path: '/',
      domain: window.location.hostname,
      secure: true
    });
  }

  if(getURLParam('utm_campaign') !== null) {
    Cookies.set('utm_campaign', getURLParam('utm_campaign'), {
      expires: 365,
      path: '/',
      domain: window.location.hostname,
      secure: true
    });
  }

  if(getURLParam('utm_medium') !== null) {
    Cookies.set('utm_medium', getURLParam('utm_medium'), {
      expires: 365,
      path: '/',
      domain: window.location.hostname,
      secure: true
    });
  }
});
</script>`

I know this is working correctly because using the Javascript console in Chrome Developer Tools, I can call

`Cookies.get('utm_source')`

and get the actual value if the URL contains that particular UTM parameter.

But for some reason, this is not passing to Intercom and the code (located in the footer) for passing that information looks like:

`<script>
  window.intercomSettings = {
   app_id: "zto7cy6x",
   "utm_source": Cookies.get('utm_source'),
   "utm_medium": Cookies.get('utm_medium'),
   "utm_campaign": Cookies.get('utm_campaign')
  };
</script>`

What am I doing wrong?

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
