### ISSUE TITLE
How to handle a Date as part of serialized cookie

### ISSUE THREAD

**Issue by mwpowellhtx** [js-cookie/js-cookie#361]
Hello,

I've got a use case wherein I'd like to work with JavaScript Date instances as part of a deserialized cookie. However, it seems that serializing/deserializing the object has difficulties with this interpretation.

First impressions are that I may want to translate some nominal representation, whether numeric (i.e. seconds or milliseconds since epoch, etc), or string (i.e. literally the ISO string representation), and perform a transformation to/from the language level Date object at the appropriate moment.

Any other suggestions how good/better/best to deal with this?

Thank you...

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

In your case, though, it might be possible to serialize JavaScript Date instances. However, client-side serializing is incredibly tricky and there's a lot of peculiarities in regards to timezone. It's so complicated I would have to research all over again if I would have a similar use case. I highly recommend asking in StackOverflow. Some people might have worked on this recently around there.

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
