### ISSUE TITLE
Remove support for IE 6, 7 and 8

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [js-cookie/js-cookie#370]
Some parts of our development environment are starting to break due to many dependencies removing support for IE 8.

Here I'll list all the problems that are happening because of it:

* `qunitjs ` doesn't support IE 6, 7 and 8 and that [prevents js-cookie from upgrading](https://github.com/js-cookie/js-cookie/pull/216#issuecomment-228578080).
* `grunt-contrib-uglify` version 2 [was failing due to `screwIE8` option](https://github.com/js-cookie/js-cookie/pull/242#issuecomment-236415359).

**Comment by FagnerMartinsBrack** [comment]
It looks like Sauce Labs does not support IE7 and IE8 anymore:

<img width="613" alt="screen shot 2017-10-28 at 3 03 33 pm" src="https://user-images.githubusercontent.com/835857/32131089-460175b6-bbf1-11e7-9eec-78d6b4de2b82.png">

**Comment by FagnerMartinsBrack** [comment]
Just to point it out, if we can remove IE 6, 7, 8 support there's a lot of bytes we might be able to trim out of the source :D

**Comment by tbillington** [comment]
Microsoft [stopped supporting IE10 over 2 years ago](https://www.microsoft.com/en-au/windowsforbusiness/end-of-ie-support), and the implementation of cookies is not going to change in older browsers, it seems fair to abandon unsupported browsers when making a new major version.

Users can always stay on version 2 of the library if they need the backwards compatibility.

**Comment by FagnerMartinsBrack** [comment]
> [...] the implementation of cookies is not going to change in older browsers

The cookies implementation in browsers doesn't matter for the purpose of compatibility. It's about which JS features we can use and which ones we can't, that's the library code, not browsers code.

We're definitely considering drop support due to the problems stated above. However, because there's not a big cost to support those browsers in this project, we're just leaving it.

We might as well drop it in the next major release.

**Comment by ColinLaws** [comment]
Well, you're already at ~900 bytes gzipped, so I can't see size as really being a big sticking point. The real question is how big are the improvements you're trying to make, and if support for those browsers is a major feature of your software. I feel like supporting older browsers is more of a testament towards engineering practices than anything, but the minute it starts to hurt when trying to move forward you need to let it go. 

I guess the real question is: Who is js-cookie for? 

I would say most of the consumers of your library are creating new projects with new frameworks and technologies. Also, be mindful that even large companies who may have legacy software probably don't use anything as old as IE8 anyways simply due to security vulnerabilities.

**Comment by FagnerMartinsBrack** [comment]
> I can't see size as really being a big sticking point

A sticking point for what? Reducing byte size whenever we can is one of the primary goals of the library being "lightweight" as stated in the project's description:

> A simple, lightweight JavaScript API for handling browser cookies

Not sure what you mean by this:

>  how big are the improvements you're trying to make

Which improvements are you talking about? Support for oldIE only affects testing, it's not blocking any improvement other than reducing the number of bytes the browser has to download.

> I guess the real question is: Who is js-cookie for?
> I would say most of the consumers of your library are creating new projects with new frameworks and technologies.

But why is that question or your comment relevant to this thread, can you make it clear?

We avoid making assumptions about frameworks or libraries in which js-cookie is used. We primarily assume it's being used on a browser with JavaScript.

**Comment by ColinLaws** [comment]
You seem to understand the issue pretty well then, I can't see you requiring my input.

Sorry for the uninformed attempt at contribution.

**Comment by FagnerMartinsBrack** [comment]
@ColinLaws Sorry if my comment caused the wrong impression, that was not the intention. I'm honestly trying to understand what you're trying to say because it wasn't clear, that's why I asked the questions with quotes: to avoid a [Wittgenstein's Beetle-like](https://medium.com/@fagnerbrack/wittgenstein-s-beetle-in-software-engineering-dcea89a5db92) conversation.

We definitely value contributions so I don't want you to think that we don't value your input. It would be great if you could elaborate the comment so that it becomes clearer and objective :)

Thanks

**Comment by ColinLaws** [comment]
I honestly have just been a user of the library and really enjoy using it, so I came over to try to make a contribution but I honestly do feel a bit misinformed at this point. I didn't mean to sass you, I really honestly do feel like my input wasn't very valuable after seeing that you only use the older browsers for testing.

As far as byte size, the reason why I had mentioned it not being a big deal (and I hate to be that guy) but I feel it is negligible in 2018 to really care after you've done such a good job at reducing the size to where it is at. After reading it was my understanding that you were essentially asking if the old browsers shouldn't be supported in favor of a reducing the project size and to implement new libraries that are going to help the project. That's why my first impression was 'Well, just remove the support in favor of new browsers, because the old browsers are irrelevant and the byte size is negligible.'.

That is also why I kind of asked who it was for, my intention was to ask if there were really any developers who are implementing the library who need it on really old systems. But I like your approach to it, don't ever assume who it's made for, just make it the best it can be.

**Comment by FagnerMartinsBrack** [comment]
Cool @ColinLaws, thanks for the clarifications. To have a better context of the compromises we're doing in favor of the "byte size" thing, see https://github.com/js-cookie/js-cookie/issues/415#issuecomment-373881523.

**Comment by ColinLaws** [comment]
@FagnerMartinsBrack Also, thanks for this, we have this all the time here at work, and I apologize for not elaborating, that's what this job is all about. I just find it hard to understand tone sometimes and automatically think people are offended at my input, so your clarification made sense to my logical side versus my reactive side taking it personally (as I shouldn't be of course). 

> I'm honestly trying to understand what you're trying to say because it wasn't clear, that's why I asked the questions with quotes: to avoid a Wittgenstein's Beetle-like conversation.

In regards to #415 I can see why you make such an effort towards reducing the size of the project. It reminds me of the case in which the US govt. changed their font and saved millions of dollars. 

I hope that my input made some sense, I thought you were just gathering an opinion rather than something that required a deeper understanding of your code, that's why I had jumped at this open issue to try and make a contribution.

**Comment by ColinLaws** [comment]
I've been looking around at QUnit, how it's used in the project, and screwIE8.

I can see what you mean by the fact that it only changes testing. So at this point, if you do intend to upgrade, you couldn't test for older browsers and thus say they are no longer supported?

If I'm understanding this all right, I'm on the side of upgrading in any attempt to reach your project goal of reducing size against favoring the capability of testing/deploying to older browsers.

**Comment by FagnerMartinsBrack** [comment]
One more reason to drop support: [Browserstack implementation issues](https://github.com/js-cookie/js-cookie/pull/409#issuecomment-451098036)

**Comment by phtwo** [comment]
Oh, after using the es6 module, it has intellisense

**Comment by willstocks-tech** [comment]
I'd personally nuke support for IE10 support as well (even though [BrowserStack](https://www.browserstack.com/list-of-browsers-and-platforms/live) still support it in their W8 and older tests) 😉 as IE11 is _in theory_ the "minimum" supported browser by MS themselves and even then, depending on who you speak to the support for that is questionable/security only.

Per discussion on https://github.com/js-cookie/js-cookie/issues/497#issuecomment-475165931:

> if [this chart](https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browserVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222018-03%22%2C%22dateEnd%22%3A%222019-02%22%2C%22segments%22%3A%22-1000%22%2C%22pageLength%22%3A50%7D) is to be believed, IE10 and older (because in theory, IE11 still has "support" due to being part of W10) caters for less than 2.05% of worldwide browser usage

For my sites, I take the view of `latest - 2`, except for IE/Edge, in which case I only support Edge as an absolute minimum. I don't bother with supporting IE anymore because personally I find the supportability overhead unnecessary. I more than appreciate that this approach does not work for everyone/everything - but that works for me! Again, it doesn't necessarily work for js-cookie as I appreciate the level of cross-browser compatibility the lib offers!

On that note... I'd be super happy with a version of js-cookie that utilized fully modern features/functions and then polyfilling those features for older browsers if I absolutely wanted to (as long as I had a list of "potentially unsupported features" - I made a little script that does this for me conditionally which I use on most of my sites anyway). 

That, or maybe just a "v3" that is a "breaking release" in terms of legacy browser support? 😁

**Comment by semoal** [comment]
> I'd personally nuke support for IE10 support as well (even though [BrowserStack](https://www.browserstack.com/list-of-browsers-and-platforms/live) still support it in their W8 and older tests) 😉 as IE11 is _in theory_ the "minimum" supported browser by MS themselves and even then, depending on who you speak to the support for that is questionable/security only.
> 
> Per discussion on [#497 (comment)](https://github.com/js-cookie/js-cookie/issues/497#issuecomment-475165931):
> 
> > if [this chart](https://netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browserVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222018-03%22%2C%22dateEnd%22%3A%222019-02%22%2C%22segments%22%3A%22-1000%22%2C%22pageLength%22%3A50%7D) is to be believed, IE10 and older (because in theory, IE11 still has "support" due to being part of W10) caters for less than 2.05% of worldwide browser usage
> 
> For my sites, I take the view of `latest - 2`, except for IE/Edge, in which case I only support Edge as an absolute minimum. I don't bother with supporting IE anymore because personally I find the supportability overhead unnecessary. I more than appreciate that this approach does not work for everyone/everything - but that works for me! Again, it doesn't necessarily work for js-cookie as I appreciate the level of cross-browser compatibility the lib offers!
> 
> On that note... I'd be super happy with a version of js-cookie that utilized fully modern features/functions and then polyfilling those features for older browsers if I absolutely wanted to (as long as I had a list of "potentially unsupported features" - I made a little script that does this for me conditionally which I use on most of my sites anyway).
> 
> That, or maybe just a "v3" that is a "breaking release" in terms of legacy browser support? 😁

We're using this libray on multiple financial websites, that needs ie10 support.

**Comment by willstocks-tech** [comment]
Agree and accept that @semoal, but at the same time there's nothing stopping you using the current version? 

I would _assume_ that the API/functionality wouldn't change, but would just make use of newer, modern javascript features to achieve the same end goal?

That is why I suggested "That, or maybe just a "v3" that is a "breaking release" in terms of legacy browser support?". There's only so long support for such browsers (IE10 and older) can be catered for, especially when Microsoft themselves don't even support it!

**Comment by semoal** [comment]
> Agree and accept that @semoal, but at the same time there's nothing stopping you using the current version? I would do the same for the B2B sites I've worked on, that require legacy browser support.
> 
> I would _assume_ that the API/functionality wouldn't change, but would just make use of newer, modern javascript features to achieve the same end goal?
> 
> That is why I suggested "That, or maybe just a "v3" that is a "breaking release" in terms of legacy browser support?". There's only so long support for such browsers (IE10 and older) can be catered for, especially when Microsoft themselves don't even support it!

Or just writing it in typescript(or just javascript) with babel and compile for internet explorer 10 (or necessary).
Your codebase will be updated to modern features and the output will satisfy everyone.
