### ISSUE TITLE
IE11/Windows 10 => Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by Sparkmasterflex** [js-cookie/js-cookie#372]
In IE11 on Windows 10, I'm getting `Object doesn't support property or method 'includes'` error on `Cookie.set('something', null)`. Previously I had `Cookie.remove('something') and that was giving the same error.

```
  Cookie = require('js-cookie')
  Cookies.set('save_lead', null)
  // used to be:
  // Cookies.remove('save_lead')
```
  

![screen shot 2017-10-24 at 4 16 15 pm](https://user-images.githubusercontent.com/726129/31977040-b51438e4-b8d6-11e7-9d40-12c7afe7d03f.png)

<img width="1252" alt="screen shot 2017-10-24 at 4 16 47 pm" src="https://user-images.githubusercontent.com/726129/31977069-da0942ca-b8d6-11e7-917f-a31ebf929117.png">

**Comment by Sparkmasterflex** [comment]
I'm using npm package version js-cookie@2.1.4

**Comment by FagnerMartinsBrack** [comment]
js-cookie doesn't have support in the API for `Cookie.set('something', null)`, the second argument has to be a valid String.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

**Comment by Sparkmasterflex** [comment]
done: https://stackoverflow.com/questions/46944403/ie11-windows-10-object-doesnt-support-property-or-method-includes

**Comment by FagnerMartinsBrack** [comment]
Thanks @Sparkmasterflex. Closing for now so that the discuss is moved to StackOverflow.
