### ISSUE TITLE
Make it available on cdnjs.com

### ISSUE THREAD

**Issue by stephenson** [js-cookie/js-cookie#38]
Would be great if js-cookie was available on cdnjs.com, read more here: https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by FagnerMartinsBrack** [comment]
Yeah, I am trying to figure that out: https://github.com/cdnjs/cdnjs/issues/4627

**Comment by stephenson** [comment]
Fantastic!

**Comment by FagnerMartinsBrack** [comment]
@stephenson it seems that issue is not going anywhere. I believe it's ok to add a new project named `js-cookie` in cdnjs. Do you know how to easily add [all tags](https://github.com/js-cookie/js-cookie/releases) to cdnjs without having to send one pull request for each? Do you want to help on this one? :)

**Comment by FagnerMartinsBrack** [comment]
I started a PR to add js-cookie as a new lib: https://github.com/cdnjs/cdnjs/pull/4713

**Comment by FagnerMartinsBrack** [comment]
js-cookie is available on cdnjs: http://cdnjs.com/libraries/js-cookie

**Comment by stephenson** [comment]
Fantastic, thanks!

**Comment by FagnerMartinsBrack** [comment]
I have added CDNJS as a community supported CDN. See https://github.com/js-cookie/js-cookie/wiki/Community-Supported-CDNs/262a9ae0cd09d911b02c3abaf6f3100f00feb530.

**Comment by FagnerMartinsBrack** [comment]
[Added jsDelivr CDN to the README](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-340131636) because now they support on-demand minification.
