### ISSUE TITLE
Facebook browser

### ISSUE THREAD

**Issue by exoer** [js-cookie/js-cookie#380]
Hi. Does js-cookie work in the Facebook browser?
I've tried it on our website. When a user clicks on a link to our site in the facebook app on a phone, it opens in the facebook browser (not Chrome or Safari). Our authentication flow fails on the first attempt in the facebook browser but works on the second attempt. 
I've tried to store the auth token in localstorage and using js-cookie, but it still fails in the Facebook browser.

**Comment by FagnerMartinsBrack** [comment]
If the library works in all other browsers and not in the engine that Facebook users in their mobile app, then it's more likely to be a problem in this order:

1. The code of your application.
2. The Facebook browser engine for their mobile app.
3. js-cookie

Have you made sure the problem is not in your application and in the Facebook browser engine for their mobile app? If so, can you produce a [SSCCE](http://sscce.org/) that fails in Facebook browser along with instructions of how to run it?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
