### ISSUE TITLE
Implement the ES6 Map interface (Generic Programming)

### ISSUE THREAD

**Issue by koraa** [js-cookie/js-cookie#381]
It would be useful if all of the methods of the ES6 map where provided to facilitate generic programmin: The Cookie object could the be used in any place where an es6 map is used…

The interfaces in question are:
```
.size (property)
.clear()
.delete()
.entries()
.forEach()
.has()
.values
The iterator interface.
```

**Comment by FagnerMartinsBrack** [comment]
It's not that simple.

For `.clear()` for example, it would be necessary to store the `attributes` because they are necessary to call `.remove(cookieName, attributes)`. Besides, it would imply that `clear()` (without arguments) clear all the cookies in the browser, which is not the case, it depends on the `path` and `domain`.

You can easily add those methods incrementally by wrapping js-cookie into an adapter:

```javascript
const mapLike = (Cookies) => {
  return {
    clear: () => {
      ...
    },
    delete: () => {
      ...
    },
    entries: () => {
       ...
    }
  };
};
```

Or if you want all of them at once, you can just instantiate a `new Map(...)` in the same adapter.

I'm not sure how that would benefit the library and everybody already using it. Do you have some examples I might be missing of how implementing the same interface as Map can be useful?

**Comment by koraa** [comment]
Well, my generic implementation of setDefault for maps would work for instance:

```coffeescript
# get(Container, Key) -> Any
# get(Key)(Container) -> Any
#
# Retrieve an element from a container in a generic way.
# From plain objects the element will be retrieved as normal
# properties; for any other type the .get method will be used
get = curry [1, 0], (cont, key) ->
  if type(cont) == Object \
    then cont[key] \
    else cont.get(key)

# set(Container, Key, Value) -> Value
# set(Key)(Value)(Container) -> Value
#
# Assign an element in a container in a generic way.
# From plain objects the element will be retrieved as normal
# properties; for any other type the .set method will be used
set = curry [2, 0, 1], (cont, key, value) ->
  if type(cont) == Object \
    then cont[key] = value \
    else cont.set(key, value)
  value

# has(Container, Key) -> Boolean
# has(Key)(Container) -> Boolean
# Retrieve an element from a container in a generic way.
# For plain objects hasOwnProperty will be used, for any other
# container .has() is used.
has = curry [1, 0], (cont, key) ->
  if type(cont) == Object \
    then cont.hasOwnProperty(key) \
    else cont.has(key)

# setDefault(Container, Key, Value) -> void
# setDefault(Key)(Value)(Container) -> void
#
# Default an element in a container in a generic way.
# Internally uses has() and set() and get()
setDefault = curry [2, 0, 1], (cont, key, defau) ->
  if has(cont, key)
    get(cont, key)
  else
    set(cont, key, defau)
    defau
```

Right now I am using the following wrapper (although you are right, it doesn't quite work when parameters come into play…):

```
class Cookie
  constructor: (@_base) ->

  get: (key) -> @_base.get(key)
  set: (key, value, opts) -> @_base.set(key, value, opts); @
  delete: (key) ->
    if @has(key) \
      then @_base.remove(key); true \
      else false
  getter @, 'size', () -> @_base.length

  has: (key) -> @get(key) != undefined

  clear: () ->
    for key from @keys()
      @delete(key)
    @

  @::[Symbol.iterator] = () -> iter @_base.getJSON()
  entries: () -> iter @
  keys: () -> map @, ([key, value]) -> key
  values: () -> map @, ([key, value]) -> value

module.exports = new Cookie(require 'js-cookie')
```

**Comment by FagnerMartinsBrack** [comment]
Why not just instantiating a `new Map` instead of implementing all the methods?

**Comment by koraa** [comment]
Because I need to set cookies using setDefault…

**Comment by FagnerMartinsBrack** [comment]
Why wouldn't that work with `new Map`?

**Comment by koraa** [comment]
Because if I mutate a copy I do not mutate the cookies? I am mutating the copy?

**Comment by koraa** [comment]
Another example is actually copying all the cookies into a map: With the iterator protocol implemented, it is `new Map(Cookies)`, without it, that becomes more complex: 

```
let copy = new Map();
let jsonCookies = Cookies.getJSON();
for (let key in jsonCookies) {
  copy.set(key, jsonCookies[key]); 
}
```

**Comment by FagnerMartinsBrack** [comment]
> Because if I mutate a copy I do not mutate the cookies? I am mutating the copy?

I see, the problem lies on the write operations such as `set`, `delete` and `clear`.

In that case, I guess you're using the wrong data structure. A cookie need `attributes` for the `remove` and the `set`. Write operations don't duck type easily to a `Map` interface and therefore it can't be generalized as such. If you have a use case where `attributes` wouldn't need to be passed, that should probably be specific application code and not generalized into the library.

> With the iterator protocol implemented, it is new Map(Cookies), without it, that becomes more complex:

I don't see how that code is more complex (if you're talking about runtime complexity). You'll have to test the same use cases you would have to test with `new Map(Cookies)`.

The only argument I can see is code style, and that is hard to be taken as an argument to change a library interface.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.
