### ISSUE TITLE
Weird behavior in Edge

### ISSUE THREAD

**Issue by z-vr** [js-cookie/js-cookie#383]
Hi, we're using this module and test our code in many browsers, but Edge is the only one that gives *a lot* of headache.  I monkey-patch `document.cookie` (https://www.gideonpyzer.com/blog/debugging-javascript-by-redefining-properties/) to see what's going on, and added logging. Here's what we get:
```
LOG LOG: '[monkey-patch] GETTING COOKIE: ""'
LOG LOG: '[code] accessing cookies before set: ', ''
LOG LOG: '[code] setting cookies', 'person-names', ['my-name']
LOG LOG: '[monkey-patch] SETTING COOKIE: "person-names=[%22my-name%22]; path=/; expires=Wed, 28 Nov 2018 11:39:05 GMT"'
LOG LOG: '[code] cookies have been set:', 'person-names=[%22my-name%22]; path=/; expires=Wed, 28 Nov 2018 11:39:05 GMT'
LOG LOG: '[monkey-patch] GETTING COOKIE: "person-names=[%22my-name%22]"'
LOG LOG: '[code] accessing cookies right after setting: ', 'person-names=[%22my-name%22]'
LOG LOG: '[code] JSCookie.getJSON', 'person-names'
LOG LOG: '[monkey-patch] GETTING COOKIE: ""'
```

![ok then](https://scontent-sea1-1.cdninstagram.com/t51.2885-15/e35/14276426_935708443202271_1413435729_n.jpg?ig_cache_key=MTMzOTM3NjM0ODA4MjIxMDg5Nw%3D%3D.2)

```js
function setCookie(COOKIE_NAME, newCookie, options) {
    console.log('[code] accessing cookies before set: ', document.cookie);
    console.log('[code] setting cookies', COOKIE_NAME, newCookies);
    const res = Cookies.set(COOKIE_NAME, newCookies, options);
    console.log('[code] cookies have been set:', res);
    console.log('[code] accessing cookies right after setting: ', document.cookie);
}
```

```js
// either sync or async this function does not work
async function getCookie(COOKIE_NAME, delay = 50) {
    await new Promise(resolve => setTimeout(resolve, delay));
    console.log('[code] JSCookie.getJSON', COOKIE_NAME);
    return JSCookie.getJSON(COOKIE_NAME);
}
```

```js
// test
it('should create cookies and append name on check', async () => {
    const checkBox = el.querySelector('input');
    fireEvent(checkBox, 'click'); // this triggers setCookie
    const cookies = await getCookie(COOKIE_NAME);
    expect(cookies).to.eql([personName]);
});
```

The behaviour is inconsistent in a way that it can pass or fail 😢  It's Edge 12-16 which has always been the problem. Could it be because of how it writes cookies to disk / threads sync?

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
