### ISSUE TITLE
fails removing cookie with path

### ISSUE THREAD

**Issue by enricjaen** [js-cookie/js-cookie#384]
When the cookie contains a path the library doesn't removes it but creates another cookie with path "/"

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

Can you provide a failing example attached to this issue as a ZIP file that we can run using a static server like [node-static](https://github.com/cloudhead/node-static)?

Thanks!

**Comment by lauterry** [comment]
Any news on this issue ?

**Comment by FagnerMartinsBrack** [comment]
@lauterry It looks like @enricjaen forgot about this issue.

Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again
