### ISSUE TITLE
[Request] Implement .get(cookieName, cookieDomain)

### ISSUE THREAD

**Issue by mtage70** [js-cookie/js-cookie#388]
It would be really helpful if I could include the specific domain of the cookie I'm attempting to get. This avoids confusing situations where you might have several cookies from subdomains, with the same name, but you want to get one with a specific domain value.

**Comment by FagnerMartinsBrack** [comment]
Can you show an example of how that can be done using `document.cookie`? The browser doesn't  allow you to get the cookie value form another domain because that would represent an obvious security risk.

**Comment by mtage70** [comment]
@FagnerMartinsBrack not necessarily for getting a cookie from a different domain entirely, but from getting a cookie from a specific sub-domain. For example you may have a site, 'www.mysite.com' where you set a cookie called 'mycookie', and it gets the domain value of '.mysite.com'. Now let's say you had a QA environment for that site, 'qa.mysite.com' where you also set a cookie called 'mycookie', and lets say you gave it the domain value of '.qa.mysite.com'. Now, when you are browsing qa.mysite.com you have two cookies named 'mycookie' but one has the domain '.mysite.com' and one has the domain '.qa.mysite.com'.
I'm saying it would be really great to be able to say ".get('mycookie', '.qa.mysite.com')" to specifically get the cookie set on the QA site, right now it seems like it's just a toss up, which of the two cookies is chosen by a get. This probably will come up for organization who have internal staging environments.

**Comment by FagnerMartinsBrack** [comment]
Alright.

Can you tell me exactly what's the `document.cookie` (write mode) default behavior? If you have two cookies with the same name on `qa.domain.com` and `domain.com` which one is going to be chosen by `document.cookie` (read mode) when you're running the script on `qa.domain.com` or `domain.com`? I assume that it would be the right one?

Or does one shadow the other? There's [an open task](https://github.com/js-cookie/js-cookie/issues/226) to investigate the behavior of cookies shadowing one another and this might help lighten that up.

One way to manually test all this is to change the host file of your system so that you point `qa.domain.com` and `domain.com` to `localhost` and have a [static server](https://github.com/cloudhead/node-static) setting and reading the cookie. The browser will think you're accessing a real server on `domain.com`, although it's local.

Once we have enough information of how this works, then we can decide whether it's possible or even if it makes sense to add a new API or not.

**Comment by FagnerMartinsBrack** [comment]
Ping @mtage70

**Comment by mtage70** [comment]
I'll double check today, but from what I've observed so far it looks like the cookie with the domain that comes first alphabetically is selected.

**Comment by FagnerMartinsBrack** [comment]
@mtage70 any news on this?

**Comment by mtage70** [comment]
Apologies, only getting back to this today. I did some testing and as far as I can tell what I said is correct, the cookie with the domain that comes first alphabetically is used.

**Comment by FagnerMartinsBrack** [comment]
Cool @mtage70! Can you attach the test case you used? Did you use a static server?

**Comment by carhartl** [comment]
>the cookie with the domain that comes first alphabetically is used

Did you test that with a particular browser, or more than one?

**Comment by carhartl** [comment]
If you would want to read a (eventually shadowed) cookie from a subdomain, you could maybe create an iframe on the fly with its source pointing to that subdomain, read the desired cookie from within that iframe and pass the value to the parent window. But that all sounds like there were other security restrictions in place preventing you from doing this (iframe).

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by theblang** [comment]
FWIW, I think it'd be impossible to do this. As a test, go set two identically named cookies, one **with** and one **without** a `domain` attribute. You'll notice them both in the devtools (the one with `domain` explicitly set will have a leading dot), but the value of `document.cookies` does not expose the attributes: `"test-cookie=test%20value%201611156776342; test-cookie=test%20value%201611156799243"`.
