### ISSUE TITLE
Altering User Experience using Cookies

### ISSUE THREAD

**Issue by vilav** [js-cookie/js-cookie#389]
Hello

I'm new to JS hence the noob questions:

Is there a way to have a periodic setting / resetting of cookies such that every other week, based on how often the user visits a website, they're shown or not show a specific DIV?

For example: if a user has been visiting a website atleast once a day for 1 week, then you can show them a newsletter subscription form. If they haven't fulfilled the condition, then they don't see it. 

This is one use case, but you can imagine the creation of a more modular system where DIVs can have a HTML data-* attribute (ex: data-cookie=1w / data-cookie=1m) applied such that they auto-show / hide based on a certain defined cookie setting?

Is this sort of thing possible to approach with js-cookie?

**Comment by MagicMarvMan** [comment]
I think you are in the wrong place with this question.

An issue is not a question, but a "feature request" a "bug report" or similar.

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
