### ISSUE TITLE
Temporary CDN

### ISSUE THREAD

**Issue by alexbooker** [js-cookie/js-cookie#39]
Yo. 

You mention not to reference [http://raw.github.com](http://raw.github.com) but did you know there is a "cdn" sub-domain that works in production? 

See: https://cdn.rawgit.com/js-cookie/js-cookie/master/src/js.cookie.js.

It could be nice to mention this in [README.md](https://github.com/js-cookie/js-cookie/blob/master/README.md) until you sort out #38. 

I am still going to use Bower. But when experimenting on [CodePen](http://codepen.io/alexbooker/pen/bdpKzR) - where Bower is not an option - it is handy to have a hosted solution to reference.

**Comment by FagnerMartinsBrack** [comment]
Didn't know about `rawgit.com`. Pretty interesting.

I wouldn't encourage to use the master branch though, one should use the version from a specific release tag to revalidate the offline cache in the client when updating the script to a newer version: https://cdn.rawgit.com/js-cookie/js-cookie/v2.0.0-beta.1/src/js.cookie.js

The only problem with that service is that nothing is ensured since it reads from the source, and the script is not minified, but still a good fit for a cdn workaround.

It would be very nice if the service could deliver from the downloads page, but it fails to do so =(: https://github.com/js-cookie/js-cookie/releases/download/v2.0.0-beta.1/js.cookie-2.0.0-beta.1.min.js

I created an issue about that: https://github.com/rgrove/rawgit/issues/66

**Comment by alexbooker** [comment]
Mhm. There is no reason not to reference a specific commit or tag. 

This is merely temporary work-around until #38 is closed. It is not ideal.

Should we keep this issue open for visibility?

**Comment by FagnerMartinsBrack** [comment]
> There is no reason not to reference a specific commit or tag.

It would be handy for testing, but not in production. The release is the point of ensurance of stable and supported code, if somebody loads a specific commit and another commit reverts or breaks something, then nobody will notice, since the developer might not have knowledge of the project's internals.

We reserve the right to break or revert code in the master branch without any notice.

> Should we keep this issue open for visibility?

I would leave it open for a while to see if rawgit has something to say about the downloads page.

**Comment by FagnerMartinsBrack** [comment]
> There is no reason not to reference a specific commit or tag.

It would be handy for testing, but not in production. The release is the point of ensurance of stable and supported code, if somebody loads a specific commit and another commit reverts or breaks something, then nobody will notice, since the developer might not have knowledge of the project's internals.

We reserve the right to break or revert code in the master branch without any notice.

> Should we keep this issue open for visibility?

I would leave it open for a while to see if rawgit has something to say about the downloads page.

If it takes too long, then we might temporarily document the unminified file using the releases link and replace to CDNJS later.

@carhartl ?

**Comment by carhartl** [comment]
I would refrain promoting solutions that are meant to be used as a temporary solution. Because people will use them anyway and it will cause them problems. 

I don't understand why we aren't creating a new project on cdnjs? Why do we need to redirect/rename? What is going to happen with the old jquery-cookie reference?

**Comment by FagnerMartinsBrack** [comment]
> I would refrain from promoting solutions that are meant to be used as a temporary. Because people will use them anyway and it will cause them problems.

I kind of agree, rawgit might not cause any problems, but promoting something to take it back later really doesn't seems to be a good move.

> I don't understand why we aren't creating a new project on cdnjs?

There's no actual problem in creating a new project in cdnjs, I just asked for them if there's a better recommendation on what to do in cases where the repository is renamed but the old one is still on.

> Why do we need to redirect/rename? 

They could have some message in the site saying something like "this project was moved to js-cookie" like [what NPM does to make people aware](https://docs.npmjs.com/cli/deprecate). Or maybe there's another routine that I don't know of, like exposing only the versions not available in the old repo.

> What is going to happen with the old jquery-cookie reference?

That's my question too, I have no idea what cdnjs recommend in these cases.

**Comment by FagnerMartinsBrack** [comment]
js-cookie is not on cdnjs, I will be closing this in favor of #46

**Comment by alexbooker** [comment]
:+1:

**Comment by FagnerMartinsBrack** [comment]
[Added jsDelivr CDN to the README](https://github.com/js-cookie/js-cookie/pull/371#issuecomment-340131636) because now they support on-demand minification.
