### ISSUE TITLE
js-cookie code that works for Windows and Android not working on iOS devices

### ISSUE THREAD

**Issue by chundhau** [js-cookie/js-cookie#392]
Please see this question on Stack Overflow:

https://stackoverflow.com/questions/47893743/js-cookie-library-working-on-android-but-not-ios-devices

**Comment by s1awa** [comment]
Experienced same issue today. First I thought it is a problem with unofficial parameter `SameSite: 'strict'`.

**Comment by FagnerMartinsBrack** [comment]
Thanks, @chundhau. I'll close this for now and move the discussion to StackOverflow until we have something actionable to do.

**Comment by aderpio** [comment]
FYI: I encountered the same situation where js-cookie was not working only on my iOS but behaving on Android and desktop. However, it only started happening at some point so I traced back what had been modified and I noticed that the culprit was one function written with default parameters, something which is OK since ES6/ES2015 but my iPhone was still on iOS9 which is, I believe, ES5 only.

`
function(arg1, arg2='') { }
`
Changing the function code solved it. I presume iOS 10+ has no issue with this.

**Comment by aderpio** [comment]
Not in jscookie's code. In my code before calling set or read cookie.

**Comment by FagnerMartinsBrack** [comment]
@aderpio If it's not a js-cookie problem you should probably post on the [StackOverflow thread linked above](https://stackoverflow.com/questions/47893743/js-cookie-library-working-on-android-but-not-ios-devices) until we have something actionable to do.
