### ISSUE TITLE
Cannot use js-cookie with Angular 5

### ISSUE THREAD

**Issue by elliotykim** [js-cookie/js-cookie#395]
I installed js-cookie with types:
`npm install --save js-cookie @types/js-cookie`

Here's the file where I'm trying to use it:
```
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';

import * as Cookie from 'js-cookie';

@Injectable()
export class AuthGuard implements CanActivate {

  constructor(private router: Router) { }

  canActivate() {
    debugger;
    if (Cookie.get('signedin')) {
      return true;
    }

    this.router.navigate(['/signin']);
    return false;
  }
}
```

![screen shot 2017-12-30 at 12 33 43 am](https://user-images.githubusercontent.com/301072/34449499-1d3f9b38-ecf9-11e7-8076-69ca00ca7a59.png)

Any ideas what I could be doing wrong? I'm able to import and use lodash with the same pattern.

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by bandhavya** [comment]
any update on this ?
It is not working for me too

**Comment by FagnerMartinsBrack** [comment]
@bandhavya, the package `@types/js-cookie` belongs to https://github.com/DefinitelyTyped/DefinitelyTyped. See https://www.npmjs.com/package/@types/js-cookie.

If you have further questions, try to create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie)
