### ISSUE TITLE
Internet Explorer 11 (Windows 7) - Cookies do not save

### ISSUE THREAD

**Issue by thediamondstore** [js-cookie/js-cookie#397]
Hi,

We are using js-cookie and it works fine on Chrome and Firefox et al, but on IE 11 it is not working at all. The cookies are just not created. Has anyone got any advice for IE 11? I have read the IE 11 FAQs, but it doesn't relate to my problem. Part of the issue is not being able to see the cookies in IE. I have installed the mzcv cookie viewer, but even that seems not to see the cookies.  Any help appreciated.

Regards,
Jon

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by thediamondstore** [comment]
Thanks for the reply. Do you have a test page where I can js-cookie in my browser (IE 11)? That would allow me to see in an instant if my IE 11 is the problem.
