### ISSUE TITLE
Cookies.get(undefined) returns all cookies

### ISSUE THREAD

**Issue by sammok** [js-cookie/js-cookie#399]
Dear developer,

When I use `Cookies.get()` method, I passing a undefined variable as a parameter into `get` method,

bug returns all cookies, 

I think, `Cookie.get()` method should checking the arguments length, if `arguments.length > 0`, this method shouldn't returns all the cookies, returns undefined would be better.

Test Case:
```` javascript
console.log(Cookies.get(), Cookies.get(undefined), Cookies.get(null))
output: {}, {}, {}
````
expect
```` javascript
console.log(Cookies.get(), Cookies.get(undefined), Cookies.get(null))
output: {}, undefined, undefined
````

**Comment by FagnerMartinsBrack** [comment]
`Cookies.get(undefined)` is not documented. Why are you using the API like that? Can you show some examples?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). If you want to continue the discussion, please comment here mentioning one of the project members.

**Comment by jackocnr** [comment]
Hi there, I've recently hit a related issue - if I have the cookie name in a variable, and in some situations I need to be able to handle where that variable is not set, or it has a default value like null or empty string, in those cases it makes more sense to me for `get` to return null instead of all of the cookies. As the op says, if I pass in a value, then I think it shows an intent to fetch a particular cookie, and certainly not all of the cookies.

Honestly it just feels dangerous to use the same `get` method for two completely different use cases, to retrieve two different data types. I would favour `get` always being to get a particular cookie, and having some new method e.g. `getAll` if you want to get all cookies, to make it explicit. What do you think?

**Comment by FagnerMartinsBrack** [comment]
Opening due to @jackocnr feedback. In this case, we should be doing `if arguments.length > 0`. Similar problem as of https://github.com/carhartl/jquery-cookie/issues/308/

@jackocnr do you want to create a test and PR for this?

**Comment by jackocnr** [comment]
Thanks for your response. I'm very busy at the mo, but I might be able to take a look one weekend if I find the time.

**Comment by FagnerMartinsBrack** [comment]
Sure @jackocnr feel free to take the time it takes :)

**Comment by FagnerMartinsBrack** [comment]
@jackocnr any news on this?

**Comment by jackocnr** [comment]
Nope. It's still on my list, but I haven't found the time yet.

**Comment by carhartl** [comment]
I believe we can change 

```javascript
return key ? jar[key] : jar
```

to 

```javascript
return arguments.length >= 1 ? jar[key] : jar
```

Will tackle this later..

**Comment by carhartl** [comment]
Ha, that would have worked if it was not for `getJSON()`...

**Comment by FagnerMartinsBrack** [comment]
@carhartl Is it time to dump `getJSON` either in favor of people doing `JSON.stringify(Cookies.get('name'))`, `Cookies.get('name', JSON.parse(value))`? I don't see a valid point in encouraging things like `Cookies.getJSON().a.foo.bar` -> If one level of JSON is removed from the store, the app crashes.

**Comment by carhartl** [comment]
>Is it time to dump getJSON

I didn't even think of that.. open a ticket and try to gather some thoughts?

**Comment by FagnerMartinsBrack** [comment]
@carhartl https://github.com/js-cookie/js-cookie/issues/540
