### ISSUE TITLE
Modularize library?

### ISSUE THREAD

**Issue by carhartl** [js-cookie/js-cookie#405]
While working with the code I realized it might be nice to modularize the library (read - write). This would allow specialized and smaller builds for someone who would only need the write functionality for instance.

Not sure whether there's a real world need for this.

**Comment by FagnerMartinsBrack** [comment]
It's a sensible suggestion. However, it may require a lot of work and it will add complexity to the build which is already very complex.

We also need to verify the use cases for this and see if it's worth the investment in effort.

Anyway, even if it's indeed something we want to do, I would suggest [adding a bullet point](https://github.com/js-cookie/js-cookie/issues/57).

**Comment by tbillington** [comment]
@FagnerMartinsBrack I don't know if I'm missing something but it doesn't look like this library has a build step...?

**Comment by FagnerMartinsBrack** [comment]
@tbillington It does sort of. See [here](https://github.com/js-cookie/js-cookie/blob/8b2a8801cc53fe9e150ef41c5c79d1193c79a385/Gruntfile.js#L80).

**Comment by FagnerMartinsBrack** [comment]
I have [this project](https://github.com/js-cookie/js-cookie-release) that's been in development for a while to address most of https://github.com/js-cookie/js-cookie/issues/57. I couldn't get enough time to finish it.

**Comment by tbillington** [comment]
@FagnerMartinsBrack I don't know how much you know about how recent bundlers work, [here's an example](https://rollupjs.org/repl?version=0.57.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGdldCUyQyUyMHNldCUyMCU3RCUyMGZyb20lMjAnLiUyRmpzLWNvb2tpZS5qcyclM0IlNUNuJTVDbmNvbnNvbGUubG9nKCUyMGdldCglNUMlMjJmb28lNUMlMjIpJTIwKSUzQiUyMCUyRiUyRiUyMDUlNUNuJTJGJTJGJTIwc2V0KCU1QyUyMmJhciU1QyUyMiUyQyUyMCU1QyUyMjEwJTVDJTIyKSUzQiUyMCUyRiUyRiUyMCUzQy0lMjBVbmNvbW1lbnQlMjBtZSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJqcy1jb29raWUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwanMtY29va2llJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGdldCUyMCglMjBuYW1lJTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwJTJGKmdldCUyMGNvb2tpZSolMkYlMjAlNUMlMjI1JTVDJTIyJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBzZXQlMjAoJTIwbmFtZSUyQyUyMHZhbHVlJTIwKSUyMCU3QiU1Q24lNUN0ZG9jdW1lbnQuY29va2llJTIwJTNEJTIwdmFsdWUlM0IlNUNuJTVDdCUyRipzZXRzJTIwY29va2llKiUyRiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwcmVtb3ZlJTIwKCUyMG5hbWUlMjApJTIwJTdCJTVDbiU1Q3QlMkYqJTIwcmVtb3ZlcyUyMGNvb2tpZSUyMColMkYlNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) of a mock "modularised" version of js-cookie and how using only what you need can save you space in the final bundle.

These work by specifying a "module" field in your package.json which recent bundlers (webpack, rollup, etc) will look for, so older bundlers will continue to work because they look for the "main" field.

**Comment by FagnerMartinsBrack** [comment]
@tbillington I haven't worked with any bundling tool recently. It would be nice to have a PR with a couple of ideas.

If anyone is keen to own this, I'd suggest avoiding to include too much "magic" dependencies that do a lot of stuff. We could try to keep them isolated from the build process as much as we can so that they can be easily replaced by something else.

It would be awesome if we could create a custom [interface](https://codeburst.io/why-do-you-need-to-know-interface-fundamentals-a129ac6ab0c3) with tests that facilitate refactoring the code that does the bundling.

However, if you can use a library that can be easily replaced, that should be ok too...

**Comment by tbillington** [comment]
Traditionally tools have been run by invoking their executable, eg `grunt build` or `browserify`. A common theme of more recent packages has been to move these implementation specific commands into the scripts in `package.json` so that in your project you type `npm run build` or `npm run test`. This means that even if the bundler/builder/thing is swapped out, the command remains the same and if the output is the same location/name no one will be impacted.

**Comment by FagnerMartinsBrack** [comment]
> A common theme of more recent packages has been to move these implementation specific commands into the scripts in package.json

@tbillington That is a discussion that has come back and forth since NodeJS came out in 2009.

In that case, if you use npm scripts you're still tied to npm.

Besides, using `package.json` scripts become unmanageable once things start to grow and you have to call scripts to "reuse" existing commands inside other commands. That becomes a mess because you can't ensure, through testing, that each of those commands is working correctly so it's very likely that they're going to break and you'll only notice later or when you want to run them for development.

Swapping a bundler may not be easy when using npm scripts. If you want to replace the bundler later without rewriting everything, you will have to find one that matches exactly the responsibility of each of the "scripts" you already have, otherwise you'll have to change them to accommodate the new bundler which has the same effort as rebuilding everything all over again.

Since they're not tested, you will also have to manually test that the existing build logic is unchanged.

Also, commands such as `build` or `test` are too broad and tend to have too many responsibilities, which impact maintainability and long-term sustainability.

What I meant by "create a custom interface with tests that facilitate refactoring the code that does the bundling" is the exact opposite of using npm scripts. It should allow refactoring, which means [not to change the interface](https://blog.cloudboost.io/how-to-refactor-a-public-interface-317ed18d38a3), things npm scripts can't do. That means using tests to drive the creation of the code and replace the resulting source with libraries.

**Comment by FagnerMartinsBrack** [comment]
@carhartl Reflecting in hindsight, I don't think we have enough evidence for a real-world use case for this. If we see that the lib is getting bigger we might consider. At the moment, though, it doesn't seem useful. We would rather focus on BrowserStack tests and all that.

What do you think?
