### ISSUE TITLE
SyntaxError: import not found: default (js.cookie-2.2.0.min.js)

### ISSUE THREAD

**Issue by Darker** [js-cookie/js-cookie#407]
This is what is stated as valid import syntax in documentation:

```
import Cookies from 'js-cookie';
```
But that does produce following error:

```
SyntaxError: import not found: default
```
In the following code:

```
import Cookies from "./lib/js.cookie-2.2.0.min.js";
```
What is the correct usage?

**Comment by PerfectlyNormal** [comment]
I got it working by using `import * as Cookies from 'js-cookie'`

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by Darker** [comment]
Are you kidding me? You need MCVE to reproduce error caused by one line of code? Like if you don't give a damn, just say it.

**Comment by FagnerMartinsBrack** [comment]
AFAIK browsers don't support ES 6 modules and you need a transpiler to make it work. That means it's not one line of code and there's a lot of assumptions about what you're saying here: which transpiler you're using, which version that is, what's your config, etc.

Did anything changed? Does browsers support ES 6 now without the need for a transpiler?

**Comment by FagnerMartinsBrack** [comment]
Ping @Darker.

**Comment by Darker** [comment]
Yeah, browsers do support ES6 modules. Not all, and some need you to enable it in dev options first, but it works. See my stackoverflow asnwer: https://stackoverflow.com/a/46415925/607407

Some libraries already support ES6 modules in browser too, such as EventEmitter2:

```
import EventEmitter from "../lib/event-emitter.js";
```
Since JSCookie says in the docs that it supports ES6 modules - and it didn't work for me, I reported that as an issue. Fix might be as simple as adding an example import code in documentation.

**Comment by FagnerMartinsBrack** [comment]
Alright, does @PerfectlyNormal's answer work? If that's so, can you create a PR to update the docs? Also, how can js-cookie support ES6 modules in a better way conscious of backward compatibility?

**Comment by FagnerMartinsBrack** [comment]
> can you create a PR to update the docs?

Might be worth a hyperlink to some website that can show the browser support over time.

**Comment by Darker** [comment]
I'll test it ASAP and if it works, I'll create PR with docs update.

**Comment by FagnerMartinsBrack** [comment]
@Darker any updates on this one?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af). Feel free to comment here to open up the discussion again.

I've created https://github.com/js-cookie/js-cookie/issues/423 to track it.
