### ISSUE TITLE
TypeError: Cookies.set is not a function

### ISSUE THREAD

**Issue by gogoIsComing** [js-cookie/js-cookie#427]
hey guys : 
when i use my Cookies.set( ) function in order to add a new cookie to my page i get this error message : 
![1](https://user-images.githubusercontent.com/33967218/38422560-e25b09dc-39b3-11e8-9c9b-020f650a363c.png)

my HTML code : 
![2](https://user-images.githubusercontent.com/33967218/38422578-f1dc87aa-39b3-11e8-9780-39143c1a285c.png)

my  JS code : 
![3](https://user-images.githubusercontent.com/33967218/38422583-f9f7da34-39b3-11e8-9498-150ccdeb5fd3.png)

Any Help :) 

@FagnerMartinsBrack

**Comment by FagnerMartinsBrack** [comment]
Hi @gogoIsComing, thanks for opening an issue on js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!

**Comment by FagnerMartinsBrack** [comment]
Probably the same problem as https://github.com/js-cookie/js-cookie/issues/423. Closing in favor of https://github.com/js-cookie/js-cookie/issues/423.
