### ISSUE TITLE
[javascript] Cookies

### ISSUE THREAD

**Issue by hoduckhoa** [js-cookie/js-cookie#452]
**creates 2 cookies on request**
+ Cookie 1 for 30 seconds and check that this cookie is alive? If you still see the modal message "Please wait [time countdown] to continue comment"
+ Cookie 2: to save the email + full name of the user comment (if not, then create this new cookie, if it exists then use the saved information)
You have not figured out, so the code is not correct, can contribute to your own
**I only do step 1,**
**help me step2**

```
function setCookie(cname,cvalue,exdays) {
         var d = new Date();
          d.setTime(d.getTime() + (exdays*60*1000));
         var expires = "expires=" + d.toGMTString();
          document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
     }
 
   function getCookie(cname) {
       var name = cname + "=";
       var decodedCookie = decodeURIComponent(document.cookie);
       var ca = decodedCookie.split(';');
       for(var i = 0; i < ca.length; i++) {
           var c = ca[i];
           while (c.charAt(0) == ' ') {
               c = c.substring(1);
           }
           if (c.indexOf(name) == 0) {
               return c.substring(name.length, c.length);
           }
       }
       return "";
   }   
```
 
       function checkCookie() {      
 
          var user=getCookie("username");
           if (user != "") {
               alert("Vui long cho trong giay lat " + user);
              
 
 
           } else {
              user = prompt("Vui long nhap ten:","");
 
              if (user != "" && user != null) {
                  setCookie("username", user,0.5 );
              }
              else{
 
              }
           }         
           
       }

**Comment by FagnerMartinsBrack** [comment]
Hi, thanks for opening an issue on js-cookie.

As stated in the [contributing guidelines](https://github.com/js-cookie/js-cookie/blob/caa594ca966c967a8b72a317eddf446e5094caa8/CONTRIBUTING.md#issues), in order to take any further action we need a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) that shows a problem with js-cookie.

For support, you can create a question in [StackOverflow](http://stackoverflow.com/questions/ask) under the tag [`js-cookie`](http://stackoverflow.com/questions/tagged/js-cookie). The reason why we don't answer support questions on Github is that StackOverflow has a higher relevance in Google results and therefore a solution posted there is more likely to help other people with the same problem 😃 .

Closing for now, but once there's enough information that we can act upon just comment here so that we can reopen it.

If you create a StackOverflow question, please link it here so that we can help here or make it possible for others to find the answer. If you find a solution for your problem, please post it here too so that we can potentially improve the docs.

Don't let this stop you from keep contributing to js-cookie 👍 

Thank you!
