### ISSUE TITLE
Dist filename with dots

### ISSUE THREAD

**Issue by notsure** [js-cookie/js-cookie#49]
Hi, 

I am using come grunt copy tasks to move files from plugins installed via bower to a public folder. the reason is simple, I try to avoid too many unneeded files on my server. Now here is the thing, as some of those tasks, like grunt copy, have to move or compile files a dot-seperated filename is causing errors. 

current filename is: `js.cookie.js` and it would be nice if its name would be `js-cookie.js`

cheers.

**Comment by FagnerMartinsBrack** [comment]
Which error does it cause? Shouldn't that be reported as an issue for the tool you are using?

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the [OP](http://netforbeginners.about.com/od/internetlanguage/f/What-Is-OP.htm). Problems regarding other tools should be reported and fixed in their respective repositories.

Note:
I managed to find a comment in a related issue that might be useful:

> use grunt-contrib-copy plugin. that's the new version and the bug is fixed. the grunt-copy plugin is deprecated

-- https://github.com/gruntjs/grunt-contrib-copy/issues/223#issuecomment-105509705

**Comment by notsure** [comment]
Sorry I've been abroad. Yes you are totally right, and thanks for your engagement!
