### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by pmcalabrese** [js-cookie/js-cookie#50]
Would be very nice to have Typescript Definition added to this repo https://github.com/borisyankov/DefinitelyTyped

**Comment by FagnerMartinsBrack** [comment]
Is that a different syntax that compiles to Javascript, like coffeescript?

**Comment by FagnerMartinsBrack** [comment]
It seems this is to enable typing in JS using TypeScript. I see [`jquery.cookie` has definitions published there](https://github.com/borisyankov/DefinitelyTyped/tree/master/jquery.cookie), maybe some of the [past commiters](https://github.com/borisyankov/DefinitelyTyped/commits/faff1866df10486a4c50904236183edc62ca841e/jquery.cookie/jquery.cookie.d.ts) would be willing to help on this? I have no idea how it works.

@RoyGoode, @NN---, @hiradimir, @theodorejb

**Comment by pmcalabrese** [comment]
@FagnerMartinsBrack Yes it's a language that gets compiled to JS. I would say that the main goal of the typedefinition is to help the developer to have type check during the design phase (plus autocompletion). So us (developer) should not go check the doc that often. It's not a need since the api are few, but would be nice to have.

**Comment by FagnerMartinsBrack** [comment]
@pmcalabrese thanks for the explanation.

I don't use that tool and I believe @carhartl doesn't use either. Since you seems to be most interested party in this matter and the implementation doesn't need any changes in this repository, would you like submitting a TypeScript Definition named `js-cookie` there?

We don't expect any API changes after version 2, `jquery-cookie` 1.x API will stay frozen in both repositories. It makes sense creating a new project under the `js-cookie` containing the new API `Cookies`.

The versions [1.5.0](https://github.com/js-cookie/js-cookie/releases/tag/v1.5.0) and [1.5.1](https://github.com/js-cookie/js-cookie/releases/tag/v1.5.1) are published only in this repository and still supports `$.cookie`, in that case it makes sense to create a definition of both `$.cookie` and `Cookies`, so ppl can update the project without having to rewrite where the cookies are being used (the rewrite is only required when upgrading to version 2).

**Comment by theodorejb** [comment]
Last night I created an initial definition file for js-cookie 2.0: https://github.com/theodorejb/DefinitelyTyped/tree/add-js-cookie-definitions/js-cookie.

I'm not sure whether it would make more sense to keep the jquery.cookie definitions separate, or try to merge the two together with js-cookie 1.5.x support.

**Comment by FagnerMartinsBrack** [comment]
@theodorejb Thanks! :smiley: 

> I'm not sure whether it would make more sense to keep the jquery.cookie definitions separate, or try to merge the two together with js-cookie 1.5.x support.

We had the same issue when deciding how to include it in cdnjs ([see the discussion](https://github.com/cdnjs/cdnjs/issues/4627)). The result was that I added only the versions 1.5.0, 1.5.1 and 2.0.0 to the CDN.

**Comment by FagnerMartinsBrack** [comment]
What happens is that `jquery.cookie` is widely used and many people/tools depend upon its API. This issue make that point clear.

@carhartl pointed out [here](https://github.com/carhartl/jquery-cookie/commit/636c27d72cc1e4eec53fade4f74f4b35570cd6b8#commitcomment-11127418):

> According to the plans js-cookie is/will become rather different compared to jquery-cookie, the former only building on the latter. To simply make jQuery Cookie vanish (and moving everyone to the new library) didn't seem to be the right thing to me when we made the decision

I believe the best strategy for TypeScript and similar would be to create a new library under the name `js-cookie`. Then, if possible (and only if possible), include the versions 1.5.x to enable people to migrate from `jquery.cookie` to `js-cookie` while maintaining backwards compatibility, since the versions 1.5.x still works under the `$.cookie` namespace (but if it's not possible, just include 2.0 and onwards).

**Comment by pmcalabrese** [comment]
@theodorejb fantastic!

**Comment by theodorejb** [comment]
@FagnerMartinsBrack Thanks for the feedback!

I've thought about this some more, and I think it would be best to keep the jquery.cookie definitions separate from those for js-cookie, for the following reasons:

1. Many people already depend on jquery.cookie, and moving those definitions to a new location could cause unnecessary confusion/breakage.
2. Including the jquery.cookie definitions with js-cookie would introduce a hard dependency on the jQuery TypeScript definitions, even for those who don't use/want jQuery.
3. Keeping the definitions separate still allows users to gradually migrate to js-cookie, as both definition files can be easily included until the transition is complete.

I'm planning to wait until the stable release of js-cookie 2.0 is available before making a pull request to add the js-cookie definitions to DefinitelyTyped. In the meantime, feel free to use the definitions in my branch I linked to above, and let me know if you run into any issues.

**Comment by FagnerMartinsBrack** [comment]
> I'm planning to wait until the stable release of js-cookie 2.0 is available before making a pull request to add the js-cookie definitions to DefinitelyTyped.

@theodorejb 
js-cookie version 2 [is out](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0)! :smiley:

**Comment by pmcalabrese** [comment]
Thank you! Appreciated!
