### ISSUE TITLE
Please provide a compressed package of es6's module syntax in NPM.

### ISSUE THREAD

**Issue by zhangchenglin** [js-cookie/js-cookie#501]
Not everyone will choose a CDN.

**Comment by FagnerMartinsBrack** [comment]
@zhangchenglin or anybody else coming to this issue: Do you have a suggestion in how we can easily provide a minified version with the least amount of code and effort in the current codebase?

To give some context I had the plan to create a release process but eventually dropped that because it was consuming too much of my time.

Please read this for context: https://github.com/js-cookie/js-cookie/issues/57#issuecomment-450299638

Ping the upvoters: @erralb @muuvmuuv @Chmylov @aleqsio @ValterJunior @akkis @lloydjatkinson

**Comment by muuvmuuv** [comment]
@FagnerMartinsBrack for most of my project I use [Rollup](https://rollupjs.org/), see: https://github.com/muuvmuuv/vanilla-click-outside

It is easy to set up and does this job very well.

**Comment by carhartl** [comment]
I’m planning to provide this library as an ES module with a fully modernized v3 release.

**Comment by carhartl** [comment]
With #539 in place, as soon as we release the next version, the release will contain a minified version.

**Comment by carhartl** [comment]
We've released version 3 beta, and the package comes with minified versions, for instance via jsdelivr:

https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js

There's a ES module variant as well:

https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.mjs

**Comment by FagnerMartinsBrack** [comment]
@carhartl I added this last line to the release:

> From < 900 bytes gzipped to < 800 bytes gzipped
