### ISSUE TITLE
JSON Object value - unwanted "{%22foo%22:%22bar2%22}"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [js-cookie/js-cookie#509]
**This:**
 ` Cookies.set('name', { foo: 'bar' });`

**Create cockie with this value:**
`
{%22foo%22:%22bar2%22}`

Instead of this:
```
{'foo': 'bar}`
```
**"The Problem"** --> Cookie output is not readable. 

Related (Without any solution):
https://github.com/js-cookie/js-cookie/issues/480

**Comment by carhartl** [comment]
If you retrieve the cookie via `Cookie.getJSON('name')`, what do you get? A properly parsed object equal to the original input?

I believe you shouldn’t be concerned about the internal representation.

**Comment by carhartl** [comment]
A possible workaround would be to specify your own default encoder and `JSON.stringify()` values yourself. This should give you the desired persisted output. 

See https://github.com/js-cookie/js-cookie/blob/master/README.md

**Comment by Ezra-Siton-UIX** [comment]
I will try - but anyway life will be easier if by default the output will be without `%22` :(

**Comment by carhartl** [comment]
> but anyway life will be easier if by default the output will be without

Not necessarily. We need to respect https://tools.ietf.org/html/rfc6265#section-4.1.1

**Comment by carhartl** [comment]
> Also no examples for this issue (Only placeholder code).

Could you give an example what you expected to see as an example?

**Comment by Ezra-Siton-UIX** [comment]
I want to "get rid" from the %22. 
`{foo: bar}`
When I work with "regular" JS the value is "OK":
```
<script>
const lead = {
  parameters: {utm_source:"facebook", utm_medium: "cpc" /* ... More parameters here, if they exist */},
  referrer: "http://www.facebook.com"
}

document.cookie = 'lead='+JSON.stringify(lead);
</script>
```

**Comment by FagnerMartinsBrack** [comment]
@Ezra-Siton-UIX It's impossible to achieve a cookie name that uses JSON using the **single quotes**, **no quotes**, or **doubles quotes unescaped** for the following reasons.

1. The JSON spec does not allow property values without quotes, neither JavaScript spec allows Object Literal values without quotes (only Object Literal keys).
2. Quotes in JSON **have to be** double quotes: the JSON spec does not allow single quotes in the structure.
3. The RFC 6265 does not allow double quotes in the cookie value because browsers can interpret that as having another meaning such as a **quoted cookie**.

Therefore, the only way for you to achieve what you want is if you don't use JSON and use plain strings that "look like" JSON but are not, like this:

```
Cookies.set('name', '{ foo: 'bar' }');
Cookies.get('name');
```

Does that work for you?

**Comment by hcygit** [comment]
encodeURIComponent is your rescue
