### ISSUE TITLE
Can you add "add" and "Replace" functions?

### ISSUE THREAD

**Issue by tomatodua** [js-cookie/js-cookie#520]
Would be nice if something like this will be implemented, will make things easier:

https://github.com/js-cookie/js-cookie/pull/519/files

it's just rough idea, but something useful shorthand used in many of our projects.

**Comment by FagnerMartinsBrack** [comment]
We don't want to add more methods to the library, only basic ones. You can create additional methods in your application by wrapping the `Cookie` api. The reason is that it adds more bytes for everyone to download at the expense of the cases of a few developers.

**Comment by tomatodua** [comment]
generally, any library that has many extensions, are more useful (and if any this moment only few devs use, more and more could have used extensions). it was probably about 500 bytes, but as you wish.

**Comment by carhartl** [comment]
> generally, any library that has many extensions, are more useful

Are you sure that‘s not just your opinion? I for instance, in contrast to this, believe, that simple libraries that are easily extensible prove to be useful.

**Comment by FagnerMartinsBrack** [comment]
I'm not sure if you're saying 500 bytes gzipped or not, but 500 bytes is a lot when the library gzipped is only ~900 bytes, that's 50% more!

Besides:

* Is it worth adding a `delete`? It's redundant since we already have `remove()`.
* Is it worth adding `append`? That encourages developers to create bigger cookies which should be avoided (Cookies can't exceed 4096 bytes as per RFC).
* Is it worth adding `toggle`? js-cookie is a data store and therefore shouldn't contain behavior in its methods other than to support it's CRUD operations. Toggle makes sense for things like buttons or UI toggling.

**Comment by FagnerMartinsBrack** [comment]
If there was a considerable number of people asking to implement certain operations (like what happened with the `Cookies.withConverter` which allows people to convert the default encoding/decoding mechanism) then this could be considered.
At this point, I think the byte size cost outweigh the potential benefits, which as I said in the bullet points above doesn't even seem to be a benefit.

**Comment by tomatodua** [comment]
@carhartl  I dont think that it's my opinion, like that millions of people, who uses jQuery. It's just the pure javascript wrapper, but library with many shorthand extensions. 

anyway, @FagnerMartinsBrack  thanks for taking time for answer.

**Comment by FagnerMartinsBrack** [comment]
@tomatodua Thanks for taking the time to share your findings here. Although most of the time feature requests don't land they are useful to understand how folks are using the lib :)

**Comment by carhartl** [comment]
Fwiw, the philosophy of jQuery has always been to provide a consistent, _concise_ API without a gazillion different functions, but instead provide extension points (that’s how the jQuery plugin ecosphere came to life). I know this, because I happen to have been part of the jQuery team a while ago. The same philosophy is at work here, as the origin of this library is a jQuery plugin. 

And then, speaking of extension points, I’m quite sure that the append functionality could be implemented using converters.

Last not least, this is open source! You can always fork and adapt the library to your specialized use cases.

**Comment by tomatodua** [comment]
@carhartl  thanks for the response!
my last question-  `append functionality could be implemented using converters` 
can you tell a bit more what you mean? any examples out there?

**Comment by carhartl** [comment]
Converters are described in the readme: https://github.com/js-cookie/js-cookie/blob/master/README.md#converters

Let's say all of our cookies would be "appendable", then we set up things like this (untested):

```javascript
var AppendingCookies = Cookies.withConverter({
    read: function (value, name) {},
    write: function (value, name) {
        return Cookies.get(name) + value;
    }
});
```
^^ But I realized there's a drawback to this - we're loosing out on the standard encoding which is applied otherwise. Plus calling `set()` is a bit counter-intuitive in that  case. So back to writing your own small extension(s), which probably look something like this:

```javascript
Cookies.append = function (name, value, attributes) {
    return Cookies.set((Cookies.get(name) || '')  + value, attributes);
}
```

**Comment by FagnerMartinsBrack** [comment]
@carhartl better avoid mutating objects you don't own in the application code (js-cookie). It seems better to create your own function that accepts js-cookie as a dependency and leverage closure:

const appendCookie = appendableCookie(Cookies);
appendCookie(name, value);
