### ISSUE TITLE
Cookies() to get all cookies is not supported in version 2.1.1

### ISSUE THREAD

**Issue by neitherzhu** [js-cookie/js-cookie#523]
Hi,

is `Cookies()` is not supported in v2.1.1?

in v2.1.0 
```js
const cookies = Cookies() // all my cookies
```

in v2.1.1
```js
const cookies = Cookies() // undefined
```

i read the code in v2.1.1. The `api` function is an empty function now.
in my lots of projects, i used `Cookies()` not `Cookies.get()`
 
so i wander if you could release v2.1.1 to  v3?

**Comment by carhartl** [comment]
Please stick to using the official, documented api. You were using something caused by an (accidental) side-effect not even us (me) was aware of. For the same reason there was no test for this behavior. This is not going to go into a possible future v3 either.

Again, please use documented, public apis exclusively.

**Comment by FagnerMartinsBrack** [comment]
For future readers: https://medium.com/@fagnerbrack/library-internals-do-not-exist-1ff50a30e3b0
