### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by ghazlawl** [js-cookie/js-cookie#525]
I noticed since the last update that we've been getting this error in the web console. Is there something we need to do on our end or is this something that needs to be addressed on your end?

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js?ver=5.2.2' with computed SHA-256 integrity 'Obj+Y2RiFyX/kEMaNK8Ph5dtlcAMv9HQ83EaPx+hoHs='. The resource has been blocked.`

**Comment by MartinKolarik** [comment]
You can't use the `integrity` attribute with a `@2` because it automatically updates to new 2.x.x versions and of course each version will have a different hash. If you have to use `integrity`, then use a link for a specific version, like `<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.js" integrity="sha256-P8jY+MCe6X2cjNSmF4rQvZIanL5VwUUT4MBnOMncjRU=" crossorigin="anonymous"></script>` (you can generate this [here](https://www.jsdelivr.com/package/npm/js-cookie))

**Comment by carhartl** [comment]
So we can close this?

**Comment by ghazlawl** [comment]
The reason I ask is because the documentation doesn't mention this at all. So, can we update the documentation?

**Comment by ghazlawl** [comment]
In reviewing with our other developers I see what's happened now. This topic can be closed; sorry for the confusion! (And thanks @MartinKolarik for explaining the @2 issue.)
