### ISSUE TITLE
A cookie associated with a resource at  was set with `SameSite=None` but without `Secure`. 

### ISSUE THREAD

**Issue by PiccoloYu** [js-cookie/js-cookie#555]
A cookie associated with a resource at  was set with `SameSite=None` but without `Secure`. 
![image](https://user-images.githubusercontent.com/44945137/68520947-1f9f9e00-02d7-11ea-843a-021197e60348.png)

**Comment by carhartl** [comment]
Where did you get it from that `SameSite` must only work with secure cookies?

SameSite is still in draft status, but in the draft nowhere is there a requirement like this mentioned. The opposite in fact:

> We considered
   restricting same-site cookies to secure contexts [secure-contexts] as
   a mitigation but decided against doing so

https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-6.2

I couldn’t find anything like this in the MDN docs either:
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies


BTW, you‘re using the api wrong, the 4th argument will be ignored, all options are going into a single object:

```javascript
Cookies.set('foo', 'bar', { sameSite: 'None', secure: false })
```

In this case it doesn’t matter because `secure` is by default `false`.

**Comment by carhartl** [comment]
Rereading this I think I may have misunderstood the bug report. If it’s the case that you’re expecting secure to be applied make sure to use the api in the right way. With a value of false though you’re not going to see `secure=false` as part of the resulting cookie string, as it acts like a boolean flag.

MDN has more information:
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
