### ISSUE TITLE
js-cookie not working on ios

### ISSUE THREAD

**Issue by ho3einfaramarzi** [js-cookie/js-cookie#629]
hi
why js-cookie working on all platforms but  not working in ios browsers ?

**Comment by carhartl** [comment]
Which platform and Safari (or different browser) version exactly are you experiencing problems in?

**Comment by carhartl** [comment]
I tested it on iPhone 11 w/ iOS 13 in Safari on BrowserStack and the test suite runs fine:

<img width="782" alt="Screenshot 2020-05-13 at 20 54 17" src="https://user-images.githubusercontent.com/21918/81853004-2a740d80-955c-11ea-94e3-d6f95bd24f04.png">

If you're referring to the setup in https://github.com/js-cookie/js-cookie/blob/master/browserstack.json, the reason there's no iOS in there is that back then when I was introducing BrowserStack based testing, I couldn't get automated testing to work for iOS devices (it would always hang forever when starting up the device). That's quite some time ago and it might be worth retrying.

**Comment by carhartl** [comment]
Here's an iPad Pro with iOS 12 in Safari:

<img width="856" alt="Screenshot 2020-05-13 at 21 00 37" src="https://user-images.githubusercontent.com/21918/81853556-dd446b80-955c-11ea-87c6-c7eb9506c5b7.png">

**Comment by carhartl** [comment]
@ho3einfaramarzi Please let us know what exactly doesn't work for you, plus browser and iOS version...

**Comment by moucznik** [comment]
I was able to replicate after opening Firefox 76 updated on May 5th.
- I go to "Responsive design mode" and there I select iPhone 6/7/8 Plus iOS11. 
- After that the cookies that would normally work in regular Firefox stop working.
I check that by setting the cookie and trying to get several seconds later.

Thank you very much for doing this library for us all.

**Comment by carhartl** [comment]
@moucznik Does it have anything to do with this library? Do you see a cookie when writing it as `document.cookie = 'foo=bar'`?

**Comment by moucznik** [comment]
@carhartl  after inserting I am getting ```Cookie “foo” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute ``` 

I have set ```sameSite: 'strict', secure: window.top.location.protocol === 'https:',``` in the js-cookie options
PS: this site should fulfill the secure condition

**Comment by carhartl** [comment]
Ok, and all of this is only a problem in Firefox *emulating* iOS?

**Comment by carhartl** [comment]
(The note regarding SameSite is expected I believe, since this is now the default behavior..)

**Comment by moucznik** [comment]
According to the statistics available from Sentry this is also a problem on firefox 75.0 and 76.0 on iPhone and Macs.

**Comment by carhartl** [comment]
> According to the statistics available from Sentry this is also a problem on firefox 75.0 and 76.0 on iPhone and Macs.

What kind of statistics? Error tracking for your site?

I can run the test suite just fine in Firefox 76.0.1 Responsive Design Mode:

<img width="1274" alt="Screenshot 2020-05-18 at 20 36 01" src="https://user-images.githubusercontent.com/21918/82247846-6ab20200-9947-11ea-9720-4ad2ea9918e7.png">

I'm suspecting there's something else in your application or browser/environment interfering.

**Comment by moucznik** [comment]
@carhartl  It seems that it only affects the windows version of firefox 75.0.X and 76.0.X mac seems to work fine

**Comment by carhartl** [comment]
@moucznik Tested with Firefox 76 in Windows 10:

<img width="1253" alt="Screenshot 2020-05-19 at 10 57 27" src="https://user-images.githubusercontent.com/21918/82306651-9c66af80-99bf-11ea-8afc-b14c4abac7e4.png">

<img width="1253" alt="Screenshot 2020-05-19 at 10 57 02" src="https://user-images.githubusercontent.com/21918/82306641-9a9cec00-99bf-11ea-9464-c88295a90887.png">

I'm really not sure how to reproduce the problem you're seeing. You might provide me the exact details of Windows and Firefox you're seeing the problem in, also check all installed extensions. It might be even more helpful to come up with a jsfiddle that would expose the problem at hand, since it could still very well be a problem in your application..

**Comment by carhartl** [comment]
Due to inability to reproduce and lack of feedback of the OP I am closing this.

@moucznik If you manage to provide a reproducible test case please open a new issue, this doesn't seem to relate to iOS.

**Comment by ho3einfaramarzi** [comment]
hi
cookie values remove after  go to other page in ios
why remove it?

**Comment by carhartl** [comment]
> cookie values remove after go to other page in ios

I can’t really reproduce this. I‘m going to try harder later.. in the meantime, could you provide a jsfiddle showcasing this behavior?

**Comment by ho3einfaramarzi** [comment]
this is my code :
Cookies.set('iocookie', 'default');
but in ios cookie values remove after go to other page

**Comment by carhartl** [comment]
@ho3einfaramarzi 

With this amount of information I'm afraid we're not able to help you. I've have tested a simple two page app on iOS 13.4.1 with Safari and I can retrieve the cookie that was written on the first page just fine on the second.

Here are some general pointers:

- Check for whether you have an `unload` event defined in your app that may delete cookies upon leaving page
- Check whether you have Cookies disabled altogether, or some cookie blocking extension enabled

Apart from that you might still want to answer these, in order to narrow down the problem if aforementioned doesn't lead to uncovering the problem:

- Which version of iOS and which browser do you see the problem in
- Which version of js-cookie are you using
- Set up a jsfiddle allowing to reproduce the problem

**Comment by carhartl** [comment]
Could this be a hint? https://github.com/js-cookie/js-cookie/issues/192#issuecomment-647188661

**Comment by trungducng** [comment]
this lib cause an issue for all my ios devices (iphone, ipad) in all browser (safari, chrome), work fine in other devices

**Comment by Drmzindec** [comment]
Also having an issue with Safari (Version 14.0) on iOS (Version 10.14.6).

Issue in console as follows:

- ReferenceError: Cant find variable: module
- ReferenceError: Cant find variable: Cookies

This works perfectly fine on all browsers in windows, as well as any other browser on iOS, just safari where the issue lies.

**Comment by carhartl** [comment]
@Drmzindec 👉 https://github.com/js-cookie/js-cookie/issues/698#issuecomment-880466721
