### ISSUE TITLE
add dist folder 

### ISSUE THREAD

**Issue by nostalgiaz** [js-cookie/js-cookie#66]
Hi! 
Nice library!

I use this library over Django and I use the `collectstatic` management command in order to copy all the static files into the same folder.
Due to space limit, we ignore the `src` folder (with the `-i src` option)  because this folder is always used for the source of the code, not for the dist, and we don't need these files in production.

So, can you please add a `dist` folder with the `js-cookie.js` file? Thanks!

**Comment by FagnerMartinsBrack** [comment]
Hi, are you using npm or bower for package management?

This has been brought several times, the main reason for not adding a dist folder is that the git source repository is not supposed to contain production code.

I ask if you are using npm, because then by implementing a custom build process in this repository we might be able to provide the dist folder for each release on npm, unfortunately that is still in the TODO list with no ETA (see #57).

Also, see the following issues for context:
https://github.com/carhartl/jquery-cookie/issues/350,
https://github.com/carhartl/jquery-cookie/issues/223,
https://github.com/carhartl/jquery-cookie/pull/71,
https://github.com/carhartl/jquery-cookie/issues/223,
https://github.com/carhartl/jquery-cookie/issues/121

**Comment by FagnerMartinsBrack** [comment]
@nostalgiaz I am not familiar with Django. Does exposing the dist files [on npm](https://www.npmjs.com/package/js-cookie) instead of the [git repository](github.com/js-cookie/js-cookie) solves your problem?

**Comment by nostalgiaz** [comment]
I think that the npm package should not contain the source code, but only the dist folder. For example, bootstrap uses this package manager to provide to the users only the css version of their stylesheets, and not the sass one (https://www.npmjs.com/package/bootstrap). The same should be for the bower package.

**Comment by FagnerMartinsBrack** [comment]
I'll interpret your last comment as a "yes", providing the source files in npm is probably the only way to solve the issue with the [collectstatic](https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#collectstatic) API you mentioned.

Since we already have plans for an automatic release process, I will be closing this and start tracking this problem in #57. There is no ETA though.
