### ISSUE TITLE
Adding Separate file which will include large diapason of functionalities

### ISSUE THREAD

**Issue by ttodua** [js-cookie/js-cookie#664]
Of course, the first what should be said again, we all know this library tends to aim to be the slimmest and just coming to support the most basic functionalities (read/write/delete cookies).

However, It will be nice if there will be a separate (second one) library which will have additional functionalities, so users can decide themselves, if they want to use the "small" library (which you currently have) or a bit large, library with more shorthands for functionalities, so users, who are willing to use a bit larger files (just 1 kb larger I assume), but have many handy features which they use everyday. I am sure, many users will start using that.

For example, what I see, many developers misuse the cookies functionalities, to set the different cookie for each option.
for example, many people do:

Cookie.Set("homepage", "/specific-page.html");
Cookie.Set("last_visit",     "2020-.....");

(please don't grasp this exact examples, they are just examples).
What I want to say, that for example, it has been a while, that I've been using [my custom solution ](https://github.com/ttodua/useful-javascript/blob/master/cookies-library.js)to store 1 cookie in JSON format, where all individual options will reside as subkeys.

So, i use my solution to have one cookie for website (like: `myMainCookie`  which value is: `'{ homepage: "/my-page.html", last_visit: "2020...", chosen_color: "#123" }'`;   ) where are stored all individual options and then i use :

`Cookiess.setOption('myMainCookie', 'homepage', '/blabl.html');`

and then:

`Cookiess.getOption('myMainCookie', 'homepage');`

So, I work with one cookie which has sub-objects/arrays. 

I also have some other shorthands, like:
`Cookiess.isSet()` 
`Cookiess.append()` 
and etc..

if you will try to shoot and you will have a separate file (1kb larger) aside to your main js, which will include additional shorthands that users use frequently, this library will be used by many people i am sure, including my team. (the success of jquery was that it made shorthands available to users, otherwise we could still do the same with plain JS. however, people tend to like ready-made, standartized libraries). 

Thanks.

**Comment by carhartl** [comment]
Thanks for these ideas! I’m having difficulties deriving a concrete feature request other than „let‘s build another library on top of this one that can do more things“. I‘m afraid we will not have the capacity at this point to build, and, more importantly, maintain such a thing. These are exactly the things we want to enable developers to build themselves with this simple library, i.e. provide the building blocks to implement specific functionality taylored towards more specific application needs. Go ahead and publish such a “separate file” as another npm package maybe, just as an idea — ensuring a stable api is on us :)

**Comment by ttodua** [comment]
Hm, isn't there mentioned not one, but even several concrete features? 
```
Cookiess.setOption()
Cookiess.getOption()
Cookiess.isSet()
Cookiess.append()
```
strange you had difficulties deriving a concrete feature request other than "lets build".
ok, as you wish. thnx

**Comment by carhartl** [comment]
>strange you had difficulties deriving a concrete feature request

The issue’s title read “Adding Separate file which will include large diapason of functionalities”. Then you went on to give examples of what seemed (to me) to be subset of these desired functionalities. Possible I was a bit biased given the title. Either way, my point of view hasn’t changed, what you’re basically requesting is a second type of library, but as I already explained, we don’t have the time to support this.

>btw, i don't use NPM at all, why that was mentioned specifically?

If you wish to build additional functionality as proposed, instead of asking us to build and maintain it, npm is __one__ possibility to distribute it yourself once you‘ve built it. That is, if you deem it useful for others (which seems to be the case, otherwise you wouldn’t have sent a feature request I guess). Hence I was mentioning it as a suggestion, an alternative, given we were going to reject the feature request. It’s absolutely your choice of course.
