### ISSUE TITLE
Possible to minify the library even more?

### ISSUE THREAD

**Issue by ttodua** [js-cookie/js-cookie#665]
It might be some slight reduction in size, if repeated functions are shortcuted, like: https://www.diffnow.com/report/60ehk
will make the library few bytes smaller.  also, `document.cookie, i.expires, typeof document!="undefined"` mentioned several times, can they be shorthanded, or it affects smth? I suppose min.js version is not meant for readability.

**Comment by carhartl** [comment]
We’ve tried a variety of things in the past, capturing some things in variables amongst them (didn’t yield the desired outcome back then). _Adding gzip to the game, the outcome of certain tricks is not always as obvious as it seems at first glance._ The tool that you were using doesn’t seem to take gzip compression into account. Our goal is to come up with the smallest possible size, when gzipped.

But we have our own tooling in place.

If you clone the repository, and set up the required dependencies (see https://github.com/js-cookie/js-cookie/blob/master/CONTRIBUTING.md#getting-started) you can run `grunt compare_size` to see the effect of a particular change. Run it once against HEAD without any changes in order to have a baseline. It can be a lot of fun experimenting and finding a change that would yield a smaller (gzipped!) lib size. If you find a change that has the desired outcome please send a PR, we’ll be more than happy to accept it.

Btw, here’s an example PR of such successful micro-optimization: https://github.com/js-cookie/js-cookie/pull/576
