### ISSUE TITLE
Read cookies return String value 'undefined'

### ISSUE THREAD

**Issue by maghffu** [js-cookie/js-cookie#673]
**Describe the bug**
When I read the cookie using this syntax 
```Cookies.get('nothing')```
it will return string with value 'undefined' instead returning undefined type data.

**To Reproduce**
``` 
const value = Cookies.get('nothing')
console.log(typeof value) // <-- 'string'
if (value) {
  // here will be executed
}
```

**Expected behavior**
since return value is string it will give result true when use conditional operator

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser chrome
- Version 86

**Comment by carhartl** [comment]
What does `Cookies.get()` return?

**Comment by carhartl** [comment]
Seems to work fine, cannot reproduce:

![VirtualBox_Ubuntu_17_11_2020_15_44_29](https://user-images.githubusercontent.com/21918/99404474-f8b57800-28eb-11eb-8883-72637aaa8518.png)

Make sure you do not accidentally have a cookie in place for `nothing` with the String value `undefined` <= this can happen if you do something like `String(undefined)`. I believe there was a bug in an older version that may cause this behavior after attempting to write an undefined value, .e.g. `Cookies.set('foo', undefined)`. In later versions we skip writing such a cookie. Make sure you're using an up-to-date version of the library.

**Comment by maghffu** [comment]
ok, thanks @carhartl

**Comment by echo-999** [comment]
This happened to me. I'm using it in a React App along with jsonwebtoken. 
```
useEffect(() => {
    /** If the user reloads the page, but the access token exists, set the credentials again */
    // console.info("typeof Cookies.get("accessToken"): ", typeof Cookies.get("accessToken"));
    if (Cookies.get("accessToken")) {
      const decodedToken = jwt.decode(Cookies.get("accessToken"));
      // console.info("decodedToken: ", decodedToken);
      setCredentials(decodedToken);
    }
  }, [state.isLoggedIn]);
```
This caused an error when the `setCredentials` action was being dispatched. Initially, the `accessToken` cookie is not set. When the component first mounts, the `useEffect` runs. Since `Cookies.get("accessToken")` returned a `string` of "undefined", it passed the if statement, and `jsonwebtoken` tried to decode it, which inevitably caused the `setCredential` function to throw an error since the fields that I expected to get from the `decodedToken` are `null`

![image](https://user-images.githubusercontent.com/60455353/148910026-10e131dc-daf0-4ba4-8f21-cc14b207a63e.png)


I changed the `if statement`  in the `useEffect` to:

```
if (Cookies.get("accessToken") !== "undefined")
```

And it's now working.

**Comment by blamarvt** [comment]
I have the same issue with Sveltekit. The odd (?) thing is that I'm seeing `Cookies.get(...)` return a true `undefined` on the SSR and then the string `"undefined"` on the CSR. I can't afford to debug further right now but I'll return to this issue if I figure it out!
