### ISSUE TITLE
'undefined' as a string value

### ISSUE THREAD

**Issue by chrwei** [js-cookie/js-cookie#685]
`Cookies.set("foo")` produces a cookie with the string value 'undefined'.  I expected either a removed cookie, or somehow a undefined or null, not a string value of 'undefined'.  

The reason I even had this code is because the nodejs cookies library uses this method to remove cookies.  Since you use the same object name and your API is the same for get() it would great if the APIs were compatible for set() as well. 

If you don't care to be compatible, throwing an error would also be acceptable if the value parameter is required and not passed.

**Comment by carhartl** [comment]
You‘re not using the api according to documentation.

**Comment by chrwei** [comment]
I know that, that's why it's a feature request and not a bug report

please consider the new feature

**Comment by carhartl** [comment]
At the moment there‘s not a defined behavior for such a case, simply because there‘s no expectation at all for the api being used in that way — and I intend to keep it that way.

I don‘t want to overload the setter with some sort of remove behavior. “somehow a undefined or null” isn’t possible as we need a string when writing a cookie. In other words “undefined” is already the somehow you’re asking for.

**Comment by carhartl** [comment]
Would leave the option to not write a cookie at all, or maybe with an empty string as value, but I don’t see the benefit, as we don’t intent to change the api.

**Comment by carhartl** [comment]
Possibly guard against incorrect usage like for the getter:

https://github.com/js-cookie/js-cookie/blob/eceefcc0be5bcb07d6ca32b03978e2c6f8cc848e/src/api.mjs#L51
