### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by AliHassan13** [js-cookie/js-cookie#703]
i'm using this package in my PHP web application via CDN that's the url 
`<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>`
now i'm facing this **ERROR** 

`js.cookie.js:131 Uncaught ReferenceError: module is not defined
    at js.cookie.js:131`
    
now it doesn't save the token in cookie. i'm using this code to save it
` Cookies.set('token', token, {expires: in60Minutes});`
  
pakage version : 3.0.0

**Comment by andymsuk** [comment]
This is fixed in v3.0.0-rc.4 - see the [release notes](https://github.com/js-cookie/js-cookie/releases/tag/v3.0.0-rc.4).

You can therefore fix this by changing your `script` tag to:
`<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0-rc.4/dist/js.cookie.min.js"></script>`

However, as per the release notes, the package owners "advise to always use the latest stable version in production environments."

**Comment by AliHassan13** [comment]
@andymsuk Thanks a lot.
