### ISSUE TITLE
ADD deleteAllCookies()  method 

### ISSUE THREAD

**Issue by hasnath1** [js-cookie/js-cookie#719]
In this library , we have all the things we need , But sometimes deleting each cookie with Cookies.remove() one by one . It feels tedious . 
some people like me sometime want to delete all the cookies from the browser with just one method . 
So My request is to add a method deleteAllCookies()  to the Cookie class  . 

----------------------------  HERE IS A SOLUTION   --------------------------- 
```
const deleteAllCookies = () => {
  const cookies = document.cookie.split(";");

  for (let i = 0; i < cookies.length; i++) {
    const cookie = cookies[i];
    const eqPos = cookie.indexOf("=");
    const name = eqPos > -1 ? cookie.substr(0, eqPos) : cookie;
    document.cookie = name + "=;expires=Thu, 01 Jan 1970 00:00:00 GMT";
  }
};
```
PLEASE JUST ADD THIS . IN CASE SOMEONE NEEDS THAT .

**Comment by carhartl** [comment]
Thank’s for the proposal. There’s a (shorter) solution provided in the FAQ: https://github.com/js-cookie/js-cookie/wiki/Frequently-Asked-Questions#how-to-remove-all-cookies

It’s simple enough so that we believe we won’t need to add something like this to the library, which we try to keep as lightweight as possible, giving you the building blocks to implement further functionality on top.
