### ISSUE TITLE
Fail on not-set cookies?

### ISSUE THREAD

**Issue by vemv-kantox** [js-cookie/js-cookie#86]
If I am in `mydomain.com` and attempt to `Cookies.set('foo', 'bar', {domain: 'ANOTHERdomain.com'})`, nothing will happen, as I understand it.

In other words, the write silently fails. Wouldn't it be good to do some sanity checks regarding secure/domain/path options for ensuring `.set` always does what we believe to?

**Comment by FagnerMartinsBrack** [comment]
There is a few drawbacks in doing this check inside js-cookie:

1. If we choose to do that, we would have to accept any other sanity check for all kinds of inputs, which should be tested and supported from now on.
2. Let's say we do choose to accept "1". Considering that one of the features of js-cookie is being a lightweight lib for handling cookies, I don't see how the benefit of validating the domain attribute in inside js-cookie is worth the increase of characters that it will bring.

The only solution I can see for cases like this is to enhance the documentation with additional info regarding how it is going to work (preventing [abstraction leaks](https://en.wikipedia.org/wiki/Leaky_abstraction) like this one). In this specific case I believe it is perfectly understandable that setting a cookie with a different domain will yield an undefined result due to an obvious security hole it would be if the browser allowed otherwise, perhaps this could be mentioned in the docs.

**Comment by FagnerMartinsBrack** [comment]
I have created #87 to enhance the domain attribute documentation. Maybe something could be mentioned there regarding this.

**Comment by vemv-kantox** [comment]
Hi! Thanks so much for the reply.

Regarding point **1**, I don't think my proposed change would imply that every argument has to be checked (particularly type-checked). If I pass a `Number` instead of a `String`, any unexpected/undefined behavior will be entirely my fault, not any library's.

Cookie behavior is tricky though, and help for using them correctly would be greatly appreciated. Real code can artitrarily complex: cookies can be dynamically set, JS code can be invoked by either `<script>` or `<iframe>` tags in either a first-party or third-party domain...

The reason why I opened this ticket was not a "hey, let's do a random improvement" moment, but a real need - my cookies were not being set (and I wasn't passing bad secure/domain/path opts) and I didn't know why. If the library can help - it should!

Regarding point **2**, that would be clearly addressable by having development features that would be discarded in production/minification. React does this extensively:

> We provide two versions of React: an uncompressed version for development and a minified version for production. The development version includes extra warnings about common mistakes, whereas the production version includes extra performance optimizations and strips all error messages.

Seems worth a shot in my opinion!

**Comment by FagnerMartinsBrack** [comment]
> Regarding point 2, that would be clearly addressable by having development features that would be discarded in production/minification

Very good idea. I am not familiar with React though, but it seems pretty simple to create a file that can be included after `js.cookie.js` and stub its related methods. Perhaps it should be something for a different repository.

**Comment by vemv-kantox** [comment]
Just so you can have a better idea of my request and why I find it so necessary, here's an issue I'm having right now.

![screen shot 2015-09-14 at 14 15 01](https://cloud.githubusercontent.com/assets/12593885/9849406/19a4987c-5aeb-11e5-8790-10462a863081.png)

Here `Cookies.remove` doesn't remove any cookies even though the options match those with which the cookies were set. Why? No idea. Couldn't the library help? Reporting failures is something any API does... they throw an exception, return an error message, give info such as `"0 cookies matched your options."`... something. Not nothing.

(FYIi I found the fix for that in particular - but the problem I point out remains)

IMO js-cookie shouldn't need an extra library just for getting the behavior one would expect from any API!

**Comment by FagnerMartinsBrack** [comment]
Thanks for the print, it helped a lot. In this case I can see the value of shipping `js.cookie.debug.js` upon release that does all necessary sanity checks and prints to the console in the form of a `console.warn`. What do you think? I can do that along with #57.

**Comment by vemv-kantox** [comment]
`console.warn` seems enough. Thank you!

**Comment by FagnerMartinsBrack** [comment]
> console.warn seems enough. Thank you!

You're welcome :)
I will be tracking this in #57 then, I have added a bullet point there.
