### ISSUE TITLE
After the expiration date of the cookie, resetting the cookie will fail if the page is not refreshed

### ISSUE THREAD

**Issue by qiiuyl** [js-cookie/js-cookie#863]

**Comment by qiiuyl** [comment]
First, execute this program.
const expiresTime = new Date(new Date().getTime() + 180 * 1000)
export function setCookie(key:string) {
  Cookies.set('token', key, { expires: expiresTime })
}

Three minutes later, the cookie can't be seen in the browser. This suggests that the cookie you set in first step was successful.

Do not refresh the page, repeat the cookie setting operation again.
const expiresTime = new Date(new Date().getTime() + 180 * 1000)
export function setCookie(key:string) {
  Cookies.set('token', key, { expires: expiresTime })
}

I can't see the cookie set up for the second time.

**Comment by oliver139** [comment]
Have investigated into this issue, but turns out that the problem should be come from `expiresTime`, where it is not updated before the second call, so that same `expiresTime` is used, and then the cookie expired immediately.

Wrapping it into a function, which make sure the `expiresTime` will be assigned again, should solve the problem.
```js
function setCookie(key) {
  const expiresTime = new Date(new Date().getTime() + 180 * 1000)
  Cookies.set('token', key, { expires: expiresTime })
}
```
