### ISSUE TITLE
Warning message for overflow

### ISSUE THREAD

**Issue by WillemLabu** [js-cookie/js-cookie#88]
As hinted at in #86, warning or error messages would be useful.
I agree with your sentiment there that domain handling and sanity checks like that shouln't really be part of this repo, however, what I'm proposing here is different.

It would be useful to see a warning when trying to set a cookie with a string that is too long for the browser to keep, thus not setting the cookie at all.

For instance:

```
  Cookies.set('myJSON', { stringified JSON that overflows the max of 4096 bytes })
```

Currently, this fails silently. It would be useful to see a warning.
Here is an example of how Angular does it with `$cookies`:

    > Cookie 'myJSON' possibly not set or overflowed because it was too large (6129 > 4096 bytes)!

*Please note [this SO answer](http://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key) - 4093 bytes should be used as a max.*

Thoughts?

**Comment by FagnerMartinsBrack** [comment]
`js-cookie` has historically been a simple wrapper for browser's `document.cookie`, like a [Facade](https://en.wikipedia.org/wiki/Facade_pattern). But in order to keep its lightweight properties, since the begining it always required knowledge of native cookies behavior implicitly.

Sanity checks are out of scope from `js-cookie` (or at least from v2 due to backwards compatibility concerns), but not from the docs. Like #86, we can also enhance the docs to document this behavior.

Related to #76, https://github.com/carhartl/jquery-cookie/issues/221#issuecomment-25524090.

**Comment by FagnerMartinsBrack** [comment]
@WillemLabu

I will be creating a `js.cookie.debug.js` file with sanity checks on #57 as stated in a similar problem on [this issue](https://github.com/js-cookie/js-cookie/issues/86#issuecomment-140058592).

Does that works for you?

**Comment by WillemLabu** [comment]
That's awesome, and I'm glad you guys are on the ball.
Native cookies are a pain, and you're doing great work to make a lot of people's lives easier.

Thank you! :+1:

**Comment by FagnerMartinsBrack** [comment]
I have added a new bullet point at #57.
