### ISSUE TITLE
Setting key with some value incorrectly returns wrong type and value upon get()

### ISSUE THREAD

**Issue by ivan-nikitovic** [js-cookie/js-cookie#89]
```javascript
Cookies.set('test', "73308954234454016"); 
Cookies.get('test')
```

I get this in console:
```
73308954234454020
```

Setting String but getting Number with completely different value.

**Comment by FagnerMartinsBrack** [comment]
@ivan-nikitovic I tested the following code in a local server and it is working:

```javascript
console.log( Cookies.set( "test", "73308954234454016" ) );
console.log( typeof Cookies.get( "test" ) );
```

It prints:

```shell
test=73308954234454016; path=/
string
```

Can you please post the contents of the `Cookies.json` property before the `get` call? Like:

```javascript
console.log( Cookies.json ); // Is this truthy?
Cookies.set('test', "73308954234454016"); 
Cookies.get('test');
```

**Comment by ivan-nikitovic** [comment]
@FagnerMartinsBrack here is the output from console:

```javascript
true
73308954234454020
```

**Comment by FagnerMartinsBrack** [comment]
`Cookies.json` [is a leftover from the old `$.cookie.json` API](https://github.com/carhartl/jquery-cookie/commit/796abd66a0b2af7139da5dd86a464b7884d2faaf#diff-c22d3dae3096e8abf2a44ccb719800ddR38). You need to make sure that `Cookies.json` is not set to `true` when upgrading from jQuery Cookie.

At the time I choose to leave this, because it also serves as [an internal flag](https://github.com/js-cookie/js-cookie/blob/f28a0fdfc0f780406a4f083c1ec410c77acf55ec/src/js.cookie.js#L122) that is only exposed due to JS lack of visibility constraints.

Also it serves as a convenience in case you forgot to use `Cookies.getJSON()` in place of `$.cookie.json = true`, then it would not break your code upon `Cookies.get()` when it depends on the `json` flag set to `true`. But that is an undocumented behavior and should not be relied upon, the [changelog](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0) states clearly that:

> json config is removed, use Cookies.getJSON()

The solution would be to remove the code that set `Cookies.json = true` and use `Cookies.getJSON()` in places that depends upon the `Cookies.get()` call returning the same type as the previous version.

**Comment by FagnerMartinsBrack** [comment]
I will assume this is solved. I don't think it makes sense changing the property name now, ideally you should not modify objects you don't own and the changelog states clearly that `Cookies.json` is not supported anymore.
